### ISSUE TITLE
运行失败。。

### ISSUE THREAD

**Issue by matthkewk** [huanghyw/jd_seckill#1]
python main.py
  File "main.py", line 17
SyntaxError: Non-ASCII character '\xe5' in file main.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by huanghyw** [comment]
看一下配置文件是否正确

**Comment by matthkewk** [comment]
翻了好几遍，问一下cookies_string和cookies是同一个吗，因为并没有找到cookies_string值。。

**Comment by huanghyw** [comment]
cookies_String 这个填的就是http request header里面的cookies
