### ISSUE TITLE
cookie不会获取，有没有详细的教程，非常感谢

### ISSUE THREAD

**Issue by taylor618** [huanghyw/jd_seckill#10]

**Comment by wzphood** [comment]
> _No description provided._
登陆京东，打开控制台，network界面，然后随便刷新页面，network里面的.js的headers里有

**Comment by taylor618** [comment]
> > _No description provided._
> > 登陆京东，打开控制台，network界面，然后随便刷新页面，network里面的.js的headers里有

谢谢，找到了

**Comment by taylor618** [comment]
已解决
