### ISSUE TITLE
检测本地时间与京东服务器时间误差为【-151】毫秒

### ISSUE THREAD

**Issue by ZRT-1998** [huanghyw/jd_seckill#100]
出现这个问题是否说明脚本无法成功运行

**Comment by DLwyp** [comment]
> 出现这个问题是否说明脚本无法成功运行

成功了，只是说明你自己机器的时间比京东服务器的时间慢151毫秒

**Comment by ZRT-1998** [comment]
不是这个意思，这里是负号，是不是说明服务器时间获取的不对

**Comment by DLwyp** [comment]
> 不是这个意思，这里是负号，是不是说明服务器时间获取的不对

负号就是比京东服务器慢啊，那块代码是用本地时间-京东时间得到的

**Comment by ZRT-1998** [comment]
额，延迟应该是正数

**Comment by huanghyw** [comment]
> 额，延迟应该是正数

@DLwyp D 说的是对的，负延迟就是本地比服务器慢，这个无所谓，用差值算出正确的时候就行
