### ISSUE TITLE
抢购是否需要前台开着挂机？

### ISSUE THREAD

**Issue by 91chen1** [huanghyw/jd_seckill#101]
我这边显示我切换过去抢购窗口的时候才开始一路抢购

**Comment by DLwyp** [comment]
> 我这边显示我切换过去抢购窗口的时候才开始一路抢购

cmd打开的？

**Comment by 91chen1** [comment]
> > 我这边显示我切换过去抢购窗口的时候才开始一路抢购
> 
> cmd打开的？

main.py这个打开的，窗口确实是cmd的

**Comment by huanghyw** [comment]
提前十分钟开始挂机就行
