### ISSUE TITLE
二维码登录失败

### ISSUE THREAD

**Issue by whherui** [huanghyw/jd_seckill#108]
哪位大神遇到过吗？

![微信截图_20201228102831](https://user-images.githubusercontent.com/13448641/103185456-7c08b700-48f7-11eb-8a30-6cf306fb9ba3.png)

**Comment by huanghyw** [comment]
图片查看软件背景需要是白色

**Comment by whherui** [comment]
> 图片查看软件背景需要是白色

Windows 10 系统自带的 图片 查看器
