### ISSUE TITLE
大佬有没打算写个淘宝和苏宁的呀？

### ISSUE THREAD

**Issue by YetNeleven** [huanghyw/jd_seckill#109]
京东这个是跑起来的，小白信用98+，但跑代码的时候经常能看到错误代码出来，是账号被黑了吗还是京东无望了。
想说来个淘宝和苏宁的一起抢抢~

**Comment by huanghyw** [comment]
主要关注下日志里面有“很遗憾”的输出就证明配置没问题，错误代码可以忽略。

淘宝、苏宁暂不考虑，以后再说吧。
