### ISSUE TITLE
这样并发会被拉黑吗

### ISSUE THREAD

**Issue by avriler** [huanghyw/jd_seckill#11]
试了一下，预约也不行。
![Image 2](https://user-images.githubusercontent.com/1689289/102207412-05d47f80-3f09-11eb-9ae8-04085f3421ba.jpg)

**Comment by huanghyw** [comment]
更新最新代码，并且检查下配置

**Comment by avriler** [comment]
多进程好像动不了，  进去就卡在这边了
![微信图片_20201216124829](https://user-images.githubusercontent.com/1689289/102306381-0ae30e80-3f9d-11eb-8b70-bfd8a8802f03.png)

**Comment by huanghyw** [comment]
目前没有遇到这个问题，首先确认下依赖是否都正确安装。我这没有Windows环境，方便的话您调试一下，看看具体什么问题。
