### ISSUE TITLE
INFO: 抢购链接获取失败，稍后自动重试

### ISSUE THREAD

**Issue by dudumuta** [huanghyw/jd_seckill#115]
二维码图片用百度的二维码解析器重新优化后可以识别；但是抢购时提示这个“INFO: 抢购链接获取失败，稍后自动重试”

**Comment by huanghyw** [comment]
提示这个是抢购链接还没有放出来，根据历史情况来看，一般在1.1秒后会放出抢购链接

**Comment by dudumuta** [comment]
哦，我是在10点30左右看的。正常的就好，明天试试

**Comment by huanghyw** [comment]
OK

**Comment by huanghyw** [comment]
图片查看器只要是白色背景就能正常扫二维码

**Comment by yx9881** [comment]
> 提示这个是抢购链接还没有放出来，根据历史情况来看，一般在1.1秒后会放出抢购链接

1.1秒 指的是每天 10点后的 1,.1 秒吗？

**Comment by huanghyw** [comment]
对
