### ISSUE TITLE
有大佬晒一下今天抢到的么??

### ISSUE THREAD

**Issue by jiehao321** [huanghyw/jd_seckill#117]

**Comment by Lasx** [comment]
抢到了

**Comment by jiehao321** [comment]
大佬看下日志

**Comment by Lasx** [comment]
INFO:抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
INFO: 访问抢购订单结算页面...
INFO: 生成提交抢购订单所需参数...
INFO: 获取秒杀初始化信息...
INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
INFO: 访问抢购订单结算页面...
INFO:生成提交抢购订单所需参数...
INFO: 获取秒杀初始化信息...
INFO:抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
INFO: 访问抢购订单结算页面...
INFO: 生成提交抢购订单所需参数...
INFO: 获取秒杀初始化信息...
INFO: 提交抢购订单...
INFO: 提交抢购订单...
INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
INFO: 访问抢购订单结算页面...
INFO: 抢购成功，订单号:XXXXXXXXXX 总价:2998.00, 电脑端付款链接

3秒抢到的。

**Comment by zhengwei19003** [comment]
@Lasx 可以发一下你的配置文件吗？config.ini

**Comment by mendylove** [comment]
京东手动抢到过2瓶，这个还不会用。

**Comment by Lasx** [comment]
> @Lasx 可以发一下你的配置文件吗？config.ini

默认只改改了eid fp

**Comment by yliu46** [comment]
> INFO:抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> INFO: 访问抢购订单结算页面...
> INFO: 生成提交抢购订单所需参数...
> INFO: 获取秒杀初始化信息...
> INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> INFO: 访问抢购订单结算页面...
> INFO:生成提交抢购订单所需参数...
> INFO: 获取秒杀初始化信息...
> INFO:抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> INFO: 访问抢购订单结算页面...
> INFO: 生成提交抢购订单所需参数...
> INFO: 获取秒杀初始化信息...
> INFO: 提交抢购订单...
> INFO: 提交抢购订单...
> INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> INFO: 访问抢购订单结算页面...
> INFO: 抢购成功，订单号:XXXXXXXXXX 总价:2998.00, 电脑端付款链接
> 
> 3秒抢到的。

小白多少分啊？
