### ISSUE TITLE
'...'.format(...) has unused arguments at position(s): 0

### ISSUE THREAD

**Issue by SmileJohnson** [huanghyw/jd_seckill#119]
代码395行 payload = {
            'callback': 'jQuery'.format(random.randint(1000000, 9999999)),
            '_': str(int(time.time() * 1000)),
        }

提示报错：'...'.format(...) has unused arguments at position(s): 0

**Comment by huanghyw** [comment]
python什么版本？

**Comment by SmileJohnson** [comment]
> python什么版本？

3.7

**Comment by huanghyw** [comment]
代码确实不对，少个占位符，稍等我修改下

**Comment by huanghyw** [comment]
#132 已合并代码了，您更新下

**Comment by SmileJohnson** [comment]
> #132 已合并代码了，您更新下

好的，麻烦你了
