### ISSUE TITLE
有抢购成功过的同学吗

### ISSUE THREAD

**Issue by tsuiyuenhong** [huanghyw/jd_seckill#12]

**Comment by huanghyw** [comment]
我应该是运气比较好，三个账号，抢购了三次，抢到两次。主要还是看运气，只要配置没问题，每天试一试，总会抢到的。

**Comment by tsuiyuenhong** [comment]
> 我应该是运气比较好，三个账号，抢购了三次，抢到两次。主要还是看运气，只要配置没问题，每天试一试，总会抢到的。

Thanks, 我还发了邮件给你🤦‍♀️，谢谢回复

**Comment by huanghyw** [comment]
客气了
