### ISSUE TITLE
苏宁大家还有办法加购物车吗？(加进购物车好抢多了)

### ISSUE THREAD

**Issue by iNOmoNey** [huanghyw/jd_seckill#120]
前段时间还可以，现在苏宁貌似加了验证，各种办法都试了茅台就是加不进购物车
不知道有没有大佬有奇淫怪技

**Comment by tttxx** [comment]
确实，加进购物车的号都抢到了

**Comment by Lstoryc** [comment]
> 确实，加进购物车的号都抢到了
6666 怎么玩

**Comment by iNOmoNey** [comment]
> > 确实，加进购物车的号都抢到了
> > 6666 怎么玩

购物车等着，到点选中茅台去结算。
直接就会进下单页面。没有什么活动火爆的弹窗

**Comment by wuchiawuchi** [comment]
等个奇淫怪技

**Comment by huanghyw** [comment]
已经不行了，简单的写了个代码测试下，已经在程序后端做了验证。

```js
jQuery17209914492524519483_1609161816793({"customerNo":"6061011577","isSuccess":"N","addCartErrorList":[{"itemNo":"0","cmmdtyCode":"000000011001203841","cmmdtyName":"","shopCode":"30000757","errorCode":"051","errorMessage":"该商品只能通过立即购买进行下单","errorIgeTag":"0","backErrorCode":"MC570001","uomErrorCode":"ccf-gwc1-20000_CSC_57_0001"}],"safeDps":"0","recommendServiceSwitch":"1"})
```

**Comment by iNOmoNey** [comment]
> 已经不行了，简单的写了个代码测试下，已经在程序后端做了验证。
> 
> ```js
> jQuery17209914492524519483_1609161816793({"customerNo":"6061011577","isSuccess":"N","addCartErrorList":[{"itemNo":"0","cmmdtyCode":"000000011001203841","cmmdtyName":"","shopCode":"30000757","errorCode":"051","errorMessage":"该商品只能通过立即购买进行下单","errorIgeTag":"0","backErrorCode":"MC570001","uomErrorCode":"ccf-gwc1-20000_CSC_57_0001"}],"safeDps":"0","recommendServiceSwitch":"1"})
> ```

对。 我用fd修改别的可以加购物车的商品的包发回去也不行

**Comment by huanghyw** [comment]
> > 已经不行了，简单的写了个代码测试下，已经在程序后端做了验证。
> > ```js
> > jQuery17209914492524519483_1609161816793({"customerNo":"6061011577","isSuccess":"N","addCartErrorList":[{"itemNo":"0","cmmdtyCode":"000000011001203841","cmmdtyName":"","shopCode":"30000757","errorCode":"051","errorMessage":"该商品只能通过立即购买进行下单","errorIgeTag":"0","backErrorCode":"MC570001","uomErrorCode":"ccf-gwc1-20000_CSC_57_0001"}],"safeDps":"0","recommendServiceSwitch":"1"})
> > ```
> 
> 对。 我用fd修改别的可以加购物车的商品的包发回去也不行

只要后端做了校验，这条路看来就堵死了

**Comment by y500** [comment]
> > 已经不行了，简单的写了个代码测试下，已经在程序后端做了验证。
> > ```js
> > jQuery17209914492524519483_1609161816793({"customerNo":"6061011577","isSuccess":"N","addCartErrorList":[{"itemNo":"0","cmmdtyCode":"000000011001203841","cmmdtyName":"","shopCode":"30000757","errorCode":"051","errorMessage":"该商品只能通过立即购买进行下单","errorIgeTag":"0","backErrorCode":"MC570001","uomErrorCode":"ccf-gwc1-20000_CSC_57_0001"}],"safeDps":"0","recommendServiceSwitch":"1"})
> > ```
> 
> 对。 我用fd修改别的可以加购物车的商品的包发回去也不行

fd是啥

**Comment by iNOmoNey** [comment]
> > > 已经不行了，简单的写了个代码测试下，已经在程序后端做了验证。
> > > ```js
> > > jQuery17209914492524519483_1609161816793({"customerNo":"6061011577","isSuccess":"N","addCartErrorList":[{"itemNo":"0","cmmdtyCode":"000000011001203841","cmmdtyName":"","shopCode":"30000757","errorCode":"051","errorMessage":"该商品只能通过立即购买进行下单","errorIgeTag":"0","backErrorCode":"MC570001","uomErrorCode":"ccf-gwc1-20000_CSC_57_0001"}],"safeDps":"0","recommendServiceSwitch":"1"})
> > > ```
> > 
> > 
> > 对。 我用fd修改别的可以加购物车的商品的包发回去也不行
> 
> fd是啥

fiddler
