### ISSUE TITLE
抢成功了不自动停止的吗？

### ISSUE THREAD

**Issue by Lasx** [huanghyw/jd_seckill#122]
问个问题，抢购成功了为啥不停止。。我以为没抢上，结果上手机一看有了。回头这边还跑着呢。

**Comment by huanghyw** [comment]
恭喜恭喜，手动听一下吧，目前成功了是不会停的。

**Comment by Lasx** [comment]
原来抢口罩是可以自动停的。看看哪里出了问题吧。我抢2瓶够用了。

**Comment by huanghyw** [comment]
现在是多进程，没有做进程同步，所以现在不能停。
我的做法是开抢三分钟后去京东看一眼，有没有待付款订单就行。

**Comment by tttxx** [comment]
@Lasx 请问下你的小白信用多少？

**Comment by Lasx** [comment]
> @Lasx 请问下你的小白信用多少？

 那个不重要

**Comment by Git-Wilson** [comment]
> > @Lasx 请问下你的小白信用多少？
> 
> 那个不重要

那跟什么有关系啊？我4个账号抢了2周一个都没中。。求指导
