### ISSUE TITLE
请教个问题，二维码扫描只是在第一次成功运行程序的时候出现，后面就不用了。那么cookie估计有效期多久呢？后面需要自动清除cookie文件， 再次扫码吗？谢谢！

### ISSUE THREAD

**Issue by pony000ma** [huanghyw/jd_seckill#124]
请教个问题，二维码扫描只是在第一次成功运行程序的时候出现，后面就不用了。那么cookie估计有效期多久呢？后面需要自动清除cookie文件， 再次扫码吗？谢谢！

**Comment by huanghyw** [comment]
多久失效说不准，如果电脑登录之后程序的Cookie就失效了，有时候也不失效。
有失效检测，到时候会有新的二维码。

**Comment by DLwyp** [comment]
> 多久失效说不准，如果电脑登录之后程序的Cookie就失效了，有时候也不失效。
> 有失效检测，到时候会有新的二维码。

我这边试了几次，有效时间没有超过24小时的

**Comment by pony000ma** [comment]
> 
> 
> > 多久失效说不准，如果电脑登录之后程序的Cookie就失效了，有时候也不失效。
> > 有失效检测，到时候会有新的二维码。
> 
> 我这边试了几次，有效时间没有超过24小时的

是的， 这两天陆续试了试，的确，不会超过24小时。谢谢。
