### ISSUE TITLE
脚本判断时间有问题吧？

### ISSUE THREAD

**Issue by dudumuta** [huanghyw/jd_seckill#125]
INFO: 正在等待到达设定时间:2020-12-22 09:59:59.500000，检测本地时间与京东服务器时间误差为【-137】毫秒
INFO: 时间到达，开始执行……
INFO: 预约成功，已获得抢购资格 / 您已成功预约过了，无需重复预约
INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
INFO: 正在等待到达设定时间:2020-12-22 09:59:59.500000，检测本地时间与京东服务器时间误差为【-137】毫秒
怎么是个12月22日呢？

**Comment by huanghyw** [comment]
时间是自己在配置文件里面设置

**Comment by wangmyde** [comment]
> 时间是自己在配置文件里面设置

你好，如果抢购12月29日的茅台，请问在配置文件里 `buy_time = 2020-12-29 09:59:59.500` 还是`buy_time=10:00:00.100000`?谢谢

**Comment by huanghyw** [comment]
> > 时间是自己在配置文件里面设置
> 
> 你好，如果抢购12月29日的茅台，请问在配置文件里 `buy_time = 2020-12-29 09:59:59.500` 还是`buy_time=2020-12-29 10:00:00.100000`?谢谢

其实都可以，现在有时间同步了，误差很小。
不放心提前0.5秒也没问题。

**Comment by huhewen** [comment]
我理解的这个buy_time 是要在预约成功了以后再设置为抢购时间的，要不然就会导致想预约的时候程序不会去预约，一直等待
