### ISSUE TITLE
你好，问一下你们有没有遇到这种情况，运行程序后，到点不会自动执行，要敲回车后才执行

### ISSUE THREAD

**Issue by Reddy888** [huanghyw/jd_seckill#126]
你好，问一下你们有没有遇到这种情况，运行程序后，到点不会自动执行，要敲回车后才执行。

**Comment by huanghyw** [comment]
提前十分钟运行程序，输入2并敲回车，到时间了会自动执行

**Comment by Reddy888** [comment]
这些都已经提前执行了，但是真正到了我设定的时间点还是不会自动运行，要敲一下回车才运行，我更新了代码才出现这个问题的，之前非扫码登录没有这个问题

**Comment by huanghyw** [comment]
扫码之后关闭图片查看器，焦点落回到终端窗口

**Comment by xiaofsu** [comment]
用的windows会有这种情况，推荐使用windows的 windows shell 来操作。

**Comment by MrQcc** [comment]
是因为你cmd开了快速编辑模式，程序运行的时候你在窗口里面有点击动作程序就会停，右键cmd关掉快速编辑模式就可以了
