### ISSUE TITLE
可以直接用pycharm多开扫码登录吗

### ISSUE THREAD

**Issue by caopulan** [huanghyw/jd_seckill#127]
①请问现在还可以不填fp和eid来扫码登录吗，因为我看readme已经没有这个操作方式了
②多开的话直接在pycharm多开可以吗，因为不知道运行的时候会不会有冲突，还是需要把文件单独拷一份来进行多开
③作者有试过ubuntu能否运行成功吗
谢谢解答~

**Comment by huanghyw** [comment]
1、fp和eid必须填，Cookie不用填，readme有提示
2、拷贝或者clone多份
3、虚拟机里面试过ubuntu，没有问题

**Comment by caopulan** [comment]
> 1、fp和eid必须填，Cookie不用填，readme有提示
> 2、拷贝或者clone多份
> 3、虚拟机里面试过ubuntu，没有问题

填了fp和eid之后是不是就没有扫码登录这个过程了，我填了之后就直接开始等时间了。这样的话换号之后fp和eid没有变化，那只能虚拟机或者docker多开吗

**Comment by huanghyw** [comment]
直接开始可能是之前已经扫码过了

换号之后需要重新获取eid和fp

多开可以复制或clone多份项目单独配置

**Comment by caopulan** [comment]
> 直接开始可能是之前已经扫码过了
> 
> 换号之后需要重新获取eid和fp
> 
> 多开可以复制或clone多份项目单独配置

非常感谢，我自己再试一下
