### ISSUE TITLE
小建议与问题

### ISSUE THREAD

**Issue by KaiShu1** [huanghyw/jd_seckill#130]
1. 今天第一次尝试运行，运行成功，有个小问题，失败日志没问题，但是控制台日志有行数限制，开抢当时的日志信息被后面的顶掉了，因此，**希望有一个额外的日志记录文件。**
2. 是否支持多个账户同时开抢？会有哪些影响？

**Comment by huanghyw** [comment]
1、jd_seckill.log就是日志记录文件
2、复制或clone多份分别配置可以多账户开抢，影响就是可能会触发京东的风控机制，会带来哪些后果目前还不可预测

**Comment by rosemaxox** [comment]
刚尝试运行，显示了2个选项后就不动了，敲1 2都没反应，是正常的么？
程序是不是到快抢购的时间才会继续运行？

**Comment by Git-Wilson** [comment]
> 1、jd_seckill.log就是日志记录文件
> 2、复制或clone多份分别配置可以多账户开抢，影响就是可能会触发京东的风控机制，会带来哪些后果目前还不可预测

请问怎么看有没有被京东风控？
