### ISSUE TITLE
非研发人员不懂就问，首次运行直接提示cookie失效

### ISSUE THREAD

**Issue by SuhaifengEric** [huanghyw/jd_seckill#131]
![image](https://user-images.githubusercontent.com/20188658/103192382-70c38480-4913-11eb-84e7-875fe39d8845.png)
想请问我运行main.py之后就这报错，是怎么回事啊。
不是研发人员，搞了好久把eid和fp搞好了，现在又出现这个问题。

**Comment by huanghyw** [comment]
python什么版本？

**Comment by SuhaifengEric** [comment]
> python什么版本？

3.9的，刚才我多试了几次，现在可以正常运行了，我也是很奇怪

**Comment by huanghyw** [comment]
网络不稳定吗？

**Comment by SuhaifengEric** [comment]
> 网络不稳定吗？

公司的网应该稳定的，而且不是wifi是插的网线。现在每次运行都正常了。就前3次出现那个cookies验证失效的问题。

**Comment by huanghyw** [comment]
OK

**Comment by daybreak-git** [comment]
> 好

大佬，是不是不能在VPS上部署的呀，我在配置信息填好EID和FP后，运行一直提示扫码登录，有点懵了

**Comment by ctr54188** [comment]
> > 好
> 
> 大佬，是不是不能在VPS上部署的呀，我在配置信息填好EID和FP后，运行一直提示扫码登录，有点懵了

我也这问题，debian上弄的，没看到二维码呀

**Comment by huanghyw** [comment]
二维码在项目文件夹下面，有一个png的文件
