### ISSUE TITLE
之前的别的老哥都删了，还有头铁上传的

### ISSUE THREAD

**Issue by Ge3kXm** [huanghyw/jd_seckill#133]
小心老哥

**Comment by huanghyw** [comment]
人肉根本抢不到，最终都让黄牛抢到了。
用了脚本，帮助更多的人能够和黄牛站在同一个起跑线上，剩下的就是运气了。

**Comment by zhankezhong** [comment]
人肉抢了一个月 终于在某三天里抢到了两瓶（就一个号） 被限制了才看到这个脚本

**Comment by dudumuta** [comment]
支持老哥，替天行道

**Comment by qy19920913** [comment]
支持老哥 老哥这个代码改商品id能抢显卡吗。。

**Comment by huanghyw** [comment]
> 支持老哥 老哥这个代码改商品id能抢显卡吗。。

目前不支持

**Comment by Mxiansheng** [comment]
> 人肉根本抢不到，最终都让黄牛抢到了。
> 用了脚本，帮助更多的人能够和黄牛站在同一个起跑线上，剩下的就是运气了。

大佬    问下你项目下的那个京东抢购助手，目前可以用不，比如抢购手机
