### ISSUE TITLE
为啥实际看到预约成功，但是在自己的商品中看不到预约呢

### ISSUE THREAD

**Issue by ybjecho** [huanghyw/jd_seckill#134]

**Comment by NBchitu** [comment]
Make sure your JD app is up to date.

**Comment by jianweizou** [comment]
没有填eid = ""  fp = ""，输入1开始预约，最后显示INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，但手机上查看预约信息里面没有。

**Comment by huanghyw** [comment]
预约时间不对

eid和fp必须要填写

**Comment by ybjecho** [comment]
> 预约时间不对
> 
> eid和fp必须要填写

这个预约时间填的不应该是今天预约明天的么，我填今天的任意时间都回复我预约成功，但是商品预约中看不到，这个时间比如我预约明天的应该设置成啥呢，里面config.ini中只有一个购买时间，再没有看到其他设置时间的地方

**Comment by dazhi1011** [comment]
@ybjecho buy_time不要改，具体逻辑可以看下代码

**Comment by wuhongbing** [comment]
预约直接在手机上操作不可以？
