### ISSUE TITLE
默认就是选了两瓶抢购吗

### ISSUE THREAD

**Issue by BrilliantJ** [huanghyw/jd_seckill#136]

**Comment by huanghyw** [comment]
是的，不支持配置，可以在代码中修改

**Comment by ZRT-1998** [comment]
是哪一块代码呢？瓶数

**Comment by DwadeWoW** [comment]
> 是的，不支持配置，可以在代码中修改

大佬，是不是只会抢两瓶？ 不会抢一瓶对吧？

**Comment by DwadeWoW** [comment]
> 是的，不支持配置，可以在代码中修改

如果三十天内抢过一瓶，那不是得配置一瓶才行？

**Comment by wujunchuan** [comment]
@ZRT-1998 

https://github.com/huanghyw/jd_seckill/blob/06294f3db2137ae265e94ea09222150c3c939de0/jd_spider_requests.py#L274

**Comment by Alan-yk** [comment]
两瓶难度会大一点吗
