### ISSUE TITLE
所有库的安装了，执行还是说找不到库，各位大佬帮忙看看啊

### ISSUE THREAD

**Issue by microcisco** [huanghyw/jd_seckill#137]
![image](https://user-images.githubusercontent.com/9547228/103201991-3dd9ba80-492c-11eb-98a0-baa24b36b160.png)

**Comment by tanbinlove** [comment]
试试`python main.py`

**Comment by szliugx** [comment]
看看pip3 和 Python3版本路径是不是一致的，pip3 -V 检查一下

**Comment by Lamb-Yang** [comment]
遇到同样的问题了，也是发现是py的版本问题，默认用了py2，但是pip是3的版本，导致库的路径不一致。

**Comment by microcisco** [comment]
ok

**Comment by canglonghaojiao** [comment]
我的原来也是没有显示没有requests，折腾了半天成了这个ModuleNotFoundError: No module named 'lxml'，小白很烦啊

**Comment by canglonghaojiao** [comment]
> 遇到同样的问题了，也是发现是py的版本问题，默认用了py2，但是pip是3的版本，导致库的路径不一致。

怎么解决的？删除py2？

**Comment by happystudy666** [comment]
pip install
