### ISSUE TITLE
ssl问题？

### ISSUE THREAD

**Issue by pppcx** [huanghyw/jd_seckill#138]
requests.exceptions.SSLError: HTTPSConnectionPool(host='a.jd.com', port=443): Max retries exceeded with url: //ajax/queryServerData.html (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))

**Comment by huanghyw** [comment]
python 什么版本

**Comment by pppcx** [comment]
最新的3.91

**Comment by pppcx** [comment]
> python 什么版本



最新的3.91

**Comment by huanghyw** [comment]
之前有个人也这个问题，多试了几次就好了

**Comment by pppcx** [comment]
> 之前有个人也这个问题，多试了几次就好了

好的 我试试
