### ISSUE TITLE
抢购链接获取失败，稍后自动重试

### ISSUE THREAD

**Issue by Storm4542** [huanghyw/jd_seckill#139]
请教下这是什么错误呢

**Comment by huanghyw** [comment]
还没到抢购时间，获取不到抢购链接

**Comment by syouko** [comment]
> 还没到抢购时间，获取不到抢购链接

原来是快到时间了才运行选项2吗。以为开着命令，到时见自动就开始抢了

**Comment by m809311563** [comment]
> > 还没到抢购时间，获取不到抢购链接
> 
> 原来是快到时间了才运行选项2吗。以为开着命令，到时见自动就开始抢了

提前打开，到了设定时间会开抢的

**Comment by syouko** [comment]
> > > 还没到抢购时间，获取不到抢购链接
> > 
> > 
> > 原来是快到时间了才运行选项2吗。以为开着命令，到时见自动就开始抢了
> 
> 提前打开，到了设定时间会开抢的

看了下代码知道了，默认时间是一个比较早的时间才导致打开之后就自动开始抢了。

也就是每次运行前需要先改到当日时间

**Comment by ctr54188** [comment]
> > > > 还没到抢购时间，获取不到抢购链接
> > > 
> > > 
> > > 原来是快到时间了才运行选项2吗。以为开着命令，到时见自动就开始抢了
> > 
> > 
> > 提前打开，到了设定时间会开抢的
> 
> 看了下代码知道了，默认时间是一个比较早的时间才导致打开之后就自动开始抢了。
> 
> 也就是每次运行前需要先改到当日时间

请问要怎么改呀，本来打算这么挂着的 哎  一直刷新链接失败

**Comment by luboyan-hub** [comment]
> > > > > 还没到抢购时间，获取不到抢购链接
> > > > 
> > > > 
> > > > 原来是快到时间了才运行选项2吗。以为开着命令，到时见自动就开始抢了
> > > 
> > > 
> > > 提前打开，到了设定时间会开抢的
> > 
> > 
> > 看了下代码知道了，默认时间是一个比较早的时间才导致打开之后就自动开始抢了。
> > 也就是每次运行前需要先改到当日时间
> 
> 请问要怎么改呀，本来打算这么挂着的 哎 一直刷新链接失败
遇到一样的问题，是购物的时间去更新下就行了，“config.ini”-“buy_time”
<a href="https://sm.ms/image/piYbFCwtZ6EugPA" target="_blank"><img src="https://i.loli.net/2020/12/29/piYbFCwtZ6EugPA.png" ></a>
