### ISSUE TITLE
获取eid和fp报错有详细教程吗？ 控制台提示VM1352:5 Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by taylor618** [huanghyw/jd_seckill#14]
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = getTakId();
var riskControl = $('#riskControl').val();
console.log(eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl});

VM1352:5 Uncaught SyntaxError: missing ) after argument list

**Comment by huanghyw** [comment]
参考原作者的issue https://github.com/zhou-xiaojun/jd_mask/issues/22

**Comment by taylor618** [comment]
已解决

**Comment by sanmaoallen** [comment]
> 解决

请问怎么解决的，求教程
