### ISSUE TITLE
提示SyntaxError

### ISSUE THREAD

**Issue by ideryang** [huanghyw/jd_seckill#141]
SyntaxError: Non-ASCII character '\xe5' in file main.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by huanghyw** [comment]
配置文件截图贴出来看看

**Comment by sunnysxr** [comment]
我也是同样的问题

**Comment by sunnysxr** [comment]
解决了，在main.py文件顶部添加一行     # -*- coding: utf-8 -*-

**Comment by jiafeijiang** [comment]
> # -_- coding: utf-8 -_-

![image](https://user-images.githubusercontent.com/23660022/103255760-8db89000-49c5-11eb-959d-bf567df43993.png)

 这么加不行啊
