### ISSUE TITLE
流程顺序的疑问

### ISSUE THREAD

**Issue by cnriddle** [huanghyw/jd_seckill#144]
流程是：
先pc登录抓eid，pf，填完config，
运行main.py后，
又弹出扫码登录？
不知道操作错没。

**Comment by huanghyw** [comment]
没错，以后就只需要扫码不需要再更新eid和fp了

**Comment by cnriddle** [comment]
不知道main.py执行后的扫码可坚持多久呢？是每次执行就扫一次码，还是扫一次就行？
