### ISSUE TITLE
请问二维码扫描登录后，校验失败 应该怎么解决

### ISSUE THREAD

**Issue by llxl** [huanghyw/jd_seckill#145]
exception.SKException: 二维码信息校验失败

**Comment by llxl** [comment]
系统是 macOs 10.15.6 
Python 3.7.2

**Comment by zjl775210697** [comment]
哥们我也遇到这个问题了,你看看是不是开着vpn啊,我关了就行了

**Comment by daybreak-git** [comment]
你们是只配置eid 和fp就可以吗，我将这两个参数填写后，运行脚本一直提示扫码登录，搞不懂

**Comment by fengjian1585** [comment]
弹出一个二维码，扫描也找不到东西呀

**Comment by JauYang** [comment]
亲测终端不要设置vpn代理就可以了

**Comment by fengjian1585** [comment]
您好:&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;没有使用vpn呀,&nbsp;本地虚拟机配置的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午9:50
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"冯建"<627459560@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] 请问二维码扫描登录后，校验失败 应该怎么解决 (#145)





 
亲测终端不要设置vpn代理就可以了
