### ISSUE TITLE
关于配置 config.ini 中的 buy_time

### ISSUE THREAD

**Issue by ilaipi** [huanghyw/jd_seckill#146]
这个配置有什么关系吗？

日志中有：

```
正在等待到达设定时间:2020-12-22 09:59:59.500000，检测本地时间与京东服务器时间误差为【-197】毫秒
```

**Comment by Lasx** [comment]
默认即可

**Comment by tlee1987** [comment]
不能使用默认的，要根据你抢的时间段改成抢购的时间

**Comment by syouko** [comment]
> 不能使用默认的，要根据你抢的时间段改成抢购的时间

可以默认，差不多到点了开始执行就行，一直抢

**Comment by huanghyw** [comment]
这里设置为商品的抢购时间，时间达到后会自动进行抢购。

不建议使用默认值，如果使用默认值，程序一启动就会不断地去刷抢购流程，但是这时候又获取不到抢购链接，没必要。最重要的是还可能会因为频繁调用导致京东封ip，造成真正抢购无法进行。

**Comment by ilaipi** [comment]
这个时间是不是不配置日期，只配置 时分秒，日期直接使用当天比较好？

**Comment by 91chen1** [comment]
> 这个时间是不是不配置日期，只配置时分秒，日期直接使用当天比较好？

我一般改的是日期，后面时分秒不改

**Comment by ilaipi** [comment]
> > 这个时间是不是不配置日期，只配置时分秒，日期直接使用当天比较好？
> 
> 
> 
> 我一般改的是日期，后面时分秒不改

每天要改一次吗？还是改一次后面启动之后就一直运行了？
