### ISSUE TITLE
eid和fp的时效以及多开

### ISSUE THREAD

**Issue by caopulan** [huanghyw/jd_seckill#147]
eid和fp时效大概有多长呢，比如晚上提前运行，早上需要重新填吗

多开的话一个号chrome登录，获取fp和eid，退出，另一个号登录，重复操作，获取的fp和eid是同样的，两个号都用同一个fp和eid可以抢购吗。还是说需要保持浏览器运行，不能退出账户呢

**Comment by Memorainer** [comment]
个人测试，发现两个值的更新频率是比较低的但是，如果更换浏览器，他们则有很大可能会发生变化，建议是每天抢购之前重新登录检查一下。

具体测试情况：
27日首次登陆浏览器A，得值A'，
28日再次登陆浏览器A，得值B'，
抢购结果，90008,90016，未抢到！

29日三次登陆浏览器B，得值A'，迷惑！
抢购结果，90016，未抢到！

@huanghyw

**Comment by caopulan** [comment]
我也补充下观察的结果，我觉得可能和账号无关，仅和浏览器有关，作为jd后台判断是否是正当手段下单的途径

电脑A登录账号1，电脑B登录账户1，分别获取fpeid1和fpeid2，两个值不一样并且在电脑A和电脑B同时登陆分别刷新后值不变（同时登陆浏览器不会被顶号）
电脑A退出账号1，登陆账号2，获取到的fpeid和账号1的fpeid完全一致

我猜测fp+eid是仅与浏览器和某随机值有关，与账号无关。京东服务器通过这两个值来判断请求是否是从合法的终端发出的。

**Comment by caopulan** [comment]
另外今天也是大量90016，未抢到
