### ISSUE TITLE
运行脚本一直提示扫码登录

### ISSUE THREAD

**Issue by daybreak-git** [huanghyw/jd_seckill#148]
在VPS上部署了，也按求填写了EID和FP，但是运行一直提示报错，懵了
2020-12-28 22:35:58,201 - 7197-MainThread - /root/jd_seckill/jd_spider_requests.py[line:308] - INFO: reserve 需登陆后调用，开始扫码登陆
2020-12-28 22:35:59,603 - 7197-MainThread - /root/jd_seckill/jd_spider_requests.py[line:177] - INFO: 二维码获取成功，请打开京东APP扫描
2020-12-28 22:35:59,708 - 7197-MainThread - /root/jd_seckill/jd_spider_requests.py[line:205] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码

**Comment by li-xunhuan** [comment]
vps部署，打不开二维码，你得自己下载那个二维码的图片打开扫码或者改代码，在控制台把二维码打印出来

**Comment by daybreak-git** [comment]
> vps部署，打不开二维码，你得自己下载那个二维码的图片打开扫码或改码，在控制台把二维码打印出来

我下载下来你扫码登录，接着报这个错误
2020-12-28 22:58:34,467 - 8018-MainThread - /root/jd_seckill/jd_spider_requests.py[line:208] - INFO: 已完成手机客户端确认
2020-12-28 22:58:34,632 - 8018-MainThread - /root/jd_seckill/jd_spider_requests.py[line:231] - INFO: {'returnCode': 80}
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    jd_seckill.reserve()
  File "/root/jd_seckill/jd_spider_requests.py", line 309, in new_func
    self.login_by_qrcode()
  File "/root/jd_seckill/jd_spider_requests.py", line 293, in login_by_qrcode
    self.qrlogin.login_by_qrcode()
  File "/root/jd_seckill/jd_spider_requests.py", line 258, in login_by_qrcode
    raise SKException('二维码信息校验失败')
exception.SKException: 二维码信息校验失败

**Comment by li-xunhuan** [comment]
> > vps部署，打不开二维码，你得自己下载那个二维码的图片打开扫码或改码，在控制台把二维码打印出来
> 
> 
> 
> 我下载下来你扫码登录，接着报这个错误
> 
> 2020-12-28 22:58:34,467 - 8018-MainThread - /root/jd_seckill/jd_spider_requests.py[line:208] - INFO: 已完成手机客户端确认
> 
> 2020-12-28 22:58:34,632 - 8018-MainThread - /root/jd_seckill/jd_spider_requests.py[line:231] - INFO: {'returnCode': 80}
> 
> Traceback (most recent call last):
> 
>   File "main.py", line 26, in <module>
> 
>     jd_seckill.reserve()
> 
>   File "/root/jd_seckill/jd_spider_requests.py", line 309, in new_func
> 
>     self.login_by_qrcode()
> 
>   File "/root/jd_seckill/jd_spider_requests.py", line 293, in login_by_qrcode
> 
>     self.qrlogin.login_by_qrcode()
> 
>   File "/root/jd_seckill/jd_spider_requests.py", line 258, in login_by_qrcode
> 
>     raise SKException('二维码信息校验失败')
> 
> exception.SKException: 二维码信息校验失败
> 
> 

重新获取一下二维码啊

**Comment by daybreak-git** [comment]
> > > vps部署，打不开二维码，你得自己下载那个二维码的图片打开扫码或改码，在控制台把二维码打印出来
> > 
> > 
> > 我下载下来你扫码登录，随后报这个错误
> > 2020-12-28 22：58：34,467-8018-MainThread-/root/jd_seckill/jd_spider_requests.py[line:208]-信息：已完成手机客户端确认
> > 2020-12-28 22：58：34,632-8018-MainThread-/root/jd_seckill/jd_spider_requests.py[line:231]-信息：{'returnCode'：80}
> > 追溯（最近一次通话）：
> > 在第26行的文件“ main.py”中 
> > ```
> > jd_seckill.reserve()
> > ```
> > 
> > 
> > 在new_func中的文件“ /root/jd_seckill/jd_spider_requests.py”第309行
> > ```
> > self.login_by_qrcode()
> > ```
> > 
> > 
> > 文件“ /root/jd_seckill/jd_spider_requests.py”，第293行，位于login_by_qrcode中
> > ```
> > self.qrlogin.login_by_qrcode()
> > ```
> > 
> > 
> > 在login_by_qrcode中的文件“ /root/jd_seckill/jd_spider_requests.py”，第258行
> > ```
> > raise SKException('二维码信息校验失败')
> > ```
> > 
> > 
> > SKException：二维码信息校验失败
> 
> 重新获取一下二维码啊

奔溃啊，重新运行算是重新获取二维码吧，一样的错误

**Comment by fengjian1585** [comment]
弹出的二维码，APP扫描，什么都没有，这个二维码怎么换新的，有步骤吗

**Comment by lammonx** [comment]
> vps部署，打不开二维码，你得自己下载那个二维码的图片打开扫码或者改代码，在控制台把二维码打印出来

哥，这个下载的应该怎么改代码，没写过py

**Comment by huanghyw** [comment]
> 弹出的二维码，APP扫描，什么都没有，这个二维码怎么换新的，有步骤吗

注意图片查看器背景必须是白色

**Comment by lammonx** [comment]
> > > > vps部署，打不开二维码，你得自己下载那个二维码的图片打开扫码或改码，在控制台把二维码打印出来
> > > 
> > > 
> > > 我下载下来你扫码登录，随后报这个错误
> > > 2020-12-28 22：58：34,467-8018-MainThread-/root/jd_seckill/jd_spider_requests.py[line:208]-信息：已完成手机客户端确认
> > > 2020-12-28 22：58：34,632-8018-MainThread-/root/jd_seckill/jd_spider_requests.py[line:231]-信息：{'returnCode'：80}
> > > 追溯（最近一次通话）：
> > > 在第26行的文件“ main.py”中
> > > ```
> > > jd_seckill.reserve()
> > > ```
> > > 
> > > 
> > > 在new_func中的文件“ /root/jd_seckill/jd_spider_requests.py”第309行
> > > ```
> > > self.login_by_qrcode()
> > > ```
> > > 
> > > 
> > > 文件“ /root/jd_seckill/jd_spider_requests.py”，第293行，位于login_by_qrcode中
> > > ```
> > > self.qrlogin.login_by_qrcode()
> > > ```
> > > 
> > > 
> > > 在login_by_qrcode中的文件“ /root/jd_seckill/jd_spider_requests.py”，第258行
> > > ```
> > > raise SKException('二维码信息校验失败')
> > > ```
> > > 
> > > 
> > > SKException：二维码信息校验失败
> > 
> > 
> > 重新获取一下二维码啊
> 
> 奔溃啊，重新运行算是重新获取二维码吧，一样的错误

你把生成的那个png删了试试
