### ISSUE TITLE
获取抢购链接时，访问https://itemko.jd.com/itemShowBtn返回体仲url字段为空

### ISSUE THREAD

**Issue by 354621693** [huanghyw/jd_seckill#15]
获取抢购链接时，访问https://itemko.jd.com/itemShowBtn，返回的json一直是{'type': '3', 'state': '11', 'url': ''}，请问是不是配置参数填错的问题？

**Comment by huanghyw** [comment]
确认配置没问题，那这个就是获取链接失败了

**Comment by 354621693** [comment]
> 确认配置没问题，那这个就是获取链接失败了

好的谢谢，还想问一下，针对酒和显卡的抢购，平时没有这两项的抢购活动的时候，有哪些商品可以用来测试？求推荐测试商品和测试方法，谢谢！

**Comment by huanghyw** [comment]
我目前主要用来抢茅台，没有抢购的时候不太好测试。而且需要注意，现在还不支持购物车方式的抢购，等以后有空了准备优化下这块。

**Comment by 354621693** [comment]
好的明白了，我在京东上直接搜抢购中的一些普通商品（商品页显示正在抢购，比如k30至尊），用脚本抢购，不管加没加购物车，都是获取链接失败：{'type': '3', 'state': '11', 'url': ''}。而k30至尊在手机app上抢的时候，也是直接点击抢购进入订单确认页的（不是购物车方式）。
