### ISSUE TITLE
可以多个服务器用一个账号抢吗

### ISSUE THREAD

**Issue by liuguangruge** [huanghyw/jd_seckill#156]
比如本地一个，服务器上一个，都抢同一个账号

**Comment by tanbinlove** [comment]
服务器上不能扫码登录获取cookie，修改代码把扫码获取cookie的那一步改成从config.ini里获取cookie的话，感觉是可以的

**Comment by WuChengqian520** [comment]
刚刚用了香港的服务器，把图片传回本地扫码的，京东给我发了个警告，反正可以运行，能不能抢到就不好说了

**Comment by huanghyw** [comment]
没必要单账号多服务器，现在就是单账号多进程去抢购的，搞多了会触发风控
