### ISSUE TITLE
不能Ctrl C 优雅退出，需要pr吗

### ISSUE THREAD

**Issue by Zachary-Zhao** [huanghyw/jd_seckill#157]

**Comment by Zachary-Zhao** [comment]
有没有交流群呢

**Comment by huanghyw** [comment]
Ctrl C没问题吧，我一直都是这么退出的

**Comment by hewang1016729378** [comment]
> Ctrl C没问题吧，我一直都是这么退出的

Mac上面，Ctrl C 没用 我直接关闭终端的，

**Comment by Zachary-Zhao** [comment]
我在 win10  python37  不行

**Comment by liangie** [comment]
> > Ctrl C没问题吧，我一直都是这么退出的
> 
> Mac上面，Ctrl C 没用 我直接关闭终端的，

啊？Ctrl+C 退出没问题啊，难道我是假MBP吗  哈哈哈
