### ISSUE TITLE
cookies_String 和cookie一样吗？

### ISSUE THREAD

**Issue by rcfan1** [huanghyw/jd_seckill#16]
我获取到的cookie和说明文档里的示例cookies_String顺序不太一样，输入以后老是提示cookie错误，但是放在其他软件里就可以使用的啊。
我想咨询一下，这两个值是不是不一样啊，为什么我的老是失败啊
谢谢

**Comment by huanghyw** [comment]
cookies_String这一项就是填写cookie

**Comment by rcfan1** [comment]
> cookies_String这一项就是填写cookie

我填的就是谷歌浏览器里查询到的cookie啊，今天试了好多次，老是显示登陆失败，  昨天还能用的，不清楚是怎么回事啊

**Comment by huanghyw** [comment]
我之前遇到过cookie的问题是一开始使用的火狐浏览器，直接复制粘贴出来的里面以后未转义字符，最终导致失败。
