### ISSUE TITLE
大佬，你的github已经很多人被发到微信公众号了。 

### ISSUE THREAD

**Issue by XFW-10086** [huanghyw/jd_seckill#160]

**Comment by huanghyw** [comment]
来，提供下线索，重点关注下收费的那种

**Comment by Mikasa33** [comment]
https://mp.weixin.qq.com/s/JXc5tiQy09FDoFrAOOVKTw
https://mp.weixin.qq.com/s/csPCQdWLuG7s_5Ew3XDIhw

**Comment by huanghyw** [comment]
> https://mp.weixin.qq.com/s/JXc5tiQy09FDoFrAOOVKTw
> https://mp.weixin.qq.com/s/csPCQdWLuG7s_5Ew3XDIhw

这个看了下，没问题。不存在转载，更不存在收费。

**Comment by huanghyw** [comment]
大家还有其他线索欢迎提供。

特别是那种需要收费才能看的转载或者代码下载的文章。

我的目标很简单，尽量让每个人都能参与到公平抢茅台的竞争中。
