### ISSUE TITLE
抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】？请问有人遇到一样的报错吗？

### ISSUE THREAD

**Issue by ObbaLX** [huanghyw/jd_seckill#164]

**Comment by long9922** [comment]
老哥能教教我怎么开启吗,我是搞前端的,不会派森

**Comment by TnWah** [comment]
+1

**Comment by huanghyw** [comment]
接口返回信息异常，不用关注，程序会自动重试

**Comment by ObbaLX** [comment]
程序从一开始就在报这个错，真的不用干预吗

**Comment by Vincentjianpeng** [comment]
我开了三个程序对应三个账号，一个正常返回抢购失败的信息，另外两个都是返回“接口返回:【'addressList'】”，不知道什么回事

**Comment by TnWah** [comment]
@huanghyw 请问抢购时返回addresslist是正常情况么？

**Comment by huanghyw** [comment]
是否正常主要通过日志里面有没有出现“很遗憾”来判断，如果没有检查下配置文件是否正确
还有，在抢购的过程中不要登录PC端查看订单。确实是否抢购成功可以用手机端确认。
