### ISSUE TITLE
抢到了，感谢老大！！！卖了来打赏~^~

### ISSUE THREAD

**Issue by jianweizou** [huanghyw/jd_seckill#165]

**Comment by huanghyw** [comment]
恭喜恭喜

**Comment by Visbin** [comment]
能发布一下日志和茅台截图么

**Comment by swansun95** [comment]
你多少分钟抢到的呀？我一直跑都抢不到

**Comment by tttxx** [comment]
报下小白信用

**Comment by jianweizou** [comment]
我也不晓得什么时候抢到的，因为我第一次是用python打开，发现python界面出现‘未响应’，后来我直接双击 main.py，后来发现log出现乱码，看不了了。
![image](https://user-images.githubusercontent.com/42789178/103254067-d9b40680-49be-11eb-96c8-a5909c3f060e.png)

**Comment by jianweizou** [comment]
昨天在京东金融上查看了下 小白信用是100.5

**Comment by Oays** [comment]
你们是开了plus抢的还是普通用户抢的哈？

**Comment by pwy5150** [comment]
> 你们是开了plus抢的还是普通用户抢的哈？

只能plus

**Comment by applebest** [comment]
![image](https://user-images.githubusercontent.com/16376401/103325560-3b3fa800-4a87-11eb-9342-49fecced2e6d.png)
选2吗?

**Comment by Yeziyou666** [comment]
有联系方式吗 我怎么安装不了requirements.txt==
