### ISSUE TITLE
感谢作者，今天第一次抢，抢到2瓶

### ISSUE THREAD

**Issue by urionz** [huanghyw/jd_seckill#166]
感谢作者，今天第一次抢，抢到2瓶，小白信用98

**Comment by huanghyw** [comment]
厉害了

**Comment by TeslaLyon** [comment]
您抢的哪一款？

**Comment by medic5767** [comment]
不信

**Comment by long9922** [comment]
老哥能教教我怎么打开程序吗,我是搞前端的,不会派森

**Comment by swansun95** [comment]
一次怎么抢到2瓶？？

**Comment by medic5767** [comment]
信用100.3，次次抢90016

**Comment by qy19920913** [comment]
京东不是一次只能一瓶？

**Comment by swansun95** [comment]
> 京东不是一次只能一瓶？

对啊，一次只能1瓶，咋抢的两瓶？不解

**Comment by Danbro007** [comment]
哈哈哈 我也抢到了 太感谢了

**Comment by tttxx** [comment]
@swansun95 @qy19920913 这个脚本就是设置了下单两瓶

**Comment by ctr54188** [comment]
一直90016

**Comment by Oays** [comment]
你们是plus还是普通用户呀？

**Comment by jingjxd** [comment]
代码里配置了2瓶，所以只要抢中就是2瓶

**Comment by wubinsheng2017** [comment]
win10到点了不自动输出日志，过了很久手动ctrl+c之后才输出，日志里也没见提交订单的请求。
就是这样吗？
2020-12-29 09:46:43,922 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2020-12-29 09:46:43,923 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
2020-12-29 09:46:43,985 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2020-12-29 09:46:43,986 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
2020-12-29 10:00:00,896 - 24252-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
2020-12-29 10:00:00,896 - 9756-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
2020-12-29 10:00:01,073 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
2020-12-29 10:00:01,075 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
2020-12-29 10:00:01,267 - 25956-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
2020-12-29 10:03:01,037 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
2020-12-29 10:03:01,038 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...

**Comment by cuiguohua** [comment]
> win10到点了不自动输出日志，过了很久手动ctrl+c之后才输出，日志里也没见提交订单的请求。
> 就是这样吗？
> 2020-12-29 09:46:43,922 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2020-12-29 09:46:43,923 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> 2020-12-29 09:46:43,985 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2020-12-29 09:46:43,986 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> 2020-12-29 10:00:00,896 - 24252-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> 2020-12-29 10:00:00,896 - 9756-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> 2020-12-29 10:00:01,073 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> 2020-12-29 10:00:01,075 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> 2020-12-29 10:00:01,267 - 25956-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> 2020-12-29 10:03:01,037 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> 2020-12-29 10:03:01,038 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...

用的是系统自带的cmd或者powershell吗？是的话在属性里关掉 快速插入

**Comment by wubinsheng2017** [comment]
> > win10到点了不自动输出日志，过了很久手动ctrl+c之后才输出，日志里也没见提交订单的请求。
> > 就是这样吗？
> > 2020-12-29 09:46:43,922 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> > 2020-12-29 09:46:43,923 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> > 2020-12-29 09:46:43,985 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> > 2020-12-29 09:46:43,986 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> > 2020-12-29 10:00:00,896 - 24252-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:00,896 - 9756-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:01,073 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:01,075 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:01,267 - 25956-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,037 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,038 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> 
> 用的是系统自带的cmd或者powershell吗？是的话在属性里关掉 快速插入
是“快速编辑模式”，“插入模式”都取消选中吗？

**Comment by Vincentjianpeng** [comment]
配置发一下？

**Comment by cuiguohua** [comment]
> > win10到点了不自动输出日志，过了很久手动ctrl+c之后才输出，日志里也没见提交订单的请求。
> > 就是这样吗？
> > 2020-12-29 09:46:43,922 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> > 2020-12-29 09:46:43,923 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> > 2020-12-29 09:46:43,985 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> > 2020-12-29 09:46:43,986 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> > 2020-12-29 10:00:00,896 - 24252-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:00,896 - 9756-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:01,073 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:01,075 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:00:01,267 - 25956-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,037 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,038 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> 
> 用的是系统自带的cmd或者powershell吗？是的话在属性里关掉 快速插入
> 是“快速编辑模式”，“插入模式”都取消选中吗？

貌似是“快速编辑模式”，或者都取消选中也无妨。win的cmd的这个feature（bug）很烦人

**Comment by wubinsheng2017** [comment]
> > > win10到点了不自动输出日志，过了很久手动ctrl+c之后才输出，日志里也没见提交订单的请求。
> > > 就是这样吗？
> > > 2020-12-29 09:46:43,922 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> > > 2020-12-29 09:46:43,923 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> > > 2020-12-29 09:46:43,985 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:461] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> > > 2020-12-29 09:46:43,986 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-29 09:59:59.500000，检测本地时间与京东服务器时间误差为【1355】毫秒
> > > 2020-12-29 10:00:00,896 - 24252-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > > 2020-12-29 10:00:00,896 - 9756-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > > 2020-12-29 10:00:01,073 - 47292-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > > 2020-12-29 10:00:01,075 - 18504-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > > 2020-12-29 10:00:01,267 - 25956-MainThread - E:\07_openSource\jd_seckill\timer.py[line:50] - INFO: 时间到达，开始执行……
> > > 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > > 2020-12-29 10:03:01,016 - 24252-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > > 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > > 2020-12-29 10:03:01,025 - 47292-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > > 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > > 2020-12-29 10:03:01,028 - 18504-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > > 2020-12-29 10:03:01,037 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > > 2020-12-29 10:03:01,038 - 9756-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > > 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:452] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=f2e4500c778831b0e5c4aecefe334a55&from=pc
> > > 2020-12-29 10:03:01,045 - 25956-MainThread - E:\07_openSource\jd_seckill\jd_spider_requests.py[line:464] - INFO: 访问商品的抢购连接...
> > 
> > 
> > 用的是系统自带的cmd或者powershell吗？是的话在属性里关掉 快速插入
> > 是“快速编辑模式”，“插入模式”都取消选中吗？
> 
> 貌似是“快速编辑模式”，或者都取消选中也无妨。win的cmd的这个feature（bug）很烦人

多谢多谢，去掉试了下，好了
另外再请教下，提示说我们jd的时间相差1s+，是不是就是说应该把config中的开始时间往前调1s左右？

**Comment by Danbro007** [comment]
> 你们是plus还是普通用户呀？

plus用户，昨天特地充的会员

**Comment by Oays** [comment]
> > 你们是plus还是普通用户呀？
> 
> plus用户，昨天特地充的会员

好的

**Comment by Mingwang1986** [comment]
> 感谢作者，今天第一次抢，抢到2瓶，小白信用98

这个必须先运行1，后运行2，才可以抢到吗？
