### ISSUE TITLE
没报错，返回null

### ISSUE THREAD

**Issue by Arvin-007** [huanghyw/jd_seckill#167]
![z2251915198950_7e81196bbfeba8fbaa511356526e8750](https://user-images.githubusercontent.com/61957092/103253968-01eb3780-49b6-11eb-8d1e-cfc115d804fc.jpg)

**Comment by huanghyw** [comment]
京东接口返回异常，不用关心，程序会自动重试的

**Comment by testuser495** [comment]
跟你一样的问题，就是不知道具体是什么原因导致的报错。。。

**Comment by testuser495** [comment]
> 京东接口返回异常，不用关心，程序会自动重试的

大佬，报了null，然后就开始90016，意思就是这次失败，等待下次呗？

**Comment by huanghyw** [comment]
报null可以忽略，会自动重试的
三分钟还没抢到基本上就不用等了，第二天继续
