### ISSUE TITLE
谢谢作者，29号，两瓶入手

### ISSUE THREAD

**Issue by jin522** [huanghyw/jd_seckill#168]

**Comment by smallhorsegg** [comment]
你是一直开着程序抢吗？

**Comment by Oays** [comment]
你是plus还是普通用户呀？

**Comment by long9922** [comment]
老哥我是前端不会派森,能教我怎么开启程序吗

**Comment by qy19920913** [comment]
京东是默认两瓶？？不是一个号一瓶吗？

**Comment by qy19920913** [comment]
> 老哥我是前端不会派森,能教我怎么开启程序吗

你去问问程序员老哥啊   有没有mac系统 直接装个homebrew 装个pip 就完事了 环境就搭载好了

**Comment by long9922** [comment]
只有window系统,没有mac




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午10:22
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"一棵小葱"<2421945671@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] 谢谢作者，29号，两瓶入手 (#168)





  
老哥我是前端不会派森,能教我怎么开启程序吗
  
你去问问程序员老哥啊   有没有mac系统 直接装个homebrew 装个pip 就完事了 环境就搭载好了

**Comment by taohuzefu** [comment]
n GitHub, or unsubscribe.



> 老哥我是前端不会派森,能教我怎么开启程序吗

装个python就ok

**Comment by long9922** [comment]
老哥加个微信可以吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午10:29
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"一棵小葱"<2421945671@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] 谢谢作者，29号，两瓶入手 (#168)





 
n GitHub, or unsubscribe.
  
老哥我是前端不会派森,能教我怎么开启程序吗
  
装个python就ok

**Comment by sunzhongguan** [comment]
那必须得请作者喝个咖啡了  -_-
