### ISSUE TITLE
抢到的大佬们可以发个config.ini参考下吗，记得删掉自己的支付密码

### ISSUE THREAD

**Issue by DLwyp** [huanghyw/jd_seckill#172]
抢了四次了，颗粒无收

**Comment by KenZP** [comment]
小白信用100+  表示也没抢到

**Comment by tttxx** [comment]
一次90008都没，就是抢不到～～

**Comment by Arvin-007** [comment]
需要填写支付密码吗？

**Comment by kojayhuang** [comment]
一般不用填写支付密码吧

**Comment by jingjxd** [comment]
![image](https://user-images.githubusercontent.com/11516842/103254442-454aa380-49c0-11eb-92e7-ec375e0c3381.png)

**Comment by mendylove** [comment]
ini用什么打开的，用记事本打开乱码，怎么改编码都没用。

**Comment by jingjxd** [comment]
sublime text

**Comment by creazy412** [comment]
@jingjxd 也没什么特殊的配置项哦，加油继续战斗
