### ISSUE TITLE
抢到的朋友能否说说大概程序运行多久就能抢到？

### ISSUE THREAD

**Issue by swansun95** [huanghyw/jd_seckill#174]
RT 谢谢

**Comment by medic5767** [comment]
与运行多久有啥关系。。

**Comment by swansun95** [comment]
我的意思是，如果前5分钟都抢光了，那么我也就不用在盯着屏幕看上十几二十分钟了

**Comment by LockiJiang** [comment]
> 
> 
> 我的意思是，如果前5分钟都抢光了，那么我也就不用在盯着屏幕看上十几二十分钟了

我觉得一般两分钟就不用继续了，不排除后面有人取消订单的还能捡漏，但是几率特别小

**Comment by swansun95** [comment]
> > 我的意思是，如果前5分钟都抢光了，那么我也就不用在盯着屏幕看上十几二十分钟了
> 
> 我觉得一般两分钟就不用继续了，不排除后面有人取消订单的还能捡漏，但是几率特别小

感觉好难抢，哈哈

**Comment by Auto-SK** [comment]
2020-12-29 10:00:02,681 - 11788-MainThread - F:\Caches\jd_seckill\jd_spider_requests.py[line:610] - INFO: 抢购成功

**Comment by LockiJiang** [comment]
> 
> 
> 2020-12-29 10:00:02,681 - 11788-MainThread - F:\Caches\jd_seckill\jd_spider_requests.py[line:610] - INFO: 抢购成功

拉仇恨

**Comment by swansun95** [comment]
唉，我500M光纤都不好使啊，是不是要上阿里云服务器才行？

**Comment by sea0302** [comment]
> > 2020-12-29 10:00:02,681 - 11788-MainThread - F:\Caches\jd_seckill\jd_spider_requests.py[line:610] - INFO: 抢购成功
> 
> 拉仇恨

你们小白信用多少呢?

**Comment by Auto-SK** [comment]
> > > 2020-12-29 10:00:02,681 - 11788-MainThread - F:\Caches\jd_seckill\jd_spider_requests.py[line:610] - INFO: 抢购成功
> > 
> > 
> > 拉仇恨
> 
> 你们小白信用多少呢?

95.3

**Comment by sunzhongguan** [comment]
如果之前没抢过的话，第一次应该成功率很大。

**Comment by swansun95** [comment]
> > > > 2020-12-29 10:00:02,681 - 11788-MainThread - F:\Caches\jd_seckill\jd_spider_requests.py[line:610] - INFO: 抢购成功
> > > 
> > > 
> > > 拉仇恨
> > 
> > 
> > 你们小白信用多少呢?
> 
> 95.3

我99.x都没抢到，而且之前也没抢过茅台。。。😭

**Comment by LockiJiang** [comment]
> 
> 
> 唉，我500M光纤都不好使啊，是不是要上阿里云服务器才行？

我就是在阿里云跑的

**Comment by Lstoryc** [comment]
1s(2次)/5s(1次)内，已经成功搞了6瓶 感谢大佬

**Comment by taoqiyang** [comment]
@Lstoryc 兄弟你是多久抢到6瓶的 不是30天内最多抢两瓶
