### ISSUE TITLE
main.py出错

### ISSUE THREAD

**Issue by pjoce** [huanghyw/jd_seckill#176]
main.py运行后报错，窗口只停留0.3s左右，试了好几次大概是的信息是 
找不到模块  ，这个是缺少了什么呢

**Comment by barry-gq** [comment]
贴报错信息啊。。。

**Comment by pjoce** [comment]
运行main.py 就闪退  0.3s左右贴不出报错信息

**Comment by BrilliantJ** [comment]
肯定是双击打开的main.py。。。

**Comment by barry-gq** [comment]
> 肯定是双击打开的main.py。。。

。。。。
