### ISSUE TITLE
关于user-ag问题

### ISSUE THREAD

**Issue by me1799** [huanghyw/jd_seckill#179]
jd app 提示需要5.5.6以上版本，你这的请求头  是pc端，他是否有做user-ag认证？因为有用过其他seckill软件，会提示非手机端，所以有这方面疑虑，怎么做到正常请求，有人帮忙解答下嘛

**Comment by Joenothing-lst** [comment]
这个程序就是使用的pc端网站进行抢购的

**Comment by huanghyw** [comment]
暂时没遇到过认证失败的问题

**Comment by yf9212** [comment]
> 这个程序就是使用的pc端网站进行抢购的

我昨天用网站抢，发现按钮都出不来，有今天跑这个程序成功的吗
