### ISSUE TITLE
纯小白安装第三方库问题

### ISSUE THREAD

**Issue by a81798045** [huanghyw/jd_seckill#180]
![QQ截图20201229104103](https://user-images.githubusercontent.com/20829539/103254955-71672400-49c2-11eb-94ea-6f2727a45092.png)
折腾了半天还是不会，有人告知下吗~

**Comment by barry-gq** [comment]
昨天我踩到了这个坑，我升级到py3.7解决了

**Comment by mendylove** [comment]
可能py版本问题，用3.9死活不行，后来用3.87没问题

**Comment by tesNeg** [comment]
大概率是楼上说的版本问题，3.9版本不适配 certifi==2020.4.5.1，建议3.8

另外SSLEOFError，pip源换成国内的可以缓解
例如清华源
`pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple   `

**Comment by a81798045** [comment]
> 可能py版本问题，用3.9死活不行，后来用3.87没问题

搞定了，从3.8.7降到了 3.7.9成功了
