### ISSUE TITLE
多线程进行抢购将线程拉高是否有效？

### ISSUE THREAD

**Issue by unclebuff** [huanghyw/jd_seckill#182]

**Comment by unclebuff** [comment]
`@check_login
    def seckill_by_proc_pool(self, work_count=5):
        """
        多进程进行抢购
        work_count：进程数量
        """
        with ProcessPoolExecutor(work_count) as pool:
            for i in range(work_count):
                pool.submit(self.seckill)`

**Comment by sunzhongguan** [comment]
猜测：多线程可能会提高成功率，如果你不怕被封号的话可以试试，然后回来告诉我们峰值  嘿嘿

**Comment by 6923403** [comment]
这是进程池 5个就行   开多了其实没多少作用

**Comment by Joenothing-lst** [comment]
程序里已经开了一个包含5个进程的进程池，多进程的作用应该是让时间粒度变小。  
无论是多进程还是多线程，理论上都会提高成功率。

**Comment by Lstoryc** [comment]
当然多了风控系统是否触发？ 然后成了黑户。。。嘿嘿
