### ISSUE TITLE
成功与否主要看号，软件就是辅助

### ISSUE THREAD

**Issue by openxbmc** [huanghyw/jd_seckill#185]
RT,茅台也好，Mate40P也好，我用插件在天猫都买到过，但京东就是不行，我是Plus，信用分100+，而我用同事的Plus号，信用分95的，一下就抢到了，所以，完全看号的好吧

**Comment by billy-huang** [comment]
大佬，求個天貓的插件

**Comment by DLwyp** [comment]
哈哈哈，不如交流下天猫的脚本

**Comment by ilaipi** [comment]
佛系点，每天手动去点几乎做不到，用软件就是持之以恒，抢到最好，抢不到等第二天。

**Comment by iNOmoNey** [comment]
> 佛系点，每天手动去点几乎做不到，用软件就是持之以恒，抢到最好，抢不到等第二天。

改点代码放云服务器上每天定时定点抢。
每天10:05看下手机哈哈哈
一切随缘~
