### ISSUE TITLE
关于抢购流程的问题

### ISSUE THREAD

**Issue by Joenothing-lst** [huanghyw/jd_seckill#188]
**生成提交抢购订单所需的请求体**方法(`_get_seckill_order_data()`)
在每次调用**提交抢购订单**方法(`submit_seckill_order()`)之后都会被调用并初始化抢购订单，是否可以放在**提交抢购订单**方法之前，仅调用至成功一次？这样每次**提交抢购订单**都可以减少一次网络请求。

**Comment by NBchitu** [comment]
I think it will work. Just try it!

**Comment by huanghyw** [comment]
但是这么做不符合真实的使用流程，容易被发现
