### ISSUE TITLE
拉下最新代码，换了图片查看器还是报错“二维码登陆失败”？求大佬来看下，已贴截图

### ISSUE THREAD

**Issue by whherui** [huanghyw/jd_seckill#189]
![image](https://user-images.githubusercontent.com/13448641/103255911-1df6d500-49c6-11eb-8bde-4cbed85ac9df.png)

**Comment by huanghyw** [comment]
手机和电脑都是国内网络吗？

**Comment by whherui** [comment]
> 手机和电脑都是国内网络吗？

都是国内网络，梯子软件关闭后，重启Windows 10，只不过电脑用的是手机热点

**Comment by huanghyw** [comment]
看着没问题，扫码应该也是通过了，要不您更新一下代码再试试

**Comment by klakekent** [comment]
我也是相同的问题

**Comment by lvjisong** [comment]
登录京东网页端==》点击头像==》进入我的京东==》账户设置==》安全设置==》登录保护取消就可以了，我也是遇到这个问题，刚解决。

**Comment by lvjisong** [comment]
> 我也是相同的问题

登录京东网页端==》点击头像==》进入我的京东==》账户设置==》安全设置==》登录保护取消就可以了，我也是遇到这个问题，刚解决。

**Comment by whherui** [comment]
> 登录京东网页端==》点击头像==》进入我的京东==》账户设置==》安全设置==》登录保护取消就可以了，我也是遇到这个问题，刚解决。

谢谢大佬，已解决。。。还有，我个人在这里补充一点，给遇到同样问题的筒子们参考参考，电脑端也不要开启代理转发服务器（哪怕关了梯子），否则还是会报这个错。。
