### ISSUE TITLE
你好 mac运行main.py似乎有问题

### ISSUE THREAD

**Issue by allan1334** [huanghyw/jd_seckill#191]
if __name__ == '__main__':
    a = """

       oooo oooooooooo.            .oooooo..o                     oooo         o8o  oooo  oooo  
       `888 `888'   `Y8b          d8P'    `Y8                     `888         `"'  `888  `888  
        888  888      888         Y88bo.       .ooooo.   .ooooo.   888  oooo  oooo   888   888  
        888  888      888          `"Y8888o.  d88' `88b d88' `"Y8  888 .8P'   `888   888   888  
        888  888      888 8888888      `"Y88b 888ooo888 888        888888.     888   888   888  
        888  888     d88'         oo     .d8P 888    .o 888   .o8  888 `88b.   888   888   888  
    .o. 88P o888bood8P'           8""88888P'  `Y8bod8P' `Y8bod8P' o888o o888o o888o o888o o888o 
    `Y888P                                                                                                                                                  
                                               
功能列表：                                                                                
 1.预约商品
 2.秒杀抢购商品
    """
    print(a)

    jd_seckill = JdSeckill()
    choice_function = input('请选择:')
    if choice_function == '1':
        jd_seckill.reserve()
    elif choice_function == '2':
        jd_seckill.seckill_by_proc_pool()
    else:
        print('没有此功能')
        sys.exit(1)

**Comment by huanghyw** [comment]
什么问题？

**Comment by allan1334** [comment]
> 什么问题？

"""
print(a)

jd_seckill = JdSeckill()
choice_function = input('请选择:')
if choice_function == '1':
    jd_seckill.reserve()
elif choice_function == '2':
    jd_seckill.seckill_by_proc_pool()
else:
    print('没有此功能')
    sys.exit(1)

**Comment by allan1334** [comment]
就是会多这一串。输1、2回车没反应，win下正常 没底下那串代码。输1预约也正常。

**Comment by allan1334** [comment]
也不会弹登陆的二维码

**Comment by Jasoncoool** [comment]
人才不会是双击打开的吧？win上是可执行程序，双击就能运行，mac上可不是双击就能运行的

**Comment by allan1334** [comment]
> 人才不会是双击打开的吧？win上是可执行程序，双击就能运行，mac上可不是双击就能运行的

哈哈 不好意思 我就是双击打开的=- =。那我先去查查mac怎么运行py，感谢！
