### ISSUE TITLE
抢购链接获取失败,稍后自动重试是怎么回事

### ISSUE THREAD

**Issue by long9922** [huanghyw/jd_seckill#192]
是不是没到抢购时间

**Comment by long9922** [comment]
求解答

**Comment by niupuyue** [comment]
同问

**Comment by TimorYang** [comment]
buy_time = 2020-12-22 09:59:59.500
改这个参数

**Comment by hewang1016729378** [comment]
> buy_time = 2020-12-22 09:59:59.500
> 改这个参数

文章里面不是说不需要改时间，会自动获取时间嘛

**Comment by cat-drink-coffe** [comment]
> > buy_time = 2020-12-22 09:59:59.500
> > 改这个参数
> 
> 文章里面不是说不需要改时间，会自动获取时间嘛

同问

**Comment by TimorYang** [comment]
> > > buy_time = 2020-12-22 09:59:59.500
> > > 改这个参数
> > 
> > 
> > 文章里面不是说不需要改时间，会自动获取时间嘛
> 
> 同问

这个是设置抢购开始的时间，文章里说的是同步京东服务器时间，不搭嘎
