### ISSUE TITLE
请教那些url请求的格式，是怎样在京东的界面上发现的

### ISSUE THREAD

**Issue by stonellearning** [huanghyw/jd_seckill#193]
你好，大佬，请问下那些url请求的格式，是怎样在京东的界面上发现的？怎样才能发现post的请求，有相关的api文档分享吗？

**Comment by huanghyw** [comment]
标题尽量能简短的说明问题

**Comment by huanghyw** [comment]
比如用Chrome浏览器，右键页面，点击检查
![image](https://user-images.githubusercontent.com/7189743/103256727-3caa9b00-49c9-11eb-953d-34ecd6ccd790.png)
右边就会出现工具，可以用来分析网页
![image](https://user-images.githubusercontent.com/7189743/103256738-46340300-49c9-11eb-97f3-c05ed2748b36.png)

**Comment by huanghyw** [comment]
具体用法可以网上学习下

**Comment by stonellearning** [comment]
https://yushou.jd.com/youshouinfo.action  这个url是怎么发现的？

**Comment by stonellearning** [comment]
![image](https://user-images.githubusercontent.com/76717577/103256851-a5921300-49c9-11eb-8b03-34d360372a61.png)

https://marathon.jd.com/seckillnew/orderService/pc/submitOrder.action 这个post的格式是如何找到的呢？

**Comment by Jasoncoool** [comment]
> ![image](https://user-images.githubusercontent.com/76717577/103256851-a5921300-49c9-11eb-8b03-34d360372a61.png)
> 
> https://marathon.jd.com/seckillnew/orderService/pc/submitOrder.action 这个post的格式是如何找到的呢？

抓包，拦截请求链接啊

**Comment by iNOmoNey** [comment]
我更想知道那些直达订单页的**BP链接**怎么发现的

**Comment by cncqw** [comment]
> 我更想知道那些直达订单页的**BP链接**怎么发现的

浏览器 开发者工具 - Network 基本可以看到网页所有请求，也可以用Fiddler抓包

**Comment by iNOmoNey** [comment]
> > 我更想知道那些直达订单页的**BP链接**怎么发现的
> 
> 浏览器 开发者工具 - Network 基本可以看到网页所有请求，也可以用Fiddler抓包

抓包下单应该没有出现那个接口。
这是淘宝的bp链接：https://h5.m.taobao.com/cart/order.html?itemId=20739895092&item_num_id=20739895092&_input_charset=utf-8&buyNow=true&v=0&skuId=4227830352490&quantity=1

你可以试试看能不能找到这个接口

**Comment by cncqw** [comment]
> > > 我更想知道那些直达订单页的**BP链接**怎么发现的
> > 
> > 
> > 浏览器 开发者工具 - Network 基本可以看到网页所有请求，也可以用Fiddler抓包
> 
> 抓包下单应该没有出现那个接口。
> 这是淘宝的bp链接：https://h5.m.taobao.com/cart/order.html?itemId=20739895092&item_num_id=20739895092&_input_charset=utf-8&buyNow=true&v=0&skuId=4227830352490&quantity=1
> 
> 你可以试试看能不能找到这个接口

这个项目是针对京东吧，你发个淘宝链接是啥意思我没搞懂。

**Comment by mendylove** [comment]
天猫的茅台不能用BP链接吧

**Comment by iNOmoNey** [comment]
> > > > 我更想知道那些直达订单页的**BP链接**怎么发现的
> > > 
> > > 
> > > 浏览器 开发者工具 - Network 基本可以看到网页所有请求，也可以用Fiddler抓包
> > 
> > 
> > 抓包下单应该没有出现那个接口。
> > 这是淘宝的bp链接：https://h5.m.taobao.com/cart/order.html?itemId=20739895092&item_num_id=20739895092&_input_charset=utf-8&buyNow=true&v=0&skuId=4227830352490&quantity=1
> > 你可以试试看能不能找到这个接口
> 
> 这个项目是针对京东吧，你发个淘宝链接是啥意思我没搞懂。
> 
> 网上有很多这种BP链接生成器，看了一下链接都有固定的格式，自己拼接就可以了。

就是想知道这个bp链接从哪抓出来的呢

**Comment by iNOmoNey** [comment]
> 天猫的茅台不能用BP链接吧

不清楚。随便举了个例子
