### ISSUE TITLE
mac python3 执行出错

### ISSUE THREAD

**Issue by jiafeijiang** [huanghyw/jd_seckill#194]
jiafeijiang@JiafeideMacBook-Pro jd_seckill % python3 main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_spider_requests import JdSeckill
  File "/Users/jiafeijiang/workspace/jd_seckill/jd_spider_requests.py", line 10, in <module>
    from lxml import etree
ImportError: dlopen(/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/lxml/etree.so, 2): Symbol not found: _PyBaseString_Type
  Referenced from: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/lxml/etree.so
  Expected in: flat namespace
 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/lxml/etree.so

**Comment by shanlilaide** [comment]
老哥，你没安装第三方

**Comment by Jasoncoool** [comment]
现在github门槛这么低了么？都不看readme的么？

**Comment by jiafeijiang** [comment]
> 老哥，你没安装第三方

安装了。。。

**Comment by jiafeijiang** [comment]
> 现在github门槛这么低了么？都不看readme的么？

python3.7

**Comment by shanlilaide** [comment]
> 现在github门槛这么低了么？都不看readme的么？

茅台一路寻过来的，命令行都找了很久……

**Comment by jiafeijiang** [comment]
> > 现在github门槛这么低了么？都不看readme的么？
> 
> 茅台一路寻过来的，命令行都找了很久……

都是环境问题  解决好几个了 最后还是不行

**Comment by Jasoncoool** [comment]
> > > 现在github门槛这么低了么？都不看readme的么？
> > 
> > 
> > 茅台一路寻过来的，命令行都找了很久……
> 
> 都是环境问题 解决好几个了 最后还是不行

看一下当前环境的python版本，是不是要用pip3安装，Python3 执行
