### ISSUE TITLE
微信交流群

### ISSUE THREAD

**Issue by boogummm** [huanghyw/jd_seckill#196]

**Comment by xiaotianwl** [comment]
看不到图片！

**Comment by direct1986** [comment]
看不到图片

**Comment by Li-shulin** [comment]
看不到图片

**Comment by 1510963833** [comment]
can not see anything

**Comment by szliugx** [comment]
host加上下面这段，就能看见图片了：

 
151.101.184.133    assets-cdn.github.com
151.101.184.133    raw.githubusercontent.com
151.101.184.133    gist.githubusercontent.com
151.101.184.133    cloud.githubusercontent.com
151.101.184.133    camo.githubusercontent.com
151.101.184.133    avatars0.githubusercontent.com
151.101.184.133    avatars1.githubusercontent.com
151.101.184.133    avatars2.githubusercontent.com
151.101.184.133    avatars3.githubusercontent.com
151.101.184.133    avatars4.githubusercontent.com
151.101.184.133    avatars5.githubusercontent.com
151.101.184.133    avatars6.githubusercontent.com
151.101.184.133    avatars7.githubusercontent.com
151.101.184.133    avatars8.githubusercontent.com
151.101.184.133    user-images.githubusercontent.com

**Comment by byHelloBaby** [comment]
> 151.101.184.133 assets-cdn.github.com

没看懂

**Comment by a81798045** [comment]
来晚了。已经满200，扫码进不去了

**Comment by 495806109** [comment]
建议赶紧删了

**Comment by sxl47** [comment]
没人再弄个群？

**Comment by 503095972** [comment]
来晚了。已经满200，扫码进不去了

**Comment by sunchao199606** [comment]
> _No description provided._

大佬 看不到二维码 帮忙拉我进去呗微信号15550452616
