### ISSUE TITLE
为了降低项目风险，去除打赏二维码

### ISSUE THREAD

**Issue by huanghyw** [huanghyw/jd_seckill#198]
实在没想到这个项目现在有这么多人使用，这么高的热度，能有今天感激大家点击的每一个小星星。

咨询了法律朋友，此类软件可能会触碰他人利益。即使没有通过售卖盈利，但是打赏的存在也说明了会有少许的获利。为了降低法律风险，为了此项目走的更远让更多人看见，也为了初衷，决定删除打赏二维码。

大家要是有好的想法请多提issues，有好的代码多多pr，每人都是贡献者，共同做大做强。

再次，祝大家顺利抢到茅台，每天开心。

**Comment by liziqing** [comment]
感谢你！加油！

**Comment by huanghyw** [comment]
> 感谢你！加油！

加油加油

**Comment by pwy5150** [comment]
谢谢大佬~

**Comment by MrTangke** [comment]
原来作者在线啊。突然刷出评论了

**Comment by MrTangke** [comment]
加油

**Comment by jingjxd** [comment]
大佬格局之大，吾等望尘莫及啊

**Comment by medic5767** [comment]
挺

**Comment by baisechundu** [comment]
感谢作者，抢购成功之时，一定打赏。

**Comment by zhankezhong** [comment]
感觉已经被黄牛利用  要失控了  担心作者收律师函啊 建议作者把仓库删了吧

**Comment by fffaker** [comment]
INFO: 抢购链接获取失败，稍后自
动重试   现在报这个是因为今天抢购链接失效了是吧

**Comment by Lstoryc** [comment]
支持大佬

**Comment by crazy-canux** [comment]
@huanghyw  哪个单位的？ 上班这么闲

**Comment by m809311563** [comment]
大佬加油

**Comment by mianbaoa** [comment]
谢谢！！

**Comment by wupeaking** [comment]
今天眼睁睁的看着ｓｔａｒ从１.9K变成３.1K 　厉害啊！

**Comment by jason1314em** [comment]
谢谢作者给普通老百姓一个抢茅台的机会，知恩图报，删除打赏也是正确的做法

**Comment by baowenqing** [comment]
jd_seckill-master\jd_spider_requests.py[line:456] - INFO: 抢购链接获取失败，稍后自动重试

**Comment by TsingA** [comment]
谢谢大佬，今天才知道这个，手抢了2个月，一直失败，明天看看大佬的script~

**Comment by YaoYufeng** [comment]
身边的朋友很多用这个脚本抢到的，唯一担心的就是当我使用的时候会不会被京东改规则了

**Comment by huaxiaweilian** [comment]
随着热度提升。。。感觉京东要改规则了~

**Comment by canglonghaojiao** [comment]
谢谢大佬

**Comment by Million-Chen** [comment]
感谢 大佬的奉献

**Comment by yliu46** [comment]
> 随着热度提升。。。感觉京东要改规则了~

京东肯定已经知道了，各大抢购群都在传这脚本。

**Comment by mianbaoa** [comment]
谢谢，已经抢到了两瓶。。。

**Comment by fayeharuna** [comment]
谢谢 连续两天抢到了…因为怕触发30天两瓶的规则每次只设置了一瓶。

**Comment by zhengkeqi** [comment]
> > 感谢你！加油！
> 
> 加油加油

你好 我想问下抢购的时候显示 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】这个是正常的么

**Comment by zhengkeqi** [comment]
> 谢谢连续两天抢到了...因为怕触发30天两瓶的规则每次只设置了一瓶。

老哥 能留个联系方式嘛  我的配置方面好像有点问题

**Comment by todayqq** [comment]
感谢大佬，已经抢到

**Comment by wuhuaiqin** [comment]
首战告捷，抢到一瓶，感谢（虽然之前很辛苦的人工抢到了一瓶）

**Comment by cwl12** [comment]
> 谢谢 连续两天抢到了…因为怕触发30天两瓶的规则每次只设置了一瓶。

这样可以绕过规则？

**Comment by qzcyy** [comment]
作者是不是应该投诉一下自媒体OR公共号等传播组织，未经允许私自传播知识产权并盈利，而且即便在传播中获利方并不是作者的情况下，这么广泛的传播会不会对作者带来风险

**Comment by maotai1499** [comment]
> 作者是不是应该投诉一下自媒体OR公共号等传播组织，未经允许私自传播知识产权并盈利，而且即便在传播中获利方并不是作者的情况下，这么广泛的传播会不会对作者带来风险

你真逗，别个不传播，这个项目能火起来吗？你这格局真小~

**Comment by zhengkeqi** [comment]
大佬 文件怎么没了
