### ISSUE TITLE
mac 报错

### ISSUE THREAD

**Issue by chenyucheng** [huanghyw/jd_seckill#199]
File "main.py", line 3, in <module>
    from jd_spider_requests import JdSeckill
  File "/Users/xxx/Desktop/work/GSwork/project/jd_seckill/jd_spider_requests.py", line 106
    def __init__(self, spider_session: SpiderSession):

**Comment by huanghyw** [comment]
日志太少了

**Comment by chenyucheng** [comment]
![image](https://user-images.githubusercontent.com/7437264/103263424-d468b300-49e2-11eb-842d-da917efd1fef.png)

**Comment by huanghyw** [comment]
检查下配置文件是否正确

**Comment by chenyucheng** [comment]
通了，弹出了二维码，没用 Pip3 安装 没用 Python3 执行，改成这个 就ok了。

**Comment by mkgrow** [comment]
怎么解决的
