### ISSUE TITLE
服务器纯命令行端可以用吗？怎么弹出二维码？怎么设置eid和fp？

### ISSUE THREAD

**Issue by BrilliantJ** [huanghyw/jd_seckill#202]

**Comment by earth2moon4mars** [comment]
https://github.com/zhou-xiaojun/jd_mask/issues/22  这个链接

**Comment by huanghyw** [comment]
纯命令行不能弹出，需要远程查看下项目目录下的png文件

**Comment by liuxiaoquan** [comment]
centos配置一个桌面就行了

**Comment by Trig-Von** [comment]
使用mobaXterm，打开X11-Forwarding，在服务器yum install xauth。就可以弹出图片了
