### ISSUE TITLE
建议删除项目具体看图

### ISSUE THREAD

**Issue by Lasx** [huanghyw/jd_seckill#207]
![1](https://user-images.githubusercontent.com/5484221/103267875-82795a80-49ed-11eb-9485-4045615e13fa.jpg)

**Comment by zhankezhong** [comment]
借个楼 也建议作者删除仓库  这不是作者是否靠项目盈利的问题了

**Comment by Li-shulin** [comment]
为了安全，建议删掉

**Comment by fastv2ray** [comment]
为了安全，建议删掉

**Comment by teemotry** [comment]
图片看不了，打不开

**Comment by m809311563** [comment]
@huanghyw 同建议删掉，只不过上图写的这文说的好像之前没有一样，只不过现在是作者重新改了贴出来，一时间star上来了

**Comment by lllrrr2** [comment]
说实话，黄牛全是用脚本抢的。在github上开源的东东，真没必要删除，是不是有黄牛们看到作者动了他们的奶酪啊。

**Comment by jason1314em** [comment]
> 说实话，黄牛全是用脚本抢的。在github上开源的东东，真没必要删除，是不是有黄牛们看到作者动了他们的奶酪啊。

我感觉也是，开源的东西如果不造成风险没必要删除，京东天猫抢茅台的都是脚本，手动点根本没希望，用脚本就看运气了，而且一个ID每个月最多2瓶，个人使用不存在任何问题，反而是黄牛他们因此可能会减少利润，因为投放的总量有限

**Comment by lllrrr2** [comment]
我很欣赏作者写的这句话“愿大家与黄牛站在同一个起跑线，公平的参与这场抢茅大赛。”这就是国人最缺的胸怀。

**Comment by m809311563** [comment]
> 说实话，黄牛全是用脚本抢的。在github上开源的东东，真没必要删除，是不是有黄牛们看到作者动了他们的奶酪啊。

自然是这个原因。不过没有胸怀的人大有人在

**Comment by Lasx** [comment]
> > 说实话，黄牛全是用脚本抢的。在github上开源的东东，真没必要删除，是不是有黄牛们看到作者动了他们的奶酪啊。
> 
> 自然是这个原因。不过没有胸怀的人大有人在

为了作者好。你们不懂。
