### ISSUE TITLE
get_seckill_url 获取抢购商品连接的时候 url 为空

### ISSUE THREAD

**Issue by caihuoche** [huanghyw/jd_seckill#21]
![image](https://user-images.githubusercontent.com/24805030/102499722-7c62b000-40b6-11eb-8d94-43ca06f00bb5.png)

**Comment by huanghyw** [comment]
为空即为获取失败，会自动重试

**Comment by caihuoche** [comment]
> 为空即为获取失败，会自动重试

但是重试很多次都这样,是因为我没到时间点吗

**Comment by huanghyw** [comment]
时间点是一个因素，还需要确认抢购的商品需要先放入购物车再下单目前是不支持的。

**Comment by huanghyw** [comment]
参考：https://github.com/huanghyw/jd_seckill/issues/27
