### ISSUE TITLE
各位大佬，我有几句话要说，且抢且珍惜

### ISSUE THREAD

**Issue by csxyy1980** [huanghyw/jd_seckill#216]
首先感谢huanghyw，让我有机会拥有一个国民理财产品，太谢谢了
第二、我仅仅是一名计算机爱好者，README里讲的这么清楚，我百度加瞎琢磨就搞定了，
如果你连这么傻瓜的程序都搞不定，问些小白问题，就不要来污染大家issue了
第三，大家心不要太狠，我就准备抢2瓶自用，
楼主当初开发目的应该也是想让大家对抗下黄牛，而不是用来牟利
最后，且行且珍惜，够用就行了。不要等到京东改变了规则，
封了这个程序或者规则，到时候大家都玩不了

**Comment by huanghyw** [comment]
> 首先感谢huanghyw，让我有机会拥有一个国民理财产品，太谢谢了
> 第二、我仅仅是一名计算机爱好者，README里讲的这么清楚，我百度加瞎琢磨就搞定了，
> 如果你连这么傻瓜的程序都搞不定，问些小白问题，就不要来污染大家issue了
> 第三，大家心不要太狠，我就准备抢2瓶自用，
> 楼主当初开发目的应该也是想让大家对抗下黄牛，而不是用来牟利
> 最后，且行且珍惜，够用就行了。不要等到京东改变了规则，
> 封了这个程序或者规则，到时候大家都玩不了

太对了，为你点赞！

**Comment by chen-Aaron** [comment]
3070显卡请求出战

**Comment by simplelife7** [comment]
大家抱平常心，这个脚本只是让大家快人一步，并不能百分百抢到，背后还有京东的风控。只要积分较高，坚持一段时间还是能抢到的

**Comment by huanghyw** [comment]
> 3070显卡请求出战

玩扫雷卡不卡？

**Comment by kaikee-Snow** [comment]
good

**Comment by cwl12** [comment]
看到issue上一些白痴问题真的觉得不配用这个程序。真的是看到有利可图就一窝蜂的跑来，结果连怎么用都不知道就开始提issue当伸手党

**Comment by hhc87** [comment]
> 看到issue上一些白痴问题真的觉得不配用这个程序。真的是看到有利可图就一窝蜂的跑来，结果连怎么用都不知道就开始提issue当伸手党

赞同，刚刚看到说配置时间不对的，readme不好好看，配置文件不好好改，真的就是伸手党冲进来，服气。

**Comment by qy19920913** [comment]
确实。写的很明白了 如果看不懂的话 真的就别用了
