### ISSUE TITLE
小白信用103.5的路过，请问时间这里该如何设置

### ISSUE THREAD

**Issue by openxbmc** [huanghyw/jd_seckill#22]
你好，我试了3天，无论是茅台还是显卡，啥都没有抢到，我感觉是时间这里不对，请问作者设置的抢购时间为多少？

**Comment by huanghyw** [comment]
比如10点整的茅台抢购，我的时间一般都这么设置：09:59:59.500
除了时间设置，时间同步也需要注意，最好是每小时自动同步一下互联网时间

**Comment by openxbmc** [comment]
谢谢， 我每次只是更改时间中的小时，后面的分秒就按照config中的保留不动
buy_time = 2020-06-09 10:00:00.150 如果再算上网络延时的50ms，我说咋每次都抢不上~

**Comment by openxbmc** [comment]
Hello
还有一个问题配置中DEFAULT_USER_AGENT = ""
实际上通过F12查看为Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

我需要更改么

**Comment by huanghyw** [comment]
最好改一下，和获取cookie的那个浏览器一致
