### ISSUE TITLE
fp 和 eid 是干什么的？

### ISSUE THREAD

**Issue by xzjby** [huanghyw/jd_seckill#225]
fp 和 eid是记录设备的吗？ 同一个设备不同的帐号试一样的吗？ 那如果我想把程序部署到linux服务器上，怎么获取呢？求指教

**Comment by luyehui** [comment]
fp 好像是设备信息，eid是浏览器指纹

**Comment by DzAvril** [comment]
> fp 和 eid是记录设备的吗？ 同一个设备不同的帐号试一样的吗？ 那如果我想把程序部署到linux服务器上，怎么获取呢？求指教

同问：我现在用的是本地电脑的浏览器fp和eid信息  脚本跑在服务器上 这样有问题吗？
而且我已经让脚本运行了  一直到明天抢购 是否有问题？

**Comment by monthAndEclipse** [comment]
我看多个账号在同一台设备得eid和fp都是一样得，那么同一台设备 可以起多个程序，跑多个账号吗？
