### ISSUE TITLE
除了茅台其他抢购基本上都是加购物车的吧

### ISSUE THREAD

**Issue by wzphood** [huanghyw/jd_seckill#23]
显卡都是获取链接失败，就茅台能走到“抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}”

**Comment by huanghyw** [comment]
是的，目前主要还是用来抢茅台

**Comment by emptiny** [comment]
我抢显卡就是预约成功，已获得抢购资格/ 您已成功预约过了，无需重复预约，一直在刷这个，是不是就没去抢

**Comment by huanghyw** [comment]
> 我抢显卡就是预约成功，已获得抢购资格/ 您已成功预约过了，无需重复预约，一直在刷这个，是不是就没去抢

预约和抢购是两个功能

**Comment by emptiny** [comment]
> > 我抢显卡就是预约成功，已获得抢购资格/ 您已成功预约过了，无需重复预约，一直在刷这个，是不是就没去抢
> 
> 预约和抢购是两个功能

所以预约完之后抢购应该选功能2吗，晕

**Comment by huanghyw** [comment]
是的
还有一点需要注意，目前不支持加购物车抢购

**Comment by emptiny** [comment]
> 是的
> 还有一点需要注意，目前不支持加购物车抢购

好的，谢谢您

**Comment by huanghyw** [comment]
> > 是的
> > 还有一点需要注意，目前不支持加购物车抢购
> 
> 好的，谢谢您

没事，您客气了
