### ISSUE TITLE
采用小白信用应该不是很准确

### ISSUE THREAD

**Issue by bberljw** [huanghyw/jd_seckill#234]
> 京东的风控体系应该和另外一个值有关，是Plus综合分。

- 具体路径应该是我的Plus -> Plus综合积分。里面有几个具体的纬度来评判一个用户是否是合规用户(或者说对商城更有价值)。
低于90分，用户无法开通Plus会员，甚至无法领取优惠券。

- 以前用一些脚本扫京东的优惠券，号已经黑掉了（88分）。但是小白信用分还是很高的。

- 结合一些朋友的抢购，发现只要抢到茅台的，Plus综合分都在105分（扫脸之后107分）的用户。所以作者可以和这个积分做一个比对。

现在每个电商的茅台风控策略都不一样，如果能把这个规则猜出来，收益会更大。（网易、小米、国美、苏宁、家乐福、1919、京东、淘宝、盒马等等）
有个纯抽签的华润的茅台活动也可以参加一下。

**Comment by chenghao111** [comment]
京东马上也抽签预约了。

**Comment by mengshun** [comment]
我的plus综合分 107 今天第一次抢, 就抢到了

**Comment by zhangdanfeng888** [comment]
我的105分，小白信用70多分，天天抢，毛都没抢到，怀疑是因为小白信用分太低

**Comment by mengshun** [comment]
我小白信用 97.5,  钻石, 京享值 26000+

**Comment by gqs4352** [comment]
你中了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 上午10:38
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"43528399"<43528399@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] 采用小白信用应该不是很准确 (#234)





 
我小白信用 97.5,  钻石, 京享值 26000+
