### ISSUE TITLE
第三方库到底要怎么装

### ISSUE THREAD

**Issue by HengPolar** [huanghyw/jd_seckill#237]
先是缺 pip ，装了之后缺vc14.0，然后就各种报错，大家到底怎么装的三方库啊

**Comment by pigZ-27** [comment]
1、建议先安装miniconda,参考，https://docs.conda.io/en/latest/miniconda.html
2、建议采用虚拟环境安装python3X
3、如果有报错，先截图

**Comment by cat-drink-coffe** [comment]
> 先是缺 pip ，装了之后缺vc14.0，然后就各种报错，大家到底怎么装的三方库啊

老哥你装好了没 我是搞不明白这玩意

**Comment by lihouxing-sjtu** [comment]
搞个虚拟机，或是用云服务器在linux环境下弄，很方便的。我就是在自己的云服务器上跑的，虽然还没抢到，哈哈

**Comment by Caicool** [comment]
> 先是缺 pip ，装了之后缺vc14.0，然后就各种报错，大家到底怎么装的三方库啊

缺VC14.0安装就行啊，严格按照大佬给的步骤走就行。

**Comment by a774226108** [comment]
升级pip 然后安装就行了
