### ISSUE TITLE
抢购链接获取失败，稍后自动重试,这个正常吗？

### ISSUE THREAD

**Issue by qiangli524** [huanghyw/jd_seckill#245]
![image](https://user-images.githubusercontent.com/22065508/103323505-109d2180-4a7e-11eb-8534-eb3dee038c9f.png)

**Comment by 18615675682** [comment]
config.ini 中配置一下buy_time的时间

**Comment by zwinds** [comment]
这里参数更改一下buy_time = 2020-12-30 09:59:59.500

**Comment by 18615675682** [comment]
config.ini 中配置一下buy_time的时间

**Comment by JianhuangShu** [comment]
> 这里参数更改一下buy_time = 2020-12-30 09:59:59.500

没毛病，每天都得改时间

**Comment by whale-max** [comment]
改了时间还是提示   2020-12-30 10:00:31,793 - 15280-MainThread - E:\study\project\jd_seckill\jd_spider_requests.py[line:460] - INFO: 抢购链 接获取失败，稍后自动重试

**Comment by JianhuangShu** [comment]
> 改了时间还是提示 2020-12-30 10:00:31,793 - 15280-MainThread - E:\study\project\jd_seckill\jd_spider_requests.py[line:460] - INFO: 抢购链 接获取失败，稍后自动重试

一直是这样吗？那你预约下看看，看能预约成功吗？
