### ISSUE TITLE
验证cookies是否有效时发生异常

### ISSUE THREAD

**Issue by zhqiang-li** [huanghyw/jd_seckill#249]
TypeError: not all arguments converted during string formatting
Call stack:
  File ".\main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "F:\01.codesource\python\jd_seckill\jd_spider_requests.py", line 274, in __init__
    self.qrlogin = QrLogin(self.spider_session)
  File "F:\01.codesource\python\jd_seckill\jd_spider_requests.py", line 120, in __init__
    self.refresh_login_status()
  File "F:\01.codesource\python\jd_seckill\jd_spider_requests.py", line 127, in refresh_login_status
    self.is_login = self._validate_cookies()
  File "F:\01.codesource\python\jd_seckill\jd_spider_requests.py", line 144, in _validate_cookies
    logger.error("验证cookies是否有效发生异常", e)
Message: '验证cookies是否有效发生异常'
Arguments: (SSLError(MaxRetryError("HTTPSConnectionPool(host='order.jd.com', port=443): Max retries exceeded with url: /center/list.action?rid=1609293582149 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))")),)

**Comment by yeurs** [comment]
> TypeError：并非在字符串格式化期间转换了所有参数
> 调用堆栈： jd_seckill = JdSeckill（）中 文件“
> 。\ main.py”，第23行，文件“ F：\ 01.codesource \ python \ jd_seckill \ jd_spider_requests.py”，行274 ，在**初始化** self.qrlogin = QrLogin（self.spider_session） 文件“ F：\ 01.codesource \ python \ jd_seckill \ jd_spider_requests.py”，第120行，在**初始化** self.refresh_login_status（） 文件“ F：\ 01.codesource \ python \ jd_seckill \ jd_spider_requests.py”，第127行，在refresh_login_status self.is_login = self._validate_cookies（） 文件“ F：\ 01.codesource \ python \ jd_seckill \ jd_spider_requests.py”，第144行，在 _validate（cookies记录器中。 “验证Cookie是否有效发生异常”，e）
> 
> ****
> 
> ****
> 
> 
> 
> 
> 
> 消息：“验证cookie是否有效发生异常”
> 参数：（SSLError（MaxRetryError（“ HTTPSConnectionPool（host ='order.jd.com'，port = 443））：URL超过最大重试次数：/center/list.action？rid = 1609293582149（由SSLError（SSLCertVerificationError（1，'[SSL：CERTIFICATE_VERIFY_FAILED]证书验证失败：证书链中的自签名证书（_ssl.c：1108）'）））））））））

大佬在吗联系你
