### ISSUE TITLE
抢到了，特来感谢大佬

### ISSUE THREAD

**Issue by 13330222271** [huanghyw/jd_seckill#252]
没想到一次性成功，直接抢到了2瓶，想打赏，发现已经关闭了😂

**Comment by Kongsea** [comment]
我在Mac上可以扫码登录，Linux上的二维码，客户端一直不识别，不知道为什么...

**Comment by koyuhau** [comment]
羡慕 蹲了几天都没抢到

**Comment by yliu46** [comment]
号好的基本上都能成功啊，唉

**Comment by skenoy** [comment]
> 没想到一次性成功，直接抢到了2瓶，想打赏，发现已经关闭了😂

为什么你这么优秀

**Comment by Mxiansheng** [comment]
2020-12-30 10:00:01,516 - 2228-MainThread - D:\XZ\py37_Test\jd_seckill-master\jd_spider_requests.py[line:578] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

**Comment by PeachUncle** [comment]
我的一直是90016，难受

**Comment by PeachUncle** [comment]
> 2020-12-30 10:00:01,516 - 2228-MainThread - D:\XZ\py37_Test\jd_seckill-master\jd_spider_requests.py[line:578] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

我也是这个信息
![Uploading image.png…]()

**Comment by Mxiansheng** [comment]
我的一直提示这个       怎么这么秀    抢不到呀
2020-12-30 10:00:01,516 - 2228-MainThread - D:\XZ\py37_Test\jd_seckill-master\jd_spider_requests.py[line:578] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

**Comment by SnailDev** [comment]
我的也是

**Comment by 13330222271** [comment]
mac电脑运行的，jd账号小白信用88.9

**Comment by xiaoshiguangl** [comment]
> 2020-12-30 10:00:01,516 - 2228-MainThread - D:\XZ\py37_Test\jd_seckill-master\jd_spider_requests.py[line:578] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

我的也是这样，，怎么解呢，难受

**Comment by zpp0318** [comment]
> 没想到一次性成功，直接抢到了2瓶，想打赏，发现已经关闭了😂

大佬 留个联系方式 请教一下你
