### ISSUE TITLE
今天返回“抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】”

### ISSUE THREAD

**Issue by medic5767** [huanghyw/jd_seckill#256]
昨天还是仅3个90008，全是90016，今天啥情况啊

**Comment by a809918928** [comment]
猜测是不是没有设置默认地址

**Comment by taohuzefu** [comment]
有点坑，就是cookies失效了，白跑一天

**Comment by ihwf** [comment]
> 有点坑，就是cookies失效了，白跑一天

addressList是cookie失效了?

**Comment by taohuzefu** [comment]
> > 有点坑，就是cookies失效了，白跑一天
> 
> addressList是cookie失效了?

你把它删了，再跑，就ok

**Comment by ihwf** [comment]
> > > 有点坑，就是cookies失效了，白跑一天
> > 
> > 
> > addressList是cookie失效了?
> 
> 你把它删了，再跑，就ok

卧槽, 还真有可能是, 今天没有让我扫码登录直接就跑了, 跑的结果全是addressList

**Comment by medic5767** [comment]
应该是没扫码清COOKIE的原因吧？我和楼上一样都是addresslist

**Comment by medic5767** [comment]
> > > > 有点坑，就是cookies失效了，白跑一天
> > > 
> > > 
> > > addressList是cookie失效了?
> > 
> > 
> > 你把它删了，再跑，就ok
> 
> 卧槽, 还真有可能是, 今天没有让我扫码登录直接就跑了, 跑的结果全是addressList

能确认是没扫码的原因吗？

**Comment by ihwf** [comment]
不好确认, 我只是根据我的现象猜的, 因为前两天我开启的时候是有弹出扫码的, 是能正常返回,今天开启的时候没有弹出, 但是所有结果都是addressList, 关掉重跑就叫我扫码了

**Comment by medic5767** [comment]
> 不好确认, 我只是根据我的现象猜的, 因为前两天我开启的时候是有弹出扫码的, 是能正常返回,今天开启的时候没有弹出, 但是所有结果都是addressList, 关掉重跑就叫我扫码了

我把cookie清了，重新APP扫码登陆运行1和2都弹2维码了，这可如何是好？
