### ISSUE TITLE
大佬不考虑做一个扫码登录吗，之前tychxn的扫码登录挺好用的

### ISSUE THREAD

**Issue by getMTbug** [huanghyw/jd_seckill#26]
大佬不考虑做一个扫码登录吗，之前tychxn的扫码登录挺好用的，现在这种登录方式略微繁琐，有时候 Chrome提取的cookies可能是顺序不对，直接整段复制过来无法登录，要手动一项一项复制过来更改才可以登录

**Comment by huanghyw** [comment]
可以，回头搞搞

**Comment by getMTbug** [comment]
嗯。另外大佬有其他的联系方式吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 中午12:16
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"丄"<280943888@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] 大佬不考虑做一个扫码登录吗，之前tychxn的扫码登录挺好用的 (#26)





 
可以，回头搞搞

**Comment by huanghyw** [comment]
主要方式就在github留言吧

**Comment by huanghyw** [comment]
已经在开发这个功能了，等测试没问题后合并到master
https://github.com/huanghyw/jd_seckill/tree/feature-hyw-qrcode_login

**Comment by getMTbug** [comment]
Traceback (most recent call last):
  File "C:\JDBOT\jd_ qrcode_login\main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "C:\JDBOT\jd_ qrcode_login\jd_spider_requests.py", line 34, in __init__
    self._load_cookies()
  File "C:\JDBOT\jd_ qrcode_login\jd_spider_requests.py", line 89, in _load_cookies
    for name in os.listdir('./cookies'):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './cookies'

**Comment by huanghyw** [comment]
没权限吧

**Comment by getMTbug** [comment]
重新拉取一次以后以管理员模式运行CMD也还是一样的错误信息，所需要的库也重新安装了一次。没添加扫码登录之前的可以正常用。

**Comment by huanghyw** [comment]
刚才确实有问题，重新拉一下代码再试试

**Comment by Alyle-L** [comment]
> 大佬不考虑做一个扫码登录吗，之前tychxn的扫码登录挺好用的，现在这种登录方式略微繁琐，有时候 Chrome提取的cookies可能是顺序不对，直接整段复制过来无法登录，要手动一项一项复制过来更改才可以登录

这个跟顺序没关系，因为cookies有几个值是没办法通过console获取的

**Comment by getMTbug** [comment]
> > 大佬不考虑做一个扫码登录吗，之前tychxn的扫码登录挺好用的，现在这种登录方式略微繁琐，有时候Chrome提取的cookie可能是顺序不对，直接整段复制过来无法登录，要手动一项一项复制过来更改才可以登录
> 
> 这个跟顺序没关系，因为cookies有几个值是没办法通过console获取的

可能是吧，但是奇怪的是如果对照好参数 手动一项一项的复制就没问题，整段复制过来就无法登录

**Comment by Alyle-L** [comment]
> > > 大佬不考虑做一个扫码登录吗，之前tychxn的扫码登录挺好用的，现在这种登录方式略微繁琐，有时候Chrome提取的cookie可能是顺序不对，直接整段复制过来无法登录，要手动一项一项复制过来更改才可以登录
> > 
> > 
> > 这个跟顺序没关系，因为cookies有几个值是没办法通过console获取的
> 
> 可能是吧，但是奇怪的是如果对照好参数 手动一项一项的复制就没问题，整段复制过来就无法登录

自己补上那几个值就好了呀，目前也就三个（unick、_pst、thor），其实那段cookies有很多字段值是没用的

**Comment by huanghyw** [comment]
扫码登录已经可以用了
