### ISSUE TITLE
QR Code 识别不出来，无论是选择1，还是选择2，系统都会跳出要扫二维码，而这个二维码京东APP就是识别不了

### ISSUE THREAD

**Issue by daviji001** [huanghyw/jd_seckill#269]

**Comment by zjxckangkang** [comment]
这个二维码图片的背景色是黑色的，我同事的android机也是识别不出来，你可以用iphone识别，然后用草料二维码生成一个二维码让你来扫

**Comment by Nickszy** [comment]
应该是二维码的问题，你把背景换成白色的就行了

**Comment by Caicool** [comment]
识别不了是因为输出的二维码没有白色边框，你用画图打开后，把二维码剪切到白色背景中间，再用APP扫就可以识别了。我也是才知道……

**Comment by daviji001** [comment]
早知道，今天也许就能抢到了。。。。多谢，期待下次

**Comment by Caicool** [comment]
> 早知道，今天也许就能抢到了。。。。多谢，期待下次

哈哈，我也是昨天没弄明白，今天才知道才试了，也没抢到。用脚本也不是100%能抢到的，只是不用拼手速了，感觉还得看狗东的算法和运气。加油吧。

**Comment by zjxckangkang** [comment]
mac换成浅色模式再运行脚本
