### ISSUE TITLE
大佬 每次都是这样噗

### ISSUE THREAD

**Issue by rost001** [huanghyw/jd_seckill#27]
![image](https://user-images.githubusercontent.com/36664434/102584624-c5ac1180-4141-11eb-8fc4-bb063e92f571.png)

**Comment by rost001** [comment]
获取不到商品链接

**Comment by huanghyw** [comment]
目前不支持加购物车抢购的商品

**Comment by rost001** [comment]
我这个也是像茅台一样预约抢购的

**Comment by rost001** [comment]
![Uploading image.png…]()

**Comment by rost001** [comment]
![image](https://user-images.githubusercontent.com/36664434/102585070-a8c40e00-4142-11eb-9ba9-13aa05cae4d6.png)

**Comment by huanghyw** [comment]
有最新的日志吗？我看截图的日志还没到抢购时间

**Comment by rost001** [comment]
![image](https://user-images.githubusercontent.com/36664434/102585485-78c93a80-4143-11eb-96d7-fa601067bdf2.png)

**Comment by rost001** [comment]
有，发了

**Comment by huanghyw** [comment]
控制台有报错吗？有的话贴上来看下

**Comment by rost001** [comment]
没有报错

**Comment by rost001** [comment]
![image](https://user-images.githubusercontent.com/36664434/102585800-fa20cd00-4143-11eb-8dfc-1fdd2a89be50.png)
大概是这个

**Comment by rost001** [comment]
拿不到url的原因

**Comment by huanghyw** [comment]
cookie是怎么获取的？建议用Chrome浏览器在订单结算页面获取。

**Comment by rost001** [comment]
![image](https://user-images.githubusercontent.com/36664434/102585984-4d931b00-4144-11eb-94ce-3778334d04f7.png)
这样子获取的，cookie那一大串我全部拿过去了

**Comment by rost001** [comment]
![image](https://user-images.githubusercontent.com/36664434/102586068-6e5b7080-4144-11eb-8fda-88f59dda9243.png)
这样子获取的，cookie全部拿过了

**Comment by rost001** [comment]
这样子获取的，cookie全部拿过了
![image](https://user-images.githubusercontent.com/36664434/102586156-934fe380-4144-11eb-9f9a-e051fa14b1ab.png)

**Comment by huanghyw** [comment]
你在页面上点一下抢购是什么界面？

**Comment by VoidChen10** [comment]
点抢购是灰的，根本进不去

**Comment by rost001** [comment]
现在没货了，对灰色的

**Comment by VoidChen10** [comment]
![image](https://user-images.githubusercontent.com/26099534/102586650-8384cf00-4145-11eb-8c1f-cc6855924e93.png)

**Comment by rost001** [comment]
这个和茅台是一样的需要预约然后秒被抢没的那种

**Comment by rost001** [comment]
反正我这边调试看每次获取抢购商品的链接时，返回的是
![image](https://user-images.githubusercontent.com/36664434/102586867-d9f20d80-4145-11eb-861c-ade8301ccb75.png)
这个 之前是一开始会这么提示到后面他会变成抢购失败  现在是一开始到结束一直都是链接失败的提示

**Comment by huanghyw** [comment]
应该是商品一下就被秒光了，所以拿不到链接。下次可以脚本抢购的时候也人工去点一下，看看出来的是什么界面。

**Comment by rost001** [comment]
好，那我明天再试试别的显卡， 谢谢你了。

**Comment by huanghyw** [comment]
客气了

**Comment by VoidChen10** [comment]
是不是跟购物车有关，今天这个七彩虹的，预约的时候会同时加进购物车。像这样
![image](https://user-images.githubusercontent.com/26099534/102588208-073fbb00-4148-11eb-831c-b542592bbf43.png)
还有一种是不会加进购物车的，像这样：
![image](https://user-images.githubusercontent.com/26099534/102588235-16bf0400-4148-11eb-89cb-ffac6dd2d6ef.png)

**Comment by rost001** [comment]
我用电脑预约的 没有这个提示有可能哦!!!

**Comment by huanghyw** [comment]
只要是进购物车的就不行，目前不支持。
大家可以预约后去购物车确认下，如果进了就不能用程序抢了。

**Comment by rost001** [comment]
好！ 我去看看购物车有没有这个

**Comment by rost001** [comment]
还真是！老是用电脑预约 没有那个提示

**Comment by rost001** [comment]
![image](https://user-images.githubusercontent.com/36664434/102601303-ee8cd080-415a-11eb-98a8-7d336f3db7a3.png)
  好像 不是购物车方式的也不行

**Comment by lovefisher** [comment]
@huanghyw 花了点时间把购物车抢购实现了 测试后再PR给你？
![Uploading 413591608287667_.pic_hd.jpg…]()

**Comment by wzphood** [comment]
感觉显卡比茅台还难抢

**Comment by huanghyw** [comment]
> @huanghyw 花了点时间把购物车抢购实现了 测试后再PR给你？

等你好消息

**Comment by brynax0q** [comment]
> ![image](https://user-images.githubusercontent.com/36664434/102601303-ee8cd080-415a-11eb-98a8-7d336f3db7a3.png)
> 好像 不是购物车方式的也不行

我昨晚也尝试了... 不进购物车的预约抢购拿不到url，用jd-assistant那个项目试了下也不行.. 然后发现这两个项目调的jd秒杀接口一样，所以我感觉应该是jd那边改掉了..
