### ISSUE TITLE
提示  抢购链 接获取失败，稍后自动重试，大佬们怎么设置的

### ISSUE THREAD

**Issue by whale-max** [huanghyw/jd_seckill#271]
2020-12-30 10:16:25,226 - 21960-MainThread - E:\study\project\jd_seckill\jd_spider_requests.py[line:460] - INFO: 抢购链 接获取失败，稍后自动重试

**Comment by JJBoomShaKa** [comment]
config.ini文件里的buy_time,你设定对了吗？我测试的时候，时间不太对，也出现了你这个提示。
![image](https://user-images.githubusercontent.com/32153809/103325887-d422f300-4a88-11eb-9ccf-cbd951f0dd85.png)

**Comment by Lance-404** [comment]
10:16:25时间是10点16分了，已经抢完了，京东把链接下了吧，导致你找不到这个链接了，你到时候预约完了改成31号就好了

**Comment by whale-max** [comment]
> config.ini文件里的buy_time,你设定对了吗？我测试的时候，时间不太对，也出现了你这个提示。
> ![image](https://user-images.githubusercontent.com/32153809/103325887-d422f300-4a88-11eb-9ccf-cbd951f0dd85.png)

嗯，我测试 设置了别的商品 ，难道只能maotai？？？不是把

**Comment by whale-max** [comment]
> 10:16:25时间是10点16分了，已经抢完了，京东把链接下了吧，导致你找不到这个链接了，你到时候预约完了改成31号就好了

测试 换了商品sku_id，直接运行，别的商品链接应该一直都在，还提示 链接获取失败

**Comment by JJBoomShaKa** [comment]
> > 10:16:25时间是10点16分了，已经抢完了，京东把链接下了吧，导致你找不到这个链接了，你到时候预约完了改成31号就好了
> 
> 测试 换了商品sku_id，直接运行，别的商品链接应该一直都在，还提示 链接获取失败

注意看readme文件，作者已经提示了，其他商品目前不行，原因还未知。
![image](https://user-images.githubusercontent.com/32153809/103327031-e0f61580-4a8d-11eb-90e0-ecc504d9e82e.png)
