### ISSUE TITLE
有网友说其实这是抽签制的，怎么看？

### ISSUE THREAD

**Issue by JJBoomShaKa** [huanghyw/jd_seckill#274]
说是有人03分的时候还可以买到，有人抢了半天都抢不到，抽签制是有可能存在的吧？还是分地区抢购啥的？

**Comment by Themis2017** [comment]
还是要看账号，我两个同事都没准点去抢，都抢到了。其中一个甚至在3分的时候。亲身经历！

**Comment by lllrrr2** [comment]
有人说在预约的时候就已经决定了你的中奖机会。

**Comment by OceanNg529** [comment]
我觉得是抽签了。这样就可以避免服务器炸了，导致出现很多问题吧，并发性挺考验服务器性能的。
预约再内部抽签，安排得明明白白，绝不出错。

**Comment by JJBoomShaKa** [comment]
> 我觉得是抽签了。这样就可以避免服务器炸了，导致出现很多问题吧，并发性挺考验服务器性能的。
> 预约再内部抽签，安排得明明白白，绝不出错。

这个很有道理~

**Comment by Lance-404** [comment]
是的， 有人说你预约的时候就已经跟你账户里面分配好了，所以你只要去抢就有，不抢的话也不会再给其他人？

**Comment by yliu46** [comment]
据说59时预约成功率高

**Comment by OceanNg529** [comment]
> 是的， 有人说你预约的时候就已经跟你账户里面分配好了，所以你只要去抢就有，不抢的话也不会再给其他人？

按照这个预约量来看，基本都能分完的。分不完下一批，他也没有公布有多少瓶可以抢

**Comment by supermqB** [comment]
按脚步的输出来看，如果抽签的话，应该第一次请求就中。
事实是，try了好几次之后才中的。

**Comment by JJBoomShaKa** [comment]
> 按脚步的输出来看，如果抽签的话，应该第一次请求就中。
> 事实是，try了好几次之后才中的。

是呢，也是因为这个原因，我也怀疑抽签制的说法是错误的

**Comment by keyofd** [comment]
我也觉得是不是抽签的，我抢很久，毛都没有，我信用分也很高
