### ISSUE TITLE
INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

### ISSUE THREAD

**Issue by CodePlayerMingz** [huanghyw/jd_seckill#275]
运行的时候出现了两条INFO，一条是标题，一条是：
抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
这条可以理解，请问标题的INFO：INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】，是哪里出了问题？

**Comment by Mxiansheng** [comment]
我的也是提示这样

**Comment by RomanticHW** [comment]
一样 应该没啥问题

**Comment by Mxiansheng** [comment]
> 一样应该没啥问题

可能就是没抢到而已   多试几天看看

**Comment by dongdongcao** [comment]
我也是这个日志，求解
