### ISSUE TITLE
是否我设置还有问题？抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

### ISSUE THREAD

**Issue by LishanZhong** [huanghyw/jd_seckill#277]
抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】，是否我设置还有问题？
出现这个提示是我设置有问题还是没抢到正常就这样的？

**Comment by Mr-Tommy** [comment]
只要日志中有“很遗憾没有抢到，再接再厉哦”，就说明程序和配置都没问题，只是没抢到而已，我是这么理解的，我的日志里有145次“很遗憾没有抢到，再接再厉哦”，说明成功提交了145次，只是没有抢到
