### ISSUE TITLE
怎么更换账号

### ISSUE THREAD

**Issue by YYzoneYY** [huanghyw/jd_seckill#278]
怎么更换账号

**Comment by supermqB** [comment]
config.ini, 改eid， fp

**Comment by RomanticHW** [comment]
你这样子是抢到了 羡慕

**Comment by YYzoneYY** [comment]
> config.ini，改eid，fp

我用新账号登陆网页版的 这两个字段跟旧账号一样啊- - 怎么更换 换浏览器吗

**Comment by dreverlyu** [comment]
> > config.ini，改eid，fp
> 
> 我用新账号登陆网页版的 这两个字段跟旧账号一样啊- - 怎么更换 换浏览器吗

我用新浏览器，不同账号登录了，eid，fp不同了，运行起来还是同一个账号

**Comment by YYzoneYY** [comment]
> > > config.ini，改eid，fp
> > 
> > 
> > 我用新账号登陆网页版的 这两个字段跟旧账号一样啊- - 怎么更换 换浏览器吗
> 
> 我用新浏览器，不同账号登录了，eid，fp不同了，运行起来还是同一个账号

ok 明天试试

**Comment by dreverlyu** [comment]
> > > > config.ini，改eid，fp
> > > 
> > > 
> > > 我用新账号登陆网页版的 这两个字段跟旧账号一样啊- - 怎么更换 换浏览器吗
> > 
> > 
> > 我用新浏览器，不同账号登录了，eid，fp不同了，运行起来还是同一个账号
> 
> ok 明天试试

我是说，用了不同浏览器，也不行 =.=

**Comment by YYzoneYY** [comment]
> > > > > config.ini，改eid，fp
> > > > 
> > > > 
> > > > 我用新账号登陆网页版的 这两个字段跟旧账号一样啊- - 怎么更换 换浏览器吗
> > > 
> > > 
> > > 我用新浏览器，不同账号登录了，eid，fp不同了，运行起来还是同一个账号
> > 
> > 
> > ok 明天试试
> 
> 我是说，用了不同浏览器，也不行 =.=

重新解压缩文件应该就可以

**Comment by cat-drink-coffe** [comment]
> > > > > > config.ini，改eid，fp
> > > > > 
> > > > > 
> > > > > 我用新账号登陆网页版的 这两个字段跟旧账号一样啊- - 怎么更换 换浏览器吗
> > > > 
> > > > 
> > > > 我用新浏览器，不同账号登录了，eid，fp不同了，运行起来还是同一个账号
> > > 
> > > 
> > > ok 明天试试
> > 
> > 
> > 我是说，用了不同浏览器，也不行 =.=
> 
> 重新解压缩文件应该就可以

解压缩什么文件？什么文件需要解压缩?程序？

**Comment by pekinghk** [comment]
cookies文件夹里的.cookies文件删了，那个保存的是你的登录信息，和eid fp没关系。

**Comment by YYzoneYY** [comment]
> cookies文件夹里的.cookies文件删了，那个保存的是你的登录信息，和eid fp没关系。

好 谢谢

**Comment by qdchenyixuan** [comment]
> cookies文件夹里的.cookies文件删了，那个保存的是你的登录信息，和eid fp没关系。

谢谢

**Comment by cat-drink-coffe** [comment]
> cookies文件夹里的.cookies文件删了，那个保存的是你的登录信息，和eid fp没关系。

我同时2个账号抢购是不是要跑2份代码 ？

**Comment by pekinghk** [comment]
> > cookies文件夹里的.cookies文件删了，那个保存的是你的登录信息，和eid fp没关系。
> 
> 我同时2个账号抢购是不是要跑2份代码 ？

可以跑两份代码，或者把登陆那边载入cookie文件的代码改一下。嫌麻烦你就跑两份代码吧
