### ISSUE TITLE
为什么报错，大神帮忙看一下

### ISSUE THREAD

**Issue by xl929700** [huanghyw/jd_seckill#28]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\0120\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\0120\\AppData\\Local\\Temp\\pip-install-3b5jf91y\\lxml\\setup.py'"'"'; __file__='"'"'C:\\Users\\0120\\AppData\\Local\\Temp\\pip-install-3b5jf91y\\lxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\0120\AppData\Local\Temp\pip-record-wifj1dgd\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\0120\appdata\local\programs\python\python39\Include\lxml'
         cwd: C:\Users\0120\AppData\Local\Temp\pip-install-3b5jf91y\lxml\
    Complete output (74 lines):
    Building lxml version 4.5.1.
    Building without Cython.
    Building against pre-built libxml2 andl libxslt libraries
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\lxml
    copying src\lxml\builder.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\cssselect.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\sax.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\_elementpath.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\__init__.py -> build\lib.win-amd64-3.9\lxml
    creating build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win-amd64-3.9\lxml\html
    creating build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\etree.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\etree_api.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\__init__.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\0120\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\0120\\AppData\\Local\\Temp\\pip-install-3b5jf91y\\lxml\\setup.py'"'"'; __file__='"'"'C:\\Users\\0120\\AppData\\Local\\Temp\\pip-install-3b5jf91y\\lxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\0120\AppData\Local\Temp\pip-record-wifj1dgd\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\0120\appdata\local\programs\python\python39\Include\lxml' Check the logs for full command output.

**Comment by huanghyw** [comment]
这是环境问题吧？这个只能您自己研究了。

**Comment by xl929700** [comment]
> 这是环境问题吧？这个只能您自己研究了。

好吧！谢谢
