### ISSUE TITLE
90008小白信用低解释不合理

### ISSUE THREAD

**Issue by hansolo123321** [huanghyw/jd_seckill#280]
我的小白信用103分，plus分105分。但是今天第一次开抢最关键的第一次第二次都返回90008，后面几次开始有90016并且参杂着90008 。
我的理解是，90008直接拒绝，显示抢购失败，90016是已经生成订单，但是提交订单时间晚，抢购失败。
概率上我觉得跟小白信用关系不大，我估计是大数据杀熟，90008意味着老用户，90016代表有购买潜力的新用户

**Comment by gdcapf** [comment]
小白信用是怎么看的？

**Comment by supermqB** [comment]
我的，最上面，小字。

**Comment by keyofd** [comment]
我小白分100+，京享值8W，没成功过，难受

**Comment by JsonMa** [comment]
> 我小白分100+，京享值8W，没成功过，难受

再接再历！
