### ISSUE TITLE
无法在命令行输出二维码

### ISSUE THREAD

**Issue by jphtmt** [huanghyw/jd_seckill#282]
zbarimg qr_code.png > qrcode.txt && qrencode -r qrcode.txt -o - -t UTF8
该条命令无法在命令行输出二维码
![image](https://user-images.githubusercontent.com/16203408/103326000-50b5d180-4a89-11eb-8c89-2e4adb3e95f6.png)

**Comment by gqs4352** [comment]
命令行能显示图片吗

**Comment by jphtmt** [comment]
> 命令行能显示图片吗

不能显示，都报错了呀
