### ISSUE TITLE
我启了10个进程，2个进程同时买到

### ISSUE THREAD

**Issue by Heinekenbear** [huanghyw/jd_seckill#283]

**Comment by Mr-Tommy** [comment]
那就是4瓶么😁

**Comment by Heinekenbear** [comment]
![image](https://user-images.githubusercontent.com/8666150/103326088-befa9400-4a89-11eb-8200-408d6ac7361a.png)

**Comment by U97F3** [comment]
是开多个终端？

**Comment by lllrrr2** [comment]
这是怎么做到的

**Comment by Mxiansheng** [comment]
10个线程是运行了十个mian.py？

**Comment by supermqB** [comment]
技术科普来来。

**Comment by Mxiansheng** [comment]
大家一起讨论一下     让还没有抢到的兄弟一起致富一下   别便宜了黄牛

**Comment by Mr-Tommy** [comment]
> 大家一起讨论一下 让还没有抢到的兄弟一起致富一下 别便宜了黄牛

让这为老兄科普一下怎么抢到的

**Comment by heroPool** [comment]
python的多线程跟Java的多线程不一样，python只有 多进程 才能发挥多核优势

**Comment by Heinekenbear** [comment]
说错了，多进程，python有cpython有GIL，多线程没有用，下面代码处改成自己pc的核数
def seckill_by_proc_pool(self, work_count=5):
        """
        多进程进行抢购
        work_count：进程数量
        """
        with ProcessPoolExecutor(work_count) as pool:
            for i in range(work_count):
                pool.submit(self.seckill)

**Comment by desstiony** [comment]
明天放到本地的服务器上跑，配置杠杠的

**Comment by supermqB** [comment]
那你是同一个账号吗？岂不是买到四瓶？顺便test京东的bug？

**Comment by Mxiansheng** [comment]
四核心  八线程   是不是得改成4？

**Comment by LishanZhong** [comment]
能开源吗大佬？

**Comment by xun404** [comment]
真的是抢到的4瓶么？能看下订单截图么？

**Comment by jiaguoquan** [comment]
@Heinekenbear 一个账号抢到4瓶，不会都给发货吧

**Comment by zlf0308** [comment]
京东24小时内只能提交一单吧

**Comment by ZRT-1998** [comment]
这样不行的，信不信你开100个号也只有1个号能抢中，估计跟ip有关系
