### ISSUE TITLE
问一个非常白痴问题

### ISSUE THREAD

**Issue by weiwey** [huanghyw/jd_seckill#29]
我想问下cookie在哪里获取。谷歌和百度搜 都搜不到，我是新手。
http request header里面的cookie ，一直没搞懂这是哪里。我的chrome有问题么。。求救
![687`QB8DWL)5SG{IMVLLO1Y](https://user-images.githubusercontent.com/76201081/102589196-91672f80-4106-11eb-87b5-830dba24b25e.png)

**Comment by caihuoche** [comment]
不是白痴,是门外汉阿

**Comment by weiwey** [comment]
> 不是白痴，是门外汉阿

能方便指导一下吗。大神

**Comment by wzphood** [comment]
登陆后，在NetWork里，选js，在里面一个个点开看有没有cookie
![InkedAC0_0G8O@CE E1GGTJQR$@V_LI](https://user-images.githubusercontent.com/53933429/102635472-43c0e600-414b-11eb-9221-f1afc17e52c4.jpg)

**Comment by huanghyw** [comment]
过段时间上线扫码登录，到时候就不需要手动复制粘贴Cookie了。
着急的可以关注这个分支：https://github.com/huanghyw/jd_seckill/tree/feature-hyw-qrcode_login

**Comment by huanghyw** [comment]
现在不需要手动复制粘贴Cookies了，直接扫码登录
