### ISSUE TITLE
感谢大佬，抢到了2瓶

### ISSUE THREAD

**Issue by hexiaoleione** [huanghyw/jd_seckill#290]
终于干过了黄牛

**Comment by cat-drink-coffe** [comment]
> 终于干过了黄牛

你是哪个地区的

**Comment by Mr-Tommy** [comment]
你们都是哪个时间点抢到的，我10：02就不抢了

**Comment by hexiaoleione** [comment]
> > 终于干过了黄牛
> 
> 你是哪个地区的

北京

**Comment by hexiaoleione** [comment]
> 你们都是哪个时间点抢到的，我10：02就不抢了

我设置的定时，9点59开始，10点01结束。我也没当回事，10点10几的时候想起来了在APP上看到了，惊喜

**Comment by dujingyou** [comment]
> > 你们都是哪个时间点抢到的，我10：02就不抢了
> 
> 我设置的定时，9点59开始，10点01结束。我也没当回事，10点10几的时候想起来了在APP上看到了，惊喜

下单时间是多少？？
