### ISSUE TITLE
今天好像jd茅台小组就开始改抢购参数了

### ISSUE THREAD

**Issue by liusuifeng-life** [huanghyw/jd_seckill#297]

**Comment by Heinekenbear** [comment]
传播得太广了

**Comment by guixiaoyuan** [comment]
是的，Log信息 抢购链接获取失败，稍后自动重试

**Comment by keyofd** [comment]
刚发现这个项目，就不行了？？？？

**Comment by hyb855** [comment]
> 刚发现这个项目，就不行了？？？？

一脸懵逼

**Comment by kevin-garrnet-hh** [comment]
> > 刚发现这个项目，就不行了？？？？
> 
> 一脸懵逼

是的，已经不行了，现在就是--抢购链接获取失败，稍后自动重试

**Comment by hyb855** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kevin-garrnet-hh <notifications@github.com&gt;
发送时间: 2020年12月30日 11:32
收件人: huanghyw/jd_seckill <jd_seckill@noreply.github.com&gt;
抄送: hyb855 <823882442@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[huanghyw/jd_seckill] 今天好像jd茅台小组就开始改抢购参数了 (#297)





   
刚发现这个项目，就不行了？？？？
  
一脸懵逼
  
是的，已经不行了，现在就是--抢购链接获取失败，稍后自动重试

**Comment by hyb855** [comment]
还有什么好项目吗老哥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kevin-garrnet-hh <notifications@github.com&gt;
发送时间: 2020年12月30日 11:32
收件人: huanghyw/jd_seckill <jd_seckill@noreply.github.com&gt;
抄送: hyb855 <823882442@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[huanghyw/jd_seckill] 今天好像jd茅台小组就开始改抢购参数了 (#297)





   
刚发现这个项目，就不行了？？？？
  
一脸懵逼
  
是的，已经不行了，现在就是--抢购链接获取失败，稍后自动重试

**Comment by perfectar** [comment]
有大佬发现啥原因吗？
