### ISSUE TITLE
传播太厉害了，作者还是小心一点

### ISSUE THREAD

**Issue by XiaoHb233** [huanghyw/jd_seckill#310]
有人贴吧，csdn收费，咸鱼登卖钱，估计活不久了，一个从43★到现在的4.4k★的老人

**Comment by LiamChan** [comment]
是啊，这些人真的是过分了

**Comment by uruseikyo** [comment]
在别的地方看到收费的，
必须顺手举报一波

**Comment by cljnnn** [comment]
昨天还2k，现在已经4.5k了。不知道接下来会怎么样

**Comment by XiaoHb233** [comment]
> 在别的地方看到收费的，
> 必须顺手举报一波

csdn我已经举报很多了

**Comment by qzcyy** [comment]
收费的那些人真过分了，多少好项目都被这群人搞没了

**Comment by Mxiansheng** [comment]
今天看到我关注的好多公众号都在发这个项目
