### ISSUE TITLE
为什么我运行main报错啊

### ISSUE THREAD

**Issue by wangben5** [huanghyw/jd_seckill#314]
![Uploading 微信截图_20201230112109.png…]()
，有人可以帮忙看看吗？我哪儿配置出问题了

**Comment by wangben5** [comment]
报错log》》》
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
========= RESTART: C:\Users\12345\Desktop\jd\jd_seckill-master\main.py =========
Traceback (most recent call last):
  File "C:\Users\12345\Desktop\jd\jd_seckill-master\main.py", line 2, in <module>
    from jd_spider_requests import JdSeckill
  File "C:\Users\12345\Desktop\jd\jd_seckill-master\jd_spider_requests.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>>

**Comment by SuperHanKunLin** [comment]
太低级的错误了，还是去读个大学再来吧

**Comment by shaocong1994219** [comment]
去pip一个requests

**Comment by wangben5** [comment]
我真不会这个，麻烦兄弟说下

**Comment by wangben5** [comment]
@shaocong1994219 好的，谢谢，我试下

**Comment by wangben5** [comment]
@SuperHanKunLin 爸爸会了，依然感谢

**Comment by AsiaZhang123** [comment]
小白还是不要参与这种活动了

**Comment by wangben5** [comment]
@AsiaZhang123 感谢提醒，我想问下二维码登录成功过后没有反应是什么情况，就没有后续了
2020-12-30 11:35:15,665 - 6052-MainThread - C:\Users\12345\Desktop\jd\jd_seckill-master\jd_spider_requests.py[line:266] - INFO: 二维码登录成功

**Comment by AsiaZhang123** [comment]
看你选的是1 还是2了。选1是预约，登陆完就没事了。选2是开始抢购。不知道现在还能不能正常用，传的太厉害了，JD估计已经在改了。
