### ISSUE TITLE
投诉下相关自媒体和公众号吧

### ISSUE THREAD

**Issue by RomanticHW** [huanghyw/jd_seckill#316]
https://www.sohu.com/a/441253659_463994
转发不长眼睛 恶臭

**Comment by RomanticHW** [comment]
作者：明哥

编辑：陶家龙

出处：转载自公众号Python编程时光（ID：Cool-Python），注：本文仅代表作者观点不代表平台观点。返回搜狐，查看更多

**Comment by huanghyw** [comment]
之前投诉过两个直接原文拿过去不加改动还收费的CSDN的博主，后来文章下架了。

这篇文章也被转载过多次了，我看着也还行，少部分的引用，大部分是自己写的。

**Comment by huhewen** [comment]
> 之前投诉过两个直接原文拿过去不加改动还收费的CSDN的博主，后来文章下架了。
> 
> 这篇文章也被转载过多次了，我看着也还行，少部分的引用，大部分是自己写的。


作者在github的声明里说禁止公众号转载和发布
Author
人家说的是你禁止转载发布资源和文件，我并没有转载发布资源文件啊。。

**Comment by strivecheng** [comment]
这些傻逼自媒体，公众号真的恶心。tm天天自己没吊技术，就知道搞这些，一群司马玩意。

> > 之前投诉过两个直接原文拿过去不加改动还收费的CSDN的博主，后来文章下架了。
> > 这篇文章也被转载过多次了，我看着也还行，少部分的引用，大部分是自己写的。
> 
> 作者在github的声明里说禁止公众号转载和发布
> Author
> 人家说的是你禁止转载发布资源和文件，我并没有转载发布资源文件啊。。

你tm抄袭还有理了，司马玩意，刚注册的傻逼

**Comment by strivecheng** [comment]
这些傻逼自媒体，公众号真的恶心。tm天天自己没吊技术，就知道搞这些，要么抄袭，要么靠这些刷流量，一群司马玩意，垃圾公众号作者活该被车装死。

**Comment by huhewen** [comment]
> 这些傻逼自媒体，公众号真的恶心。tm天天自己没吊技术，就知道搞这些，一群司马玩意。
> 
> > > 之前投诉过两个直接原文拿过去不加改动还收费的CSDN的博主，后来文章下架了。
> > > 这篇文章也被转载过多次了，我看着也还行，少部分的引用，大部分是自己写的。
> > 
> > 
> > 作者在github的声明里说禁止公众号转载和发布
> > Author
> > 人家说的是你禁止转载发布资源和文件，我并没有转载发布资源文件啊。。
> 
> 你tm抄袭还有理了，司马玩意，刚注册的傻逼

这是我在“Python编程时光” 这个公众号下的留言及公众号作者的回复，我说代码作者不让传播，他说他的方式没问题。

**Comment by strivecheng** [comment]
> > 这些傻逼自媒体，公众号真的恶心。tm天天自己没吊技术，就知道搞这些，一群司马玩意。
> > > > 之前投诉过两个直接原文拿过去不加改动还收费的CSDN的博主，后来文章下架了。
> > > > 这篇文章也被转载过多次了，我看着也还行，少部分的引用，大部分是自己写的。
> > > 
> > > 
> > > 作者在github的声明里说禁止公众号转载和发布
> > > Author
> > > 人家说的是你禁止转载发布资源和文件，我并没有转载发布资源文件啊。。
> > 
> > 
> > 你tm抄袭还有理了，司马玩意，刚注册的傻逼
> 
> 这是我在“Python编程时光” 这个公众号下的留言及公众号作者的回复，我说代码作者不让传播，他说他的方式没问题。

那你就投诉他

**Comment by huhewen** [comment]
> > > 这些傻逼自媒体，公众号真的恶心。tm天天自己没吊技术，就知道搞这些，一群司马玩意。
> > > > > 之前投诉过两个直接原文拿过去不加改动还收费的CSDN的博主，后来文章下架了。
> > > > > 这篇文章也被转载过多次了，我看着也还行，少部分的引用，大部分是自己写的。
> > > > 
> > > > 
> > > > 作者在github的声明里说禁止公众号转载和发布
> > > > Author
> > > > 人家说的是你禁止转载发布资源和文件，我并没有转载发布资源文件啊。。
> > > 
> > > 
> > > 你tm抄袭还有理了，司马玩意，刚注册的傻逼
> > 
> > 
> > 这是我在“Python编程时光” 这个公众号下的留言及公众号作者的回复，我说代码作者不让传播，他说他的方式没问题。
> 
> 那你就投诉他

你可以去试试
