### ISSUE TITLE
测试过程发现代码出现问题

### ISSUE THREAD

**Issue by MissCuriosity** [huanghyw/jd_seckill#318]
选择2
<img width="706" alt="image" src="https://user-images.githubusercontent.com/12730051/103327925-ab532b80-4a91-11eb-9552-95defe58b548.png">
选择1预约，二维码一直失效

**Comment by whherui** [comment]
电脑登陆你的账号，关闭你账号的登陆保护

**Comment by MissCuriosity** [comment]
> 电脑登陆你的账号，关闭你账号的登陆保护

感谢回复，虽然感觉这个库要凉了。

> 电脑登陆你的账号，关闭你账号的登陆保护
