### ISSUE TITLE
虽然我是昨天才知道大佬的库的，也没有抢到过，为了大佬的安全，我还是建议大佬先删库，避避风头吧。

### ISSUE THREAD

**Issue by lllrrr2** [huanghyw/jd_seckill#319]
在我大中华，还是人怕出名啊。

**Comment by Mxiansheng** [comment]
不要再传播了  仅此而已吧

**Comment by lllrrr2** [comment]
管不住那些SB啊，我猜估计再二天，油管上的UP都会做教程吸粉了

**Comment by AsiaZhang123** [comment]
真的传的太快了，昨天我知道的时候star还不到2K,现在已经快5k了。我觉得今天或者明天JD肯定就会有应对方案了。

**Comment by maotai1499** [comment]
我一直在研究茅台，去年有新闻报道一个搞茅台的团队被抓了，好像提供程序的人被判的很重，好像是3年，估计这个程序员出来也废了，没大厂敢用了，佩服作者的勇气 @huanghyw

**Comment by 495806109** [comment]
还是赶紧删了吧

**Comment by maotai1499** [comment]
> 还是赶紧删了吧

现在已经传播开了，你看fork数，主要还是得看京东的法务部门怎么弄？

**Comment by iSaury** [comment]
> > 还是赶紧删了吧
> 
> 现在已经传播开了，你看fork数，主要还是得看京东的法务部门怎么弄？

你是黄牛怕很多人知道这个跟你抢吧？哪里新闻，张口就来？那是制作假冒茅台的好吧

**Comment by 495806109** [comment]
如果jd重视起来作者是会法律责任的

**Comment by 495806109** [comment]
> > > 还是赶紧删了吧
> > 
> > 
> > 现在已经传播开了，你看叉数，主要还是得看京东的法务部门怎么弄？
> 
> 你是黄牛怕很多人知道这个跟你抢吧？哪里新闻，张口就来？那是制作假冒茅茅台的好吧

如果jd重视起来作者是会法律责任的

**Comment by xiong0317** [comment]
+1

**Comment by Lance-404** [comment]
我也觉得，带佬删了吧，人太多了

**Comment by lany192** [comment]
京东不会要求删的，因为抢购要充值会员，他是赚钱的。越多人抢就越多人充钱。控制放货数量，完美

**Comment by cat-drink-coffe** [comment]
> 京东不会要求删的，因为抢购要充值会员，他是赚钱的。越多人抢就越多人充钱。控制放货数量，完美

我去 京东估计要请你去搞运营了

**Comment by strivecheng** [comment]
> > > 还是赶紧删了吧
> > 
> > 
> > 现在已经传播开了，你看fork数，主要还是得看京东的法务部门怎么弄？
> 
> 你是黄牛怕很多人知道这个跟你抢吧？哪里新闻，张口就来？那是制作假冒茅台的好吧

明显是黄牛，刚注册的小号

**Comment by strivecheng** [comment]
> 我一直在研究茅台，去年有新闻报道一个搞茅台的团队被抓了，好像提供程序的人被判的很重，好像是3年，估计这个程序员出来也废了，没大厂敢用了，佩服作者的勇气 @huanghyw

喲，黄牛还会注册github了啊。是不是涉及到你的利益了？司马黄牛，傻逼玩意
