### ISSUE TITLE
有人用这个抢到过显卡嘛，比如华硕3080？

### ISSUE THREAD

**Issue by CangShui** [huanghyw/jd_seckill#32]
有人用这个抢到过显卡嘛，比如华硕3080？

**Comment by CangShui** [comment]
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
2020-12-19 16:29:05,174 - 5992-MainThread - C:\Users\Desktop\jd_seckill-master\timer.py[line:14] - INFO: 正在等待到达设定时间:2020-12-23 11:00:00.100000

**Comment by wzphood** [comment]
显卡是加购物车的，应该不行
并且按现在的放货量，感觉还没茅台概率大

**Comment by nqianaaron** [comment]
各位大佬。如何获取sku_id啊

**Comment by huanghyw** [comment]
> 各位大佬。如何获取sku_id啊

readme里面有写
