### ISSUE TITLE
main程序启动错误

### ISSUE THREAD

**Issue by joezhu9** [huanghyw/jd_seckill#320]
![image](https://user-images.githubusercontent.com/52144140/103328133-84e1c000-4a92-11eb-82df-20443085c809.png)
![image](https://user-images.githubusercontent.com/52144140/103328161-9aef8080-4a92-11eb-9dd1-2c171ff1dbe8.png)
请问这个库是版本不对么还是？

**Comment by kevin-garrnet-hh** [comment]
> ![image](https://user-images.githubusercontent.com/52144140/103328133-84e1c000-4a92-11eb-82df-20443085c809.png)
> ![image](https://user-images.githubusercontent.com/52144140/103328161-9aef8080-4a92-11eb-9dd1-2c171ff1dbe8.png)
> 请问这个库是版本不对么还是？

不要挣扎了，JD茅台小组已经改参数了。

**Comment by joezhu9** [comment]
> > ![image](https://user-images.githubusercontent.com/52144140/103328133-84e1c000-4a92-11eb-82df-20443085c809.png)
> > ![image](https://user-images.githubusercontent.com/52144140/103328161-9aef8080-4a92-11eb-9dd1-2c171ff1dbe8.png)
> > 请问这个库是版本不对么还是？
> 
> 不要挣扎了，JD茅台小组已经改参数了。

但是还是想知道这个是怎么回事，之前上课的时候也出现了类似的问题

**Comment by AsiaZhang123** [comment]
图片加载不出来的，main报错基本都是依赖库没有。

**Comment by 18262600491** [comment]
哈，环境都不会还搞个啥呢，自己百度比什么都强
