### ISSUE TITLE
兄弟们   现在最重要的是各大自媒体和公众号都在传播   

### ISSUE THREAD

**Issue by Mxiansheng** [huanghyw/jd_seckill#322]
各大自媒体和公众号都在传播

**Comment by dongshouchao** [comment]
快废了，抓紧时间搞一波吧

**Comment by merlinlynn** [comment]
现在都上oschina.net的新闻了。。。醉了https://www.oschina.net/news/125042/maotai-snap-up-script-open-source

**Comment by Lance-404** [comment]
真的搞得太快了，害，还有一堆不懂Python的再问。。。明天再搞一波可能就用不了了

**Comment by strivecheng** [comment]
这些傻逼自媒体，公众号真的恶心。tm天天自己没吊技术，就知道搞这些，一群司马玩意。
