### ISSUE TITLE
有大佬知道安装requirements.txt时报错的解决方法吗

### ISSUE THREAD

**Issue by Yeziyou666** [huanghyw/jd_seckill#325]
![QQ截图20201230114103](https://user-images.githubusercontent.com/76758802/103328547-46e59b80-4a94-11eb-99a7-174c5ea27221.png)

**Comment by Mr-Tommy** [comment]
![image](https://user-images.githubusercontent.com/16432614/103335017-9fc22d80-4aae-11eb-8120-62bc0d66a67b.png)
这个地方改成4.6.2

**Comment by Jack-Shi6** [comment]
> ![image](https://user-images.githubusercontent.com/16432614/103335017-9fc22d80-4aae-11eb-8120-62bc0d66a67b.png)
> 这个地方改成4.6.2

请问哪里需要改呢  我一直报错  图片加载不出来的

**Comment by Yeziyou666** [comment]
> ![image](https://user-images.githubusercontent.com/16432614/103335017-9fc22d80-4aae-11eb-8120-62bc0d66a67b.png)
> 这个地方改成4.6.2
大佬方便留个联系方式吗  或者加我下q1006302989
