### ISSUE TITLE
配置好以后，选择1可以预约，选择2没反应是啥情况？

### ISSUE THREAD

**Issue by joyceanson** [huanghyw/jd_seckill#327]
选择2就没动静了？
                                      
功能列表：                                                                                
 1.预约商品
 2.秒杀抢购商品
    
请选择:2

**Comment by thenext13** [comment]
你问题解决了吗？我跟你是一样的问题。按1有反应，2没有反应

**Comment by yuliezhou** [comment]
1和2有什么区别

**Comment by joyceanson** [comment]
1是预约，2是抢购呀，我还没解决，有没有大佬
