### ISSUE TITLE
这种骗赞的项目都有， 程序员谁他妈的喝茅台， 我他妈的， 谁会关注茅台， 你这是给茅台打了广告还收了韭菜，中国SB 真多

### ISSUE THREAD

**Issue by zhangyu13141H** [huanghyw/jd_seckill#328]
这种骗赞的项目都有， 程序员谁他妈的喝茅台， 我他妈的， 谁会关注茅台， 你这是给茅台打了广告还收了韭菜，中国SB 真多

**Comment by hsy1992** [comment]
死吗了？开个小号骂人

**Comment by zhangyu13141H** [comment]
我他妈的写邮件举报了，中国SB 真多， 全是些没思考能力的SB， 专门做韭菜

**Comment by Visbin** [comment]
韭菜你吗  张嘴闭嘴中国xx    你咋不去国外吃屎去

**Comment by zhangyu13141H** [comment]
你们这些缺了大德的人， 必得报应

**Comment by Mxiansheng** [comment]
臭傻逼滚？？？？？

**Comment by zhangyu13141H** [comment]
我就想问我说的是不是你们真实的目的？？？？你解释下？？？

**Comment by Mxiansheng** [comment]
> 你们这些缺了大德的人， 必得报应

傻逼  一看你就是黄牛    现在嫌别人分你们羹了    京东的茅台又不是专给你们这些黄牛准备的

**Comment by zhangyu13141H** [comment]
我黄牛你妈， 黄牛懂github ？

**Comment by Mxiansheng** [comment]
> 我黄牛你妈， 黄牛懂github ？

那你傻逼的跑来干啥  没人叫你用呀   自己手贱

**Comment by yidashi** [comment]
沙币玩意儿

**Comment by zhangyu13141H** [comment]
别他妈的往我头上扣帽子了，我他妈的根本不case 茅台。 程序员都他妈的996 了， 谁喝得起茅台？真是弱智

**Comment by zhangyu13141H** [comment]
等着， 我在看怎么举报你们

**Comment by XiaoHb233** [comment]
好家伙，新开号特意加入，到车站

**Comment by Mxiansheng** [comment]
> 别他妈的往我头上扣帽子了，我他妈的根本不case 茅台。 程序员都他妈的996 了， 谁喝得起茅台？真是弱智

那你过来发个贴是什么傻逼    喝什么茅台    就你这个傻逼程序员也是真丢程序员的脸了      你当你的加班狗就好了   管别人怎么样   臭傻逼     真是什么样的人都有

**Comment by maotai1499** [comment]
> 等着， 我在看怎么举报你们

傻逼 茅台搞你全家了  你这蠢逼黄牛  多半是搞到你的利益链吧  艹泥马

**Comment by maotai1499** [comment]
> > 等着， 我在看怎么举报你们
> 
> 傻逼 茅台搞你全家了 你这蠢逼黄牛 多半是搞到你的利益链吧 艹泥马

@zhangyu13141H

**Comment by Mr-Tommy** [comment]
小老弟怕不是没抢到气急败坏了吧，哈哈哈

**Comment by qdchenyixuan** [comment]
各位高看楼主了，楼主看不懂README，看别人赚钱又酸，各位程序员同僚趁这几天多搞几单吧，这种人cn不缺

**Comment by Mxiansheng** [comment]
出来对线   曹尼玛   你全家死绝了的煞笔玩意

**Comment by Mxiansheng** [comment]
傻逼怕是连程序怎么架设的都不知道吧

**Comment by fanyangyang188** [comment]
傻逼够多

**Comment by zhangyu13141H** [comment]
我触犯了你们的利益， 我道歉， 不说了， 你们随意

**Comment by zhangyu13141H** [comment]
别说， 仓库主 ， 还注册了不少小号

**Comment by lszh0147** [comment]
被骗了是他傻逼，你激动什么。

做为程序员 技术人员 如果这个项目不行谁他妈的点赞？ 又或者人家开心点个赞 关你屁事啊。

当然了还有刷赞的，这你就更不应该激动了。

**Comment by Mr-Tommy** [comment]
> 我触犯了你们的利益， 我道歉， 不说了， 你们随意

没有触犯，可以尽你所能去举报，快，哈哈哈

**Comment by money4marry** [comment]
还觉得别人没有思考能力，你再好好看看自己

**Comment by zhangyu13141H** [comment]
作为一个程序员， 谁会去关注茅台， 你们是程序员吗? 我是作不出你们这种违背良心的事情. 打广告+骗赞。
以后是人都可以通过你们这种渠道来骗赞了

**Comment by Mr-Tommy** [comment]
> 作为一个程序员， 谁会去关注茅台， 你们是程序员吗? 我是作不出你们这种违背良心的事情. 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了

年度最佳理财产品，茅台，你是真不知道，还是装糊涂，程序员就活该赚死工资，穷死么

**Comment by Mr-Tommy** [comment]
> 作为一个程序员， 谁会去关注茅台， 你们是程序员吗? 我是作不出你们这种违背良心的事情. 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了

你要是不会搭建运行环境，我可以教你，但是你这酸劲儿，我就看不了

**Comment by Visbin** [comment]
> 作为一个程序员， 谁会去关注茅台， 你们是程序员吗? 我是作不出你们这种违背良心的事情. 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了

你好歹有下逻辑OK？ 打广告是什么鬼，关注这个库的人难道不懂茅台？ 
骗赞又是什么鬼，是介绍和内容不符？  麻烦没脑子的你不要再自以为是的秀250的智商了

**Comment by zhangyu13141H** [comment]
I don't have the energy to check whether they cheat, but as a programmer, who will pay attention to the product of Maotai, and no programmer can afford it. This is obviously unreasonable,

Are they really programmers? I can't do anything against your conscience

Advertising + praise cheating.

In the future, people can cheat and praise through your channels

Please take it seriously and make an example

**Comment by zhangyu13141H** [comment]
我给github 官方写信了

**Comment by lvjisong** [comment]
> 作为一个程序员， 谁会去关注茅台， 你们是程序员吗? 我是作不出你们这种违背良心的事情. 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了

作为一个程序员， 为什么不可以关注茅台？抢到就是赚到，允许黄牛赚钱，不许程序员分一杯羹？就你还给github写信，真是笑话，你算个卵子。

**Comment by maotai1499** [comment]
> 我给github 官方写信了

![image](https://user-images.githubusercontent.com/76725332/103330707-a5634780-4a9d-11eb-96b2-4deec10e91c6.png)

实锤了 你很有可能是羊毛党！！！

**Comment by Mr-Tommy** [comment]
> 我给github 官方写信了

按着你这个逻辑，程序员连个茅台也买不起了，是这意思？
程序员都不会理财，都不关注股市，都只会消费，都该被坑死

**Comment by Mr-Tommy** [comment]
> > 我给github 官方写信了
> 
> ![image](https://user-images.githubusercontent.com/76725332/103330707-a5634780-4a9d-11eb-96b2-4deec10e91c6.png)
> 
> 实锤了 你很有可能是羊毛党！！！

兄弟，你的嫌疑更大😁😂

**Comment by zhangyu13141H** [comment]
![Uploading image.png…]()

**Comment by zhangyu13141H** [comment]
我要举报项目 https://github.com/huanghyw/jd_seckill，
在1天时间内增加了近3000个star 和fork，
按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
难道他们真是程序员吗? 我是作不出你们这种违背良心的事情. 
打广告+骗赞。
以后是人都可以通过你们这种渠道来骗赞了，
请github 严肃对待， 以儆效尤
就这样了， 不BB 了， 看官网怎么对待

**Comment by Mr-Tommy** [comment]
> 我要举报项目 [https://github.com/huanghyw/jd_seckill，](https://github.com/huanghyw/jd_seckill%EF%BC%8C)
> 在1天时间内增加了近3000个star 和fork，
> 按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
> 我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
> 难道他们真是程序员吗? 我是作不出你们这种违背良心的事情.
> 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了，
> 请github 严肃对待， 以儆效尤
> 就这样了， 不BB 了， 看官网怎么对待

哈哈哈，就这？？？

**Comment by zhangyu13141H** [comment]
就这了， 行不行就靠这么一哆嗦， 不废话

**Comment by XiaoHb233** [comment]
> 我给github 官方写信了


> 我要举报项目 [https://github.com/huanghyw/jd_seckill，](https://github.com/huanghyw/jd_seckill%EF%BC%8C)
> 在1天时间内增加了近3000个star 和fork，
> 按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
> 我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
> 难道他们真是程序员吗? 我是作不出你们这种违背良心的事情.
> 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了，
> 请github 严肃对待， 以儆效尤
> 就这样了， 不BB 了， 看官网怎么对待

我马化腾不喝茅台，只喝牛栏山

**Comment by Mr-Tommy** [comment]
> 就这了， 行不行就靠这么一哆嗦， 不废话

兄弟，我建议啊，加我QQ，我帮你把代码跑起来，这样你就不会这么难受了

**Comment by zhangyu13141H** [comment]
我说的是你们骗赞， 你们说我是黄牛， 完美的避开了我的观点， 答非所问

**Comment by zhangyu13141H** [comment]
我他妈的根本不case 这点小钱， 是你们的骗赞行径我才发起的

**Comment by XiaoHb233** [comment]
> 我他妈的根本不case 这点小钱， 是你们的骗赞行径我才发起的

我说我自愿的

**Comment by yszhang123** [comment]
> 我要举报项目 [https://github.com/huanghyw/jd_seckill，](https://github.com/huanghyw/jd_seckill%EF%BC%8C)
> 在1天时间内增加了近3000个star 和fork，
> 按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
> 我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
> 难道他们真是程序员吗? 我是作不出你们这种违背良心的事情.
> 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了，
> 请github 严肃对待， 以儆效尤
> 就这样了， 不BB 了， 看官网怎么对待

你这如此奇葩的行为是真不知道大家抢茅台是拿来卖的吗，一瓶转手就赚800-1000，你这样很像个脱离社会的原始人，大家都在做的事你居然会有这种反应，而且程序员的收入在中国还算靠上吧，负担不起茅台吗，1499都出不起吗

**Comment by Mr-Tommy** [comment]
> > 我要举报项目 [https://github.com/huanghyw/jd_seckill，](https://github.com/huanghyw/jd_seckill%EF%BC%8C)
> > 在1天时间内增加了近3000个star 和fork，
> > 按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
> > 我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
> > 难道他们真是程序员吗? 我是作不出你们这种违背良心的事情.
> > 打广告+骗赞。
> > 以后是人都可以通过你们这种渠道来骗赞了，
> > 请github 严肃对待， 以儆效尤
> > 就这样了， 不BB 了， 看官网怎么对待
> 
> 你这如此奇葩的行为是真不知道大家抢茅台是拿来卖的吗，一瓶转手就赚800-1000，你这样很像个脱离社会的原始人，大家都在做的事你居然会有这种反应，而且程序员的收入在中国还算靠上吧，负担不起茅台吗，1499都出不起吗

别跟他废话了，这个二哈

**Comment by zhangyu13141H** [comment]
哎呦， github 啥时候都人均喝茅台了 ， 比知乎都屌了

**Comment by Mr-Tommy** [comment]
> 哎呦， github 啥时候都人均喝茅台了 ， 比知乎都屌了

兄弟，都说的很明白了，买来转售的，转售的，你是不识字么

**Comment by Mr-Tommy** [comment]
> 哎呦， github 啥时候都人均喝茅台了 ， 比知乎都屌了

程序员就规定死了，只能敲代码，不能倒腾点其他玩意么

**Comment by yszhang123** [comment]
> 哎呦， github 啥时候都人均喝茅台了 ， 比知乎都屌了

给你这说了是拿来转卖赚钱，不是拿来自己喝的，你是哪不对劲。是不是该看看医生

**Comment by Mr-Tommy** [comment]
> 哎呦， github 啥时候都人均喝茅台了 ， 比知乎都屌了

你还知道没事儿接个私活，上班干私活呢，其他人就不允许倒腾个茅台么

**Comment by zhangyu13141H** [comment]
倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利，  你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，

**Comment by Mr-Tommy** [comment]
> 倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利， 你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，

那你说骗个赞有啥用，给这个库1000w赞有啥用，能换钱么，人家把东西给你分享出来，让你用，你不领情就算了，还抨击，到底什么心态

**Comment by Mr-Tommy** [comment]
> 倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利， 你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，

在一个说，京东一个账号每个月只能购买两瓶，你有那么多号么，自己藏着这个代码有啥用

**Comment by Mr-Tommy** [comment]
> 倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利， 你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，

恐怕我说的这些你都不知道，上来就说骗赞，我都搞不明白，骗赞到底有啥好处，一天天的赞赞赞的，就知道敲代码，能敲出什么玩意

**Comment by yszhang123** [comment]
> 倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利， 你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，

你现在说的和上面你说程序员消费不起茅台的说辞逻辑完全就对不上，居然你认可了大家是为了倒卖茅台，那何来的程序员消费不起，所以这个项目是在作假的结论，你前面就是在胡说八道。关于你后面说的闷声发大财我是赞同的，我也不想更多人来抢，所以这个项目关闭了对我们这些已经知道的人肯定有益。

**Comment by Mxiansheng** [comment]
> > 倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利， 你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，
> 
> 那你说骗个赞有啥用，给这个库1000w赞有啥用，能换钱么，人家把东西给你分享出来，让你用，你不领情就算了，还抨击，到底什么心态

不用屌他了  就是傻逼黄牛  或者是不会搞的小号   自己没抢到酸了    然后跟疯狗一样在这里疯狂咬     何必呢

**Comment by raybi-asus** [comment]
黄牛党利益被侵害了... 写抢购软件买给黄牛党的程序员疯狂来喷了.哈哈哈...
为了一点点利益, 全家挨骂到底值不值得啊

**Comment by Mr-Tommy** [comment]
> 黄牛党利益被侵害了... 写抢购软件买给黄牛党的程序员疯狂来喷了.哈哈哈...
> 为了一点点利益, 全家挨骂到底值不值得啊

估计是人家黄牛要求退款，这家伙心理防线崩溃，就这样了

**Comment by raybi-asus** [comment]
> > 黄牛党利益被侵害了... 写抢购软件买给黄牛党的程序员疯狂来喷了.哈哈哈...
> > 为了一点点利益, 全家挨骂到底值不值得啊
> 
> 估计是人家黄牛要求退款，这家伙心理防线崩溃，就这样了

肯定了,正常程序员有人这么无聊上来举报一个工具类软件么... 当然是自己利益被侵害了.要么就是受到别人指使了..这种人太可怜了.钱没赚到,全家连带着挨骂....简直凄惨

**Comment by WvvvWv** [comment]
我和朋友今天抢到了四瓶嘻嘻

**Comment by WvvvWv** [comment]
> 倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利， 你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，

赞能换钱吗？

**Comment by WvvvWv** [comment]
> 倒腾个茅台绝对没问题， 我不是针对产品， 是你们的骗赞行为， 你老是把群众拉到你们的一面，但是你们的行为更本经不起任何分析，自古闷声发大财， 大家都来抢茅台了，你自己弄不是抢的更多更顺利， 你还有机会卖出去， 你自己弄不是更好， 哪个灰产不是自己偷偷的赚钱， 还能宣传开来了？ 还能通知大家来赚钱？我是可耻你们的骗赞行为，

那在这说锤子呢

**Comment by 124754649** [comment]
@WvvvWv  目测是动了某些人的利益或者蛋糕了  😂😂😂

**Comment by WvvvWv** [comment]
> @WvvvWv 目测是动了某些人的利益或者蛋糕了 😂😂😂

我觉得也是

**Comment by huisnotacouncillor** [comment]
茅台的英文写错了， 不是Maotai， 是Moutai

**Comment by roytalyan** [comment]
> 我他妈的根本不case 这点小钱， 是你们的骗赞行径我才发起的

你是想说 不care ？

**Comment by cwl12** [comment]
看见有这么多人骂楼主，我心里就踏实了

**Comment by raybi-asus** [comment]
@roytalyan 奉劝你一句话, 打人不打脸,骂人不揭短. 哈哈哈哈

**Comment by cat-drink-coffe** [comment]
> 我说的是你们骗赞， 你们说我是黄牛， 完美的避开了我的观点， 答非所问

你的骗的定义是什么？

**Comment by Allen0828** [comment]
> 这种骗赞的项目都有， 程序员谁他妈的喝茅台， 我他妈的， 谁会关注茅台， 你这是给茅台打了广告还收了韭菜，中国SB 真多

你不喝不代表别人不喝， 你是孤儿不代表别人是 OK？  给我家里人买有问题？  就你这个智障 别用中文了。  癞蛤蟆爬到脚面上，不咬人光恶心人

**Comment by money4marry** [comment]
> 我要举报项目 [https://github.com/huanghyw/jd_seckill，](https://github.com/huanghyw/jd_seckill%EF%BC%8C)
> 在1天时间内增加了近3000个star 和fork，
> 按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
> 我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
> 难道他们真是程序员吗? 我是作不出你们这种违背良心的事情.
> 打广告+骗赞。
> 以后是人都可以通过你们这种渠道来骗赞了，
> 请github 严肃对待， 以儆效尤
> 就这样了， 不BB 了， 看官网怎么对待

好好好，你说作者骗赞，可是代码很有用啊，完美实现了想要的功能。敢问你不是利益相关，只是因为点赞飙升而发怒，是因为自己的项目被挤下去了吗？发出来爷卖了茅台去淘宝给你买赞

**Comment by WvvvWv** [comment]
> > 我要举报项目 [https://github.com/huanghyw/jd_seckill，](https://github.com/huanghyw/jd_seckill%EF%BC%8C)
> > 在1天时间内增加了近3000个star 和fork，
> > 按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
> > 我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
> > 难道他们真是程序员吗? 我是作不出你们这种违背良心的事情.
> > 打广告+骗赞。
> > 以后是人都可以通过你们这种渠道来骗赞了，
> > 请github 严肃对待， 以儆效尤
> > 就这样了， 不BB 了， 看官网怎么对待
> 
> 好好好，你说作者骗赞，可是代码很有用啊，完美实现了想要的功能。敢问你不是利益相关，只是因为点赞飙升而发怒，是因为自己的项目被挤下去了吗？发出来爷卖了茅台去淘宝给你买赞

杀猪诛心呢，哦不对，猪狗不如。hhh

**Comment by linyueb** [comment]
这二哈急了，不是黄牛就是脑子有问题

**Comment by lvjisong** [comment]
这傻逼如果不是黄牛，就很可能是倒卖脚本的，我认识一个就是搞了个工作室，买了脚本挂在服务器在抢，价格不菲，小白信用100分+plus会员105分的账号，抢购成功率90%这样，这样开源的项目肯定动了这种傻逼的蛋糕。

**Comment by Deckyu** [comment]
你是真🐶啊

**Comment by strivecheng** [comment]
> > 我要举报项目 [https://github.com/huanghyw/jd_seckill，](https://github.com/huanghyw/jd_seckill%EF%BC%8C)
> > 在1天时间内增加了近3000个star 和fork，
> > 按照中国12个小时在线的时间算， 每分钟就4个star ， 多么惊人的速度，
> > 我没有精力去查他们是否有作弊，但是作为一个程序员， 谁会去关注茅台这个商品，而且根本没有程序员能消费的起这件商品， 这显然是不合理的，
> > 难道他们真是程序员吗? 我是作不出你们这种违背良心的事情.
> > 打广告+骗赞。
> > 以后是人都可以通过你们这种渠道来骗赞了，
> > 请github 严肃对待， 以儆效尤
> > 就这样了， 不BB 了， 看官网怎么对待
> 
> 哈哈哈，就这？？？

英语估计还是百度翻译出来的，黄牛懂个锤子英语，哈哈哈

**Comment by LijieSong** [comment]
> 这种骗赞的项目都有， 程序员谁他妈的喝茅台， 我他妈的， 谁会关注茅台， 你这是给茅台打了广告还收了韭菜，中国SB 真多

真是个黄牛啊,谁说程序员不关注茅台了?程序员炒股的可不少,你只是你以为的吧?SB
SB黄牛不知道IT这个行业,就别来逼逼赖赖了.

**Comment by strivecheng** [comment]
> 哎呦， github 啥时候都人均喝茅台了 ， 比知乎都屌了

操你妈的傻逼，自己喝不起，以为别人也喝不起，穷逼。是不是影响到你脚本卖不出去了，被别人退款？傻逼，永远的loser。
估计天天被老板骂，只能到github上无能狂怒，操你妈的大傻逼！

**Comment by lzpaa** [comment]
傻逼你怎么不当场暴毙啊？动了你的蛋糕吗？你全家福就一个人
