### ISSUE TITLE
这个库已经涉及到广大黄牛的利益了吧，然后黄牛就来GitHub注册账号疯狂攻击此库！！！真的是应了马克思的名言

### ISSUE THREAD

**Issue by ChinaVolvocars** [huanghyw/jd_seckill#329]
资本逃避动乱和纷争，它的本性是胆怯的。这是真的，但还不是全部真理。资本害怕没有利润或利润太少，就象自然界害怕真空一样。一旦有适当的利润，资本就胆大起来。如果有10%的利润，它就保证到处被使用；有20%的利润，它就活跃起来；有50%的利润，它就铤而走险；为了100%的利润，它就敢践踏一切人间法律；有300%的利润，它就敢犯任何罪行，甚至冒绞首的危险。如果动乱和纷争能带来利润，它就会鼓励动乱和纷争。走私和贩卖奴隶就是证明！

**Comment by zhangyu13141H** [comment]
哈哈哈，谁信， 黄牛还懂github， 骗鬼呢？ 疯狂的攻击证据呢， 我就说了句， 你们打了广告， 还收割了大家的韭菜， 你是既得利益者， 我说错了？

**Comment by Mxiansheng** [comment]
> 哈哈哈，谁信， 黄牛还懂github， 骗鬼呢？ 疯狂的攻击证据呢， 我就说了句， 你们打了广告， 还收割了大家的韭菜， 你是既得利益者， 我说错了？

傻逼  人家哪里收割了你的韭菜

**Comment by Visbin** [comment]
> 哈哈哈，谁信， 黄牛还懂github， 骗鬼呢？ 疯狂的攻击证据呢， 我就说了句， 你们打了广告， 还收割了大家的韭菜， 你是既得利益者， 我说错了？

谁是韭菜？ 收割了谁？

**Comment by zhangyu13141H** [comment]
骗赞

**Comment by zhangyu13141H** [comment]
打了广告

**Comment by XiaoHb233** [comment]
> 打了广告

12月30号 新加入的，你居心何在

**Comment by money4marry** [comment]
> 哈哈哈，谁信， 黄牛还懂github， 骗鬼呢？ 疯狂的攻击证据呢， 我就说了句， 你们打了广告， 还收割了大家的韭菜， 你是既得利益者， 我说错了？

不知道你在说什么，既然你不关注茅台，为啥你会在这里？我们喝不喝茅台跟你是个睿智有什么关系？我们抢不抢茅台跟你是个蛇宝有什么关系？你在说什么？你是谁啊？

**Comment by zhangyu13141H** [comment]
我是关注trending 进来的， 谁他妈的管一瓶没价值的水

**Comment by Messdor** [comment]
> 我是关注trending 进来的， 谁他妈的管一瓶没价值的水

笑死我了，今天注册小号，就知道直接找trending找到进来，优秀啊

**Comment by zhangyu13141H** [comment]
我是有问题， 我是不想大号来干， 但是这并不能洗脱你们的问题

**Comment by zhangyu13141H** [comment]
不要转移话题， 一切起因都是因为你这个骗赞的行为导致的

**Comment by AsiaZhang123** [comment]
别理1314这个sb

**Comment by jason1314em** [comment]
这里不止一个黄牛，还有唱双簧的，甚至帮黄牛写CODE的都在，利益面前他们活的就像个汉奸

**Comment by Odimmsun** [comment]
> 哈哈哈，谁信， 黄牛还懂github， 骗鬼呢？ 疯狂的攻击证据呢， 我就说了句， 你们打了广告， 还收割了大家的韭菜， 你是既得利益者， 我说错了？

估计这就是个给黄牛写code的傻逼  现在这儿有个开源的了  他主子不用他的   傻逼东西卖不出去就在这儿狗急跳墙是吧   死妈东西有点脑子好不好   人家开源出来怎么打广告了？  打什么广告了？   打你妈死了的广告你才这么在这恶心人？

**Comment by cat-drink-coffe** [comment]
> 我是关注trending 进来的， 谁他妈的管一瓶没价值的水

真的是RZ，就问一句怎么骗赞了？怎么个骗法？傻狗一个

**Comment by BrilliantJ** [comment]
> 我是有问题， 我是不想大号来干， 但是这并不能洗脱你们的问题

人家赞多能把这疯狗气成这样？你懂github？赞是赞作者的代码，你把你大号代码发出来看看配不配赞
