### ISSUE TITLE
请问大佬们怎么同步时间

### ISSUE THREAD

**Issue by lixiangbin** [huanghyw/jd_seckill#330]
我这里一直提示与服务器时间相差1244毫秒，大概就1秒左右，这个是自动同步还是手动同步？

**Comment by Mr-Tommy** [comment]
![image](https://user-images.githubusercontent.com/16432614/103330226-806dd500-4a9b-11eb-8b46-acb2e5a64750.png)
![image](https://user-images.githubusercontent.com/16432614/103330249-9085b480-4a9b-11eb-9659-ae15b50022eb.png)

**Comment by XiaoHb233** [comment]
不知道同步的哪个接口
