### ISSUE TITLE
举报此项目地址， 有想法的去填吧

### ISSUE THREAD

**Issue by zhangyu13141H** [huanghyw/jd_seckill#333]
https://support.github.com/contact/report-abuse?category=report-abuse&report=huanghyw&report_id=7189743&report_type=user

**Comment by vito16** [comment]
瓜皮 ？

**Comment by sqz98700** [comment]
你是个SB吧？人家为了让我们和黄牛在同一起跑线。还是说你就是黄牛，你花钱找人开发或者买软件。影响到你利益？。

**Comment by zhangyu13141H** [comment]
我在和SB 们说一句， 我是孙子， 终结！！！

**Comment by AsiaZhang123** [comment]
> 你是个SB吧？人家为了让我们和黄牛在同一起跑线。还是说你就是黄牛，你花钱找人开发或者买软件。影响到你利益？。

他肯定是黄牛，来这无脑喷

**Comment by blackAzrael** [comment]
拿个小号 Joined 1 hour ago ？？？  影响到你们黄牛赚钱了是吧

**Comment by XiaoHb233** [comment]
可以举报你吗，就是为了抵制你这种人 🐮，作者才出的脚本

**Comment by Lance-404** [comment]
这人是傻逼，管那么多干嘛

**Comment by SabrinaLiii** [comment]
为啥要举报，没有什么必要啊，我也自己写过抢大众点评特权的脚本啊，感谢作者，哈哈哈

**Comment by cwl12** [comment]
已举报此人

**Comment by cat-drink-coffe** [comment]
> 已举报此人

在哪举报

**Comment by Auto-SK** [comment]
> https://support.github.com/contact/report-abuse?category=report-abuse&report=huanghyw&report_id=7189743&report_type=user

垃圾

**Comment by gitkeen** [comment]
https://support.github.com/contact/report-abuse?category=report-abuse&report=zhangyu13141H&report_id=76763712&report_type=user

**Comment by kangchangwei** [comment]
举报尼玛币  操你妈！狗东西  走路多长个眼  ！！！！贼

**Comment by mov1er** [comment]
黄🐂全家福只有一个人，兄弟们我说的没问题吧~

**Comment by gitkeen** [comment]
> > 已举报此人
> 
> 在哪举报

https://support.github.com/contact/report-abuse?category=report-abuse&report=zhangyu13141H&report_id=76763712&report_type=user

**Comment by TrustDec** [comment]
举报项目还不忘给自己fork一份😂

**Comment by strivecheng** [comment]
> 黄🐂全家福只有一个人，兄弟们我说的没问题吧~

说的对
