### ISSUE TITLE
eid和fp在服务器上怎么获取

### ISSUE THREAD

**Issue by TopScrew** [huanghyw/jd_seckill#334]
服务器上没有界面，怎么获取到eid和fp参数。或者说在其它设备获取到的eid和fp参数，能直接不修改在服务器上用吗

**Comment by XiaoHb233** [comment]
注意看博主的REDME

**Comment by TopScrew** [comment]
> eid和fp找个普通商品随便下单,然后抓包就能看到,这两个值可以填固定的
> 
> 随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台中输入变量_JdTdudfp，即可从输出的Json中获取eid和fp。
> 不会的话参考原作者的issue [zhou-xiaojun/jd_mask#22](https://github.com/zhou-xiaojun/jd_mask/issues/22)

我关注在一个地方获取的参数，能不能跨设备使用。这回答的啥

**Comment by luerdao** [comment]
同问

**Comment by Mr-Tommy** [comment]
> > eid和fp找个普通商品随便下单,然后抓包就能看到,这两个值可以填固定的
> > 随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台中输入变量_JdTdudfp，即可从输出的Json中获取eid和fp。
> > 不会的话参考原作者的issue [zhou-xiaojun/jd_mask#22](https://github.com/zhou-xiaojun/jd_mask/issues/22)
> 
> 我关注在一个地方获取的参数，能不能跨设备使用。这回答的啥

你试试不就知道了，非要别人喂你啊

**Comment by jxlyj007** [comment]
> 服务器上没有界面，怎么获取到eid和fp参数。或者说在其它设备获取到的eid和fp参数，能直接不修改在服务器上用吗

我也想知道~
