### ISSUE TITLE
不懂就问 config.ini的buy_time需要手动修改为抢购当天10:00吗

### ISSUE THREAD

**Issue by WuBin88996** [huanghyw/jd_seckill#335]
rt

**Comment by XiaoHb233** [comment]
要改

**Comment by Splinter1** [comment]
可以自己优化一下，先获取本地年月日，然后和抢购时间拼一下

**Comment by WuBin88996** [comment]
> 要改

你们是59开始运行程序吗 提前一分钟

**Comment by WuBin88996** [comment]
> 可以自己优化一下，先获取本地年月日，然后和抢购时间拼一下

你们是59开始运行程序吗 提前一分钟

**Comment by Mr-Tommy** [comment]
这个不改也行，打开就直接开始抢了，这个buy_time设置了之后是定时抢购，跑起来就不用自己管了

**Comment by WuBin88996** [comment]
> 这个不改也行，打开就直接开始抢了，这个buy_time设置了之后是定时抢购，跑起来就不用自己管了

懂了 谢谢带佬
