### ISSUE TITLE
换了京东账号后，eid 和fp没变是怎么回事啊？

### ISSUE THREAD

**Issue by SabrinaLiii** [huanghyw/jd_seckill#340]
我新登录了一个京东账号，但是eid 和fp没有改变，请问是怎么回事啊？？然后选择抢购也是我的账号名，请问是怎么回事啊，需要怎么解决呢？？

**Comment by applebest** [comment]
我也遇到了同样的情况，两个值没有变化，两个账户都是这两个值

**Comment by SabrinaLiii** [comment]
不知道是要换电脑还是清理cookie啊

**Comment by monthAndEclipse** [comment]
同一台机子得eid和fp是一样得

**Comment by luyehui** [comment]
换个浏览器就会变eid，fp估计你得换设备
