### ISSUE TITLE
抢购成功！

### ISSUE THREAD

**Issue by lany192** [huanghyw/jd_seckill#341]
10:00:02秒抢购成功，日志没有看到成功信息。等12:00:00微信上京东提醒付款，我才发现抢购成功了。注意：抢购结束几分钟后看看京东是否有待支付订单才能判断是否成功！

**Comment by lany192** [comment]
我改了默认UA和抢购数量

**Comment by Mr-Tommy** [comment]
> 我改了默认UA和抢购数量，还有抢购时间

UA改成哪个了

**Comment by lany192** [comment]
随便改，不要用默认的比较保险，万一京东针对这个UA进行封杀。变成别的，可以降低一些封杀的风险

**Comment by WuBin88996** [comment]
带佬 UA改成什么

**Comment by jxlyj007** [comment]
请问你的信用分是多少呀？综合分多少？

**Comment by lany192** [comment]
> 带佬 UA改成什么

修改UA只是我个人猜测。要改的话用自己电脑浏览器的UA就好了。不会获取去百度。

**Comment by lany192** [comment]
> 请问你的信用分是多少呀？综合分多少？

京享值 7千多，小白信用99.1

**Comment by jxlyj007** [comment]
> > 请问你的信用分是多少呀？综合分多少？
> 
> 京享值 7千多，小白信用99.1

大佬，我的PLUS综合分 103分，京享值 1903，小白信用 74.8 这个号有希望吗？

**Comment by AbbotterWang** [comment]
你好 可以私发我一份代码么 非常感谢！2533517259@qq.com

**Comment by MrQcc** [comment]
京享10万多，PLUS综合107，小白信用100.6，还是抢不到。。。
