### ISSUE TITLE
我早上差点错过了 9点59跑程序日志提示抢购失败12点京东APP提示我有未支付订单

### ISSUE THREAD

**Issue by cat-drink-coffe** [huanghyw/jd_seckill#347]
我早上差点错过了 9点59跑程序日志提示抢购失败12点京东APP提示我有未支付订单
这个怎么回事啊
![image](https://user-images.githubusercontent.com/50495357/103333819-2d4f4e80-4aaa-11eb-8158-ca64bdcaada2.png)

**Comment by pwy5150** [comment]
同问，我第一次手动抢的时候也是一样情况，只不过我是第二天才付的款

**Comment by cat-drink-coffe** [comment]
> 同问，我第一次手动抢的时候也是一样情况，只不过我是第二天才付的款

你这才牛 订单不是12小时取消么 ？我记错了？

**Comment by BrilliantJ** [comment]
看了全部的日志吗，一开始就抢成功的话后面不会停还在抢，后面显示的当然是失败的

**Comment by pwy5150** [comment]
> > 同问，我第一次手动抢的时候也是一样情况，只不过我是第二天才付的款
> 
> 你这才牛 订单不是12小时取消么 ？我记错了？

讲道理是的，我看它锁单是10:00:20.....我那会还在反复切出去抢购......

**Comment by jxlyj007** [comment]
请问你的信用分是多少呀？综合分多少？

**Comment by cat-drink-coffe** [comment]
> 请问你的信用分是多少呀？综合分多少？
综合分京享值？18908 信用 94.5

**Comment by cat-drink-coffe** [comment]
> 看了全部的日志吗，一开始就抢成功的话后面不会停还在抢，后面显示的当然是失败的

感觉可以优化
