### ISSUE TITLE
现在到处都在宣传大佬这个，建议大佬先删库避避风头吧

### ISSUE THREAD

**Issue by yhy666888** [huanghyw/jd_seckill#348]
RT，现在什么公众号、知乎、论坛都在传，说不好会造成麻烦，建议先稳一手

**Comment by pvzbjinput** [comment]
> RT，现在什么公众号、知乎、论坛都在传，说不好会造成麻烦，建议先稳一手

是费电了点

**Comment by cuijianzhe** [comment]
这些到处宣传的博主真是不嫌事大，为了自己那点破流量，事不关己高高挂起啊

**Comment by yhy666888** [comment]
> 这些到处宣传的博主真是不嫌事大，为了自己那点破流量，事不关己高高挂起啊

我在知乎看到那个，还打着github榜单的名号，发个文章整

**Comment by strivecheng** [comment]
> 这些到处宣传的博主真是不嫌事大，为了自己那点破流量，事不关己高高挂起啊

![image](https://user-images.githubusercontent.com/20623884/103340533-457d9880-4abf-11eb-8147-e8e844ded06b.png)
看到一个举报一个
这些傻逼自媒体，公众号真的恶心。tm天天自己没吊技术，就知道搞这些，一群司马玩意。
