### ISSUE TITLE
访问抢购订单结算页面有概率会抛异常

### ISSUE THREAD

**Issue by mengxr123** [huanghyw/jd_seckill#349]
访问抢购订单结算页面有概率会抛异常
改动前:
           self.session.get(url=url, params=payload, headers=headers)
改动后:
        self.session.get(url=url, params=payload, headers=headers, allow_redirects=False)

**Comment by desstiony** [comment]
直接提PR啊

**Comment by Mxiansheng** [comment]
我的代码里就是下面这种
self.session.get(url=url, params=payload, headers=headers, allow_redirects=False)

**Comment by mengxr123** [comment]
有两个  应该

> 我的代码里就是下面这种
> self.session.get(url=url, params=payload, headers=headers, allow_redirects=False)

前天下的代码
昨天第一次跑
跑到一半 抛出了以下异常
TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), respon

然后定位到问题改了后 今天早上跑没有问题 没出现异常。

刚才看了最新的代码的确这个地方改了，应该是做这两天之内作者改的。
