### ISSUE TITLE
今早抢茅台 链接没有失效但是出现了其他的问题

### ISSUE THREAD

**Issue by rost001** [huanghyw/jd_seckill#35]
![image](https://user-images.githubusercontent.com/36664434/102731870-04291280-4374-11eb-8e81-b5078503703e.png)
![image](https://user-images.githubusercontent.com/36664434/102731871-05f2d600-4374-11eb-94e7-3a60314062bd.png)
![image](https://user-images.githubusercontent.com/36664434/102731873-07240300-4374-11eb-9e38-7d88e9471fb0.png)

**Comment by huanghyw** [comment]
这个异常忽略就行，接口偶尔会返回html，所以解析json失败，没有拿到信息，会自动重试的
