### ISSUE TITLE
今天早上抢购，抢了两分钟都没有成功，但是我访问京东茅台页面竟然可以下单购买，这是jd的bug吧

### ISSUE THREAD

**Issue by mengxr123** [huanghyw/jd_seckill#350]

**Comment by Mr-Tommy** [comment]
应该不会吧，你成功下单了么，如果成功下单了，那就说明时抽签制的

**Comment by Mxiansheng** [comment]
我怎么不相信你在扯淡

**Comment by luyehui** [comment]
现在不是按快慢的吧，完全就是看号

**Comment by mengxr123** [comment]
> 我怎么不相信你在扯淡

骗你干嘛 你微信号多少 加我我给你发截图
我当时都惊呆了，到了下单页面 我选了两瓶，因为不相信是真的 然后手贱又退回到上一个页面，然后就变成了还有20几分钟后开始预约。

**Comment by Mxiansheng** [comment]
> > 我怎么不相信你在扯淡
> 
> 骗你干嘛 你微信号多少 加我我给你发截图
> 我当时都惊呆了，到了下单页面 我选了两瓶，因为不相信是真的 然后手贱又退回到上一个页面，然后就变成了还有20几分钟后开始预约。

你这不叫抢购成功了，我们都进到这个页面了，只不过是不能下单。

**Comment by luyehui** [comment]
订单页面谁都能进。。。问题你得进去付款界面，就算退出来了，还是会生成订单，你还是能付款的

**Comment by percyjie** [comment]
我信了

**Comment by mengxr123** [comment]
> > > 我怎么不相信你在扯淡
> > 
> > 
> > 骗你干嘛 你微信号多少 加我我给你发截图
> > 我当时都惊呆了，到了下单页面 我选了两瓶，因为不相信是真的 然后手贱又退回到上一个页面，然后就变成了还有20几分钟后开始预约。
> 
> 你这不叫抢购成功了，我们都进到这个页面了，只不过是不能下单。

问题是我那个茅台的画面
底下显示两个按钮 
【加入购物车】【立即购买】
我进到购买页面也改了地址还选来了两瓶，最终没付款而已，退出来重进茅台的画面，画面下方的按钮变成了【立即预约】

**Comment by mengxr123** [comment]
> > > > 我怎么不相信你在扯淡
> > > 
> > > 
> > > 骗你干嘛 你微信号多少 加我我给你发截图
> > > 我当时都惊呆了，到了下单页面 我选了两瓶，因为不相信是真的 然后手贱又退回到上一个页面，然后就变成了还有20几分钟后开始预约。
> > 
> > 
> > 你这不叫抢购成功了，我们都进到这个页面了，只不过是不能下单。
> 
> 问题是我那个茅台的画面
> 底下显示两个按钮
> 【加入购物车】【立即购买】
> 我进到购买页面也改了地址还选来了两瓶，最终没付款而已，退出来重进茅台的画面，画面下方的按钮变成了【立即预约】

早上10点1分我看没抢到就关了 ，，接着出去办事了  下午一点四十才回公司，回公司后我就开始查log，但是没有收到抢购成功这几个字。。所以才纳闷

**Comment by Mr-Tommy** [comment]
> > > > 我怎么不相信你在扯淡
> > > 
> > > 
> > > 骗你干嘛 你微信号多少 加我我给你发截图
> > > 我当时都惊呆了，到了下单页面 我选了两瓶，因为不相信是真的 然后手贱又退回到上一个页面，然后就变成了还有20几分钟后开始预约。
> > 
> > 
> > 你这不叫抢购成功了，我们都进到这个页面了，只不过是不能下单。
> 
> 问题是我那个茅台的画面
> 底下显示两个按钮
> 【加入购物车】【立即购买】
> 我进到购买页面也改了地址还选来了两瓶，最终没付款而已，退出来重进茅台的画面，画面下方的按钮变成了【立即预约】

最终提交的时候，会提示你库存不足，想要复现这个情况也很简单，PC端进入到宝贝详情，然后打开开发者工具，然后切换到移动端模式，刷新页面，快速点击立即购买，就行了，最后还是提交不了订单，服务端有验证的

**Comment by mengxr123** [comment]
> > > > > 我怎么不相信你在扯淡
> > > > 
> > > > 
> > > > 骗你干嘛 你微信号多少 加我我给你发截图
> > > > 我当时都惊呆了，到了下单页面 我选了两瓶，因为不相信是真的 然后手贱又退回到上一个页面，然后就变成了还有20几分钟后开始预约。
> > > 
> > > 
> > > 你这不叫抢购成功了，我们都进到这个页面了，只不过是不能下单。
> > 
> > 
> > 问题是我那个茅台的画面
> > 底下显示两个按钮
> > 【加入购物车】【立即购买】
> > 我进到购买页面也改了地址还选来了两瓶，最终没付款而已，退出来重进茅台的画面，画面下方的按钮变成了【立即预约】
> 
> 最终提交的时候，会提示你库存不足，想要复现这个情况也很简单，PC端进入到宝贝详情，然后打开开发者工具，然后切换到移动端模式，刷新页面，快速点击立即购买，就行了，最后还是提交不了订单，服务端有验证的

大佬你说的这个重现方式我试一下 ，学习学习。因为我回来看log返回的resultCode 百分之九十都是90016，想着是不是90016太多了 所以按概率我访问这个茅台页面他才会出现立即购买按钮

**Comment by Mr-Tommy** [comment]
> > > > > > 我怎么不相信你在扯淡
> > > > > 
> > > > > 
> > > > > 骗你干嘛 你微信号多少 加我我给你发截图
> > > > > 我当时都惊呆了，到了下单页面 我选了两瓶，因为不相信是真的 然后手贱又退回到上一个页面，然后就变成了还有20几分钟后开始预约。
> > > > 
> > > > 
> > > > 你这不叫抢购成功了，我们都进到这个页面了，只不过是不能下单。
> > > 
> > > 
> > > 问题是我那个茅台的画面
> > > 底下显示两个按钮
> > > 【加入购物车】【立即购买】
> > > 我进到购买页面也改了地址还选来了两瓶，最终没付款而已，退出来重进茅台的画面，画面下方的按钮变成了【立即预约】
> > 
> > 
> > 最终提交的时候，会提示你库存不足，想要复现这个情况也很简单，PC端进入到宝贝详情，然后打开开发者工具，然后切换到移动端模式，刷新页面，快速点击立即购买，就行了，最后还是提交不了订单，服务端有验证的
> 
> 大佬你说的这个重现方式我试一下 ，学习学习。因为我回来看log返回的resultCode 百分之九十都是90016，想着是不是90016太多了 所以按概率我访问这个茅台页面他才会出现立即购买按钮

我今天只有三个90008，其他都是90016，依然没抢到，明天再试试，如果京东还没改 规则的话
