### ISSUE TITLE
不太会py  ，请问显示找不到config.ini 怎么回事？我看明明有这个文件啊

### ISSUE THREAD

**Issue by zpx316** [huanghyw/jd_seckill#353]
![image](https://user-images.githubusercontent.com/43135201/103335998-c170e400-4ab1-11eb-91f8-334b7ef36370.png)
![image](https://user-images.githubusercontent.com/43135201/103336017-ce8dd300-4ab1-11eb-800a-70c8165615c9.png)

**Comment by koraLi** [comment]
五五开开挂石锤！

**Comment by BeanWei** [comment]
> 五五开开挂石锤！

+10086 😄

**Comment by 310168119** [comment]
有联系方式吗 +下我 威15151150714

**Comment by AbbotterWang** [comment]
你好 可以私发我一份代码么 非常感谢！2533517259@qq.com

**Comment by wutong98** [comment]
你下载库了吗
