### ISSUE TITLE
你们都是野生程序员吗，起码看看其他分支不就好了。。。。

### ISSUE THREAD

**Issue by xjblszyy** [huanghyw/jd_seckill#368]

**Comment by mrxiaozuo** [comment]
看破不说破

**Comment by woaihsw** [comment]
就你懂, 就你知道

你仔细想想为啥没人说这个各种爬墙项目的基本操作?

自己删了吧

**Comment by jingjxd** [comment]
唉……

**Comment by AbbotterWang** [comment]
求指教

**Comment by desstiony** [comment]
你觉得你怪聪明？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: AbbotterWang <notifications@github.com>
发送时间: Wednesday, December 30, 2020 3:48:19 PM
收件人: huanghyw/jd_seckill <jd_seckill@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [huanghyw/jd_seckill] 你们都是野生程序员吗，起码看看其他分支不就好了。。。。 (#368)


求指教

―

**Comment by desstiony** [comment]
🧠？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: . desstiony <desstiony@gmail.com>
发送时间: Wednesday, December 30, 2020 3:48:51 PM
收件人: huanghyw/jd_seckill <reply@reply.github.com>; huanghyw/jd_seckill <jd_seckill@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [huanghyw/jd_seckill] 你们都是野生程序员吗，起码看看其他分支不就好了。。。。 (#368)

你觉得你怪聪明？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: AbbotterWang <notifications@github.com>
发送时间: Wednesday, December 30, 2020 3:48:19 PM
收件人: huanghyw/jd_seckill <jd_seckill@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [huanghyw/jd_seckill] 你们都是野生程序员吗，起码看看其他分支不就好了。。。。 (#368)


求指教

**Comment by ldcr1319** [comment]
删掉吧

**Comment by wzhec** [comment]
秀智商

**Comment by C-racker** [comment]
很懂？

**Comment by taany6210** [comment]
快删了吧，知道的都没说，就你在这里说

**Comment by lllrrr2** [comment]
别自以为是好吧，快close吧

**Comment by MemoBook** [comment]
作为程序员，智商是够了，情商还差点

**Comment by yuliezhou** [comment]
就你懂, 就你知道

你仔细想想为啥没人说这个各种爬墙项目的基本操作?

自己删了吧

**Comment by fanyangyang188** [comment]
就你懂？

**Comment by strivecheng** [comment]
删啊，你对得起作者吗？
