### ISSUE TITLE
logger.info('抢购发生异常，稍后继续执行！', e) Message: '抢购发生异常，稍后继续执行！'

### ISSUE THREAD

**Issue by DwadeWoW** [huanghyw/jd_seckill#37]
这个message:抢购异常是正常的吗？  刚试了第一次，想问一下大神配置没什么问题吧，等明天继续冲！

![image](https://user-images.githubusercontent.com/49184852/102840188-44a09300-443d-11eb-8738-a2911e8ef2d6.png)
![image](https://user-images.githubusercontent.com/49184852/102840199-49fddd80-443d-11eb-906b-6bcf9056f07c.png)

**Comment by huanghyw** [comment]
这个异常是正常的，忽略就行。
只要能看见”很遗憾没有抢到“就证明配置程序都没问题，坚持下去就行了。

**Comment by DwadeWoW** [comment]
> 这个异常是正常的，忽略就行。
> 只要能看见”很遗憾没有抢到“就证明配置程序都没问题，坚持下去就行了。

好的谢谢！继续冲

**Comment by DwadeWoW** [comment]
> 这个异常是正常的，忽略就行。只要
> 能看见”很遗憾没有抢到“就证明配置程序都没问题，坚持下去就行了。”

可以一个电脑同时开几个项目来抢吗？我用两个号用两个浏览器登录，eid会变 但是fp不变，有影响吗？

**Comment by huanghyw** [comment]
只要是正常获取的eid和fp就没问题，有时候确实会重复，没影响

**Comment by dwordwu** [comment]
大佬，不同账户获取到的eid和fp，可以给另一个账号使用吗？

**Comment by huanghyw** [comment]
> 大佬，不同账户获取到的eid和fp，可以给另一个账号使用吗？

最好是每个账户获取一次
