### ISSUE TITLE
请国人不要滥用issues

### ISSUE THREAD

**Issue by jack9603301** [huanghyw/jd_seckill#370]
第一，该项目可能违反中国法律
第二，issues不是聊天公共频道，也不是留言板，是讨论问题、项目建议、bug反馈和特性请求的地方 请不要滥用issues

**Comment by lllrrr2** [comment]
关掉issues一周，就冷静下来了

**Comment by jack9603301** [comment]
不要养成这个习惯，对大家都不好，人家关注issues不是为了看灌水的，不仅仅是这个repo，在任何repo都不要这样做

**Comment by bienyur** [comment]
成贴吧了

**Comment by jack9603301** [comment]
可以开通评论区功能，想讨论去那边讨论

discussions

**Comment by jack9603301** [comment]
在issues不灌水是基本的素质
