### ISSUE TITLE
建议关闭Issue功能

### ISSUE THREAD

**Issue by JsonMa** [huanghyw/jd_seckill#380]
@huanghyw 强烈建议关闭issue功能！！

**Comment by koraLi** [comment]
+1

**Comment by mengxr123** [comment]
关了吧

**Comment by lianjiangwei** [comment]
@huanghyw 赶紧关了吧，否则那些心术不正的人会害了你的

**Comment by desstiony** [comment]
是该关了，傻逼太多

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: mengxr123 <notifications@github.com>
发送时间: Wednesday, December 30, 2020 4:17:29 PM
收件人: huanghyw/jd_seckill <jd_seckill@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [huanghyw/jd_seckill] 建议关闭Issue功能 (#380)


关了吧

―

**Comment by zpp0318** [comment]
@huanghyw 关闭issue吧 大佬

**Comment by LockiJiang** [comment]
+1

**Comment by cg-llc** [comment]
+1

**Comment by MikasaAAAckerman** [comment]
@huanghyw  老哥，关闭issue吧
