### ISSUE TITLE
已下载，免费分享，来个懂python基础的，教下我怎么运行这个东西，纯小白，完全不会呀

### ISSUE THREAD

**Issue by laosiji666888** [huanghyw/jd_seckill#381]

**Comment by smileeleven** [comment]
> _No description provided._

分享一下代码可好？

**Comment by OldCaptain** [comment]
1181020958@qq.com  能发我一份么  我运行下

**Comment by MicahKong** [comment]
2482051126，加我，给你运行

**Comment by 310168119** [comment]
QQ 310168119 加我下

**Comment by vinsent** [comment]
qq 2252750458, 求一份, 好奇心

**Comment by yueyesky** [comment]
求分享   85147829@qq.com

**Comment by cuisongliu** [comment]
卧槽 你们都不会切分支么。。。

**Comment by 495806109** [comment]
> 卧槽你们都不会切分支么。。。

差不多得了，不明白作者的苦心

**Comment by jk852** [comment]
1101078778@qq.com     求分享啊，只是看了，还没下

**Comment by Linchi-s** [comment]
能分享一下嘛，想学习学习

**Comment by dingpengqiang** [comment]
1692303173@qq.com求分享

**Comment by OldCaptain** [comment]
> 卧槽 你们都不会切分支么。。。
哈哈哈哈

**Comment by pwy5150** [comment]
> 卧槽 你们都不会切分支么。。。

别说了

**Comment by Jaykcy** [comment]
> > 卧槽 你们都不会切分支么。。。
> 
> 别说了

就是过滤这些人的
