### ISSUE TITLE
bug。。没法使用

### ISSUE THREAD

**Issue by zhuobl** [huanghyw/jd_seckill#387]

**Comment by desstiony** [comment]
看，这又来一个傻逼，来秀智商

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zhuobl <notifications@github.com>
发送时间: Wednesday, December 30, 2020 4:26:49 PM
收件人: huanghyw/jd_seckill <jd_seckill@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [huanghyw/jd_seckill] 兄弟，你的master分支还在呢！！ (#387)


―

**Comment by wupeaking** [comment]
懂得人自然懂，能不说破吗？

**Comment by JunzhouLiu** [comment]
啊 别这样，这是自我保护机制。

**Comment by xiong0317** [comment]
SB，看破不说破

**Comment by BobGeek** [comment]
我以为我来晚了，master和main有啥区别？

**Comment by dakun666** [comment]
牛逼啊兄弟，眼真尖！，你不说我都没瞅见

**Comment by JunzhouLiu** [comment]
@zhuobl 直接删除本条issues。。。
![image](https://user-images.githubusercontent.com/17582066/103339507-80ca9800-4abc-11eb-9b18-bb489481d93d.png)

**Comment by TimorYang** [comment]
@zhuobl  快去删了
