### ISSUE TITLE
运行后执行预约，显示的预约成功，但是在手机端并没有显示已预约

### ISSUE THREAD

**Issue by 0xffan** [huanghyw/jd_seckill#4]

**Comment by huanghyw** [comment]
执行预约成功只代表成功触发了预约动作，并不说明一定预约成功。是否预约成功因素很多，这里不做具体判断。

**Comment by XiaoHb233** [comment]
> 执行预约成功只代表成功触发了预约动作，并不说明一定预约成功。是否预约成功因素很多，这里不做具体判断。
这个只能抢购不加车模式的吧，茅台不是只能app下单吗

**Comment by YiChuan0712** [comment]
一直都是抢购链接获取失败，请问有什么可能的原因吗

**Comment by XiaoHb233** [comment]
> 一直都是抢购链接获取失败，请问有什么可能的原因吗

你的商品不是抢购商品

**Comment by huanghyw** [comment]
还有一种情况就是没有秒到。有些商品秒完了就切换成普通商品，这时候就会显示获取秒杀链接失败。很难秒到的，运气好就是赚到了。
