### ISSUE TITLE
只能用扫码登陆了？生成的那张图扫不出来啊。填cookie也不能用了

### ISSUE THREAD

**Issue by sscccccc** [huanghyw/jd_seckill#40]

**Comment by huanghyw** [comment]
看一下你的二维码什么样子

**Comment by huanghyw** [comment]
还有，操作系统是什么？

**Comment by sscccccc** [comment]
> 看一下你的二维码什么样子

![qr_code](https://user-images.githubusercontent.com/43920457/102886523-36c82d80-4490-11eb-8d75-8124b7b1b881.png)

**Comment by sscccccc** [comment]
> > 看一下你的二维码什么样子
> 
> ![qr_code](https://user-images.githubusercontent.com/43920457/102886523-36c82d80-4490-11eb-8d75-8124b7b1b881.png)

发上来居然能扫了

**Comment by sscccccc** [comment]
> 还有，操作系统是什么？



> 看一下你的二维码什么样子

解决了，原因是我用win10自带的照片工具查看，那张二维码扫不出来。用画图打开图片就能扫了
