### ISSUE TITLE
get_seckill_url 获取抢购商品连接的时候 url 为空

### ISSUE THREAD

**Issue by tsinghua520** [huanghyw/jd_seckill#43]
大佬 抢购的时候报错，这块的获取抢购商品链接有问题

**Comment by huanghyw** [comment]
不支持购物车下单抢购的商品

**Comment by tsinghua520** [comment]
意思是只要该商品能够加入购物车， 就不支持是嘛

**Comment by huanghyw** [comment]
是的，加购物车的动作有时候在点预约按钮，有时候在点抢购按钮。
这程序目前就用来抢茅台吧，其他的抢购支持回头有空了再瞧瞧。
