### ISSUE TITLE
预约商品抢购获取抢购链接失败

### ISSUE THREAD

**Issue by kxtMy** [huanghyw/jd_seckill#46]
一直都失败，没有成功过
![image](https://user-images.githubusercontent.com/16443007/102953424-3a00ff00-450c-11eb-8e76-9f034ad3a4f8.png)

**Comment by huanghyw** [comment]
目前不支持需要进购物车的抢购商品

**Comment by kxtMy** [comment]
这个不需要进购物车啊。。。

**Comment by huanghyw** [comment]
可以手动走一下流程，点预约和抢购按钮后，看下购物车里面有没有这款商品

**Comment by huanghyw** [comment]
这款商品我点击抢购之后就让我去购物车结算了
![image](https://user-images.githubusercontent.com/7189743/102954262-0a52f680-450e-11eb-8c4c-c2a38d8bed76.png)

**Comment by huanghyw** [comment]
类似这种商品目前都是不支持的，每天十点钟抢抢茅台吧 :)

**Comment by kxtMy** [comment]
看到了，确实进了购物车。。之前我是从手机点的，就没看到购物车这个。。那支持购物车结算实现会很麻烦吗

**Comment by huanghyw** [comment]
不想花太多时间加新功能了，完善下茅台抢购，现在茅台多香啊。
等以后有时间了搞搞购物车这种。

**Comment by kxtMy** [comment]
我能说显卡也挺香的吗。。一块rtx3060ti加价至少500，一块rtx3080加价800

**Comment by huanghyw** [comment]
是吗，那也不错。
再等等吧，最近比较忙，等一月份抽时间搞搞。
