### ISSUE TITLE
eip和fp是啥意思呢  抢购茅台需要填写吗  重新登录会变吗

### ISSUE THREAD

**Issue by NickTet** [huanghyw/jd_seckill#47]
eip和fp是啥意思呢  抢购茅台需要填写吗  重新登录会变吗

**Comment by huanghyw** [comment]
说实话我也不知道京东那这两个值干什么，但是下单的时候订单里面需要。
配置一次就行，后面这两个值可能会变，但是不改也没啥问题。
如果不放心可以定期的在配置文件里面更新一下。

**Comment by NickTet** [comment]
好的 谢谢
