### ISSUE TITLE
抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】

### ISSUE THREAD

**Issue by leipeng101** [huanghyw/jd_seckill#48]
这个错误是怎么回事？ 我京东有多个收货地址，同时也有默认地址。

2020-12-23 11:01:34,818 - 18980-MainThread - D:\jd_seckill\jd_spider_requests.py[line:576] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】
2020-12-23 11:01:34,819 - 18980-MainThread - D:\jd_seckill\jd_spider_requests.py[line:478] - INFO: 访问抢购订单结算页面...
2020-12-23 11:01:34,878 - 16608-MainThread - D:\jd_seckill\jd_spider_requests.py[line:576] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】
2020-12-23 11:01:34,879 - 16608-MainThread - D:\jd_seckill\jd_spider_requests.py[line:478] - INFO: 访问抢购订单结算页面...
2020-12-23 11:01:34,884 - 18276-MainThread - D:\jd_seckill\jd_spider_requests.py[line:521] - INFO: 生成提交抢购订单所需参数...
2020-12-23 11:01:34,891 - 18276-MainThread - D:\jd_seckill\jd_spider_requests.py[line:496] - INFO: 获取秒杀初始化信息...
2020-12-23 11:01:34,974 - 13204-MainThread - D:\jd_seckill\jd_spider_requests.py[line:576] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】

**Comment by huanghyw** [comment]
检查下配置是否正确

**Comment by leipeng101** [comment]
配置如下：
我是用来抢显卡的，不是茅台酒。但是抢购过程一样。

**Comment by huanghyw** [comment]
根据大家反馈，目前是不支持抢购显卡的，显卡的抢购都需要进购物车

**Comment by leipeng101** [comment]
不用进购物车的，也是 直接抢购的商品。

**Comment by huanghyw** [comment]
商品id提供下，我看看

**Comment by leipeng101** [comment]
100015285144

**Comment by huanghyw** [comment]
现在抢不了了，您明天试下。用电脑登录，点击抢购，看看会不会进到购物车。

**Comment by leipeng101** [comment]
嗯，好的 我改天再试试 。感谢！

**Comment by wzphood** [comment]
今天茅台同样出现这个问题了

**Comment by huanghyw** [comment]
> 今天茅台同样出现这个问题了

所有订单都无法提交吗？

**Comment by wzphood** [comment]
> > 今天茅台同样出现这个问题了
> 
> 所有订单都无法提交吗？

前5次成功获取链接了，之后都失败，返回:【'addressList'】

**Comment by huanghyw** [comment]
只要能成功获取就代表程序或者配置没问题，这个返回咱们也控制不了，是京东接口给返回的。

**Comment by huanghyw** [comment]
最关键的是抢购茅台的日志里面要有很遗憾的返回，如果一次都没有，那可能就是有问题了

**Comment by wzphood** [comment]
> 最关键的是抢购茅台的日志里面要有很遗憾的返回，如果一次都没有，那可能就是有问题了

一个很遗憾都没有。。

**Comment by huanghyw** [comment]
那不对啊

**Comment by huanghyw** [comment]
配置贴上来看看

**Comment by wzphood** [comment]
[config]
# eid, fp参数必须填写，具体请参考 wiki-常见问题
# 随意填写可能导致订单无法提交等问题
eid = "7R7SAZI6QBDOMRJ5HVLHNC56KR6QOVGEWEPRKNUPN7E7VYUUAZ5E35PEH3DZJFWC2IGSXFIAA4W35LXQYUJPMMHHZY"
fp = "cf444b28435d7167e31dcdfd842f9c98"
# cookie
#cookies_String = "__jdu=1586273021865136663377; shshshfpa=1d79a82c-037d-8e4e-47cb-e35d2f9e66ae-1586273130; shshshfpb=ypTYIktPFs89QK5nxn8nGIw%3D%3D; ceshi3.com=201; unpl=V2_ZzNtbRYHRxZ1X0EBfktdDGIDEFoSUhccJlxHXHNOWAQ3V0YJclRCFnQUR1BnGlQUZwQZWEdcQRBFCEdkeB5fA2AFEFlBZxpFK0oYEDlNDEY1WnxdRF9DFnEAR1B9KWwGZzMSXHJXRxxyC0BWehpcDGAHEl9FUEQXdw5AZEsebDVXARpZR1NHJXQ4R2Q5TQAFbgUQXA9XRxxyC0BWehpcDGAHEl9FUEQXdw5AZHopXw%3d%3d; __jdv=76161171|haosou-search|t_262767352_haosousearch|cpc|1791259057_0_ea521f6d4c084136a4e8be099f50aeee|1590741875314; areaId=20; user-key=e7b2ce43-c8ea-498b-aa14-1d72ba811c3b; TrackID=14zpGGB-OpJ4mkipibzlKLH_cntpvRWi1YuLUjQQ9V-kkhdgGNzIYgnDptMlqfJhNhu8ozJ_qMXppTXszcg6uSBKf3xsYTd9LGMPVWn_V3mfk98AjllQ77oNoZNf0vk_n; pinId=tnz4f2JFgMgyIVQ1is9ieg; pin=275466402_m; unick=%E4%B8%8D%E6%83%B3%E8%B7%91%E6%AD%A5%E7%9A%84%E5%B9%B2%E9%94%85%E9%94%85; _tp=hbuicMy40IDnjEA3yKCYJg%3D%3D; _pst=275466402_m; __jda=122270672.1586273021865136663377.1586273022.1590741875.1590853863.6; __jdc=122270672; shshshfp=4502485e8b520f53be89fe44a27717ee; 3AB9D23F7A4B3C9B=XMKWG35OFYBQN3C5JYD7J4FNOWNXSGBIZNIKBUVVQEMJW6766KKTNYZD43U3Y7VCWA73EEWJRCOTKU7QVG3WKUNNQA; cn=14; ipLoc-djd=20-1761-25188-51466.2052701265; ipLocation=%u5e7f%u897f; __tak=c94559a7e3893645ee7f9f3ba3af391b4381d8e935b4895cf5f4df48e014c4aca54c30a40df88a95e670fcf3ef153823cfc92c013e7e892133119c9f79811f1b9303c52b4dffffebb6b145cbe13fc0e0; thor=A3006E40DFDA6A23E9353F8A5BE5D7B526D907891A33D2D63A28B4F6F19DC6F67E8BAA1251F8FC51DA54936D111277AEF79F42D5BBCA8C7F01068EA42B4B681CF3D78B4CB73DF9E870791980E609BABE4426FF4EF4089405842C640217A10FEC30256F6BC66C63C67D595F08AE093A375782F916DE74D980FE9E18720F2D5987B03269FB13DC923CCCEC51A5FD7155FD; shshshsID=b122acc455c4e500fe48a45f327cbeac_17_1590855792368; __jdb=122270672.25.1586273021865136663377|6.1590853863"
# 商品id，已经是茅台的sku_id了100012043978
sku_id = 100012043978
# 设定时间 # 2020-12-09 10:00:00.100000
buy_time = 2020-12-24 09:59:59.9500
# 默认UA
DEFAULT_USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
# 是否使用随机 useragent，默认为 false
random_useragent = false


今天没有登录就自动开始了，不知道是不是这个问题

**Comment by huanghyw** [comment]
没登录自动开始没关系，说明cookie还没有失效

**Comment by huanghyw** [comment]
这个配置看着没问题

**Comment by huanghyw** [comment]
这个配置文件看着不全，直接截图吧，粘贴上来都乱了

**Comment by huanghyw** [comment]
再把日志放上来看看

**Comment by wzphood** [comment]
![Uploading BOE[VZ5(A2%XO07~X2D`N`K.png…]()

**Comment by huanghyw** [comment]
配置目前看来是正常的，还有一种可能是被风控了，虽然cookie没有完全失效，但是不能获取订单信息。
在程序开始抢购之后不要用电脑端登录京东，想看有没有抢到可以手机端查看。

明天把项目里面那个cookie文件删除，重新登录之后抢购。

日志保留好。
