### ISSUE TITLE
这个报错是怎么回事呢大佬

### ISSUE THREAD

**Issue by CangShui** [huanghyw/jd_seckill#49]
图片：
![102955497-04aae000-4511-11eb-82f6-b4cdbb84565a](https://user-images.githubusercontent.com/28698760/102956047-5acc5300-4512-11eb-9fab-b5b055628114.png)

日志：
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
时间到达，开始执行……
时间到达，开始执行……
时间到达，开始执行……
时间到达，开始执行……
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
访问抢购订单结算页面...
访问抢购订单结算页面...
访问抢购订单结算页面...
访问抢购订单结算页面...
时间到达，开始执行……
生成提交抢购订单所需参数...
获取秒杀初始化信息...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
生成提交抢购订单所需参数...
获取秒杀初始化信息...
生成提交抢购订单所需参数...
获取秒杀初始化信息...
生成提交抢购订单所需参数...
获取秒杀初始化信息...
访问抢购订单结算页面...
生成提交抢购订单所需参数...

**Comment by huanghyw** [comment]
主要两种情况：
1、不支持购物车下单商品
2、瞬间就没秒光了，没抢到

**Comment by wzphood** [comment]
显卡货一次就一两个，瞬间就没了

**Comment by huanghyw** [comment]
这么少，感觉比茅台还难抢

**Comment by CangShui** [comment]
> 主要两种情况：
> 1，不支持购物车下单商品
> 2，瞬间就没秒光了，没抢到

也就是说这个截图里的报错是正常现象对么，大佬

**Comment by huanghyw** [comment]
是的，忽略吧，显卡不好抢
