### ISSUE TITLE
请问大佬提交订单有没有判断是否使用虚拟资产,特别是有红包的时候.会导致订单提交失败的问题.

### ISSUE THREAD

**Issue by sea0302** [huanghyw/jd_seckill#50]
请问大佬提交订单有没有判断是否使用虚拟资产,特别是有红包的时候.会导致订单提交失败的问题.使用虚拟资产,特别是有红包的时候会要求输入支付密码的问题.

**Comment by huanghyw** [comment]
目前还不支持虚拟资产的使用，后续加一下

**Comment by sea0302** [comment]
@huanghyw 那目前来说,在抢购前必须要把红包使用完才行,要不然会卡在支付密码那里.京东目前还不能默认关闭不使用红包的功能

**Comment by huanghyw** [comment]
这个还好加，我已经加上了，您更新下代码

**Comment by sea0302** [comment]
@huanghyw 非常感谢

**Comment by huanghyw** [comment]
客气了
