### ISSUE TITLE
Mac报了个错

### ISSUE THREAD

**Issue by zhankezhong** [huanghyw/jd_seckill#51]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_spider_requests import JdSeckill
  File "/Users/xxxxxx/Desktop/jd_seckill/jd_spider_requests.py", line 105
    def __init__(self, spider_session: SpiderSession):
                                     ^

**Comment by huanghyw** [comment]
日志太少了，多来点

**Comment by zhankezhong** [comment]
脚本可以了 是python环境问题
但是还是有个问题需要请教 怎么抓取 eid和fp  
<img width="786" alt="image" src="https://user-images.githubusercontent.com/3145434/103050110-6c733080-45ce-11eb-8c2f-69522101fc4f.png">

**Comment by huanghyw** [comment]
这两个值readme中有描述如何获取

**Comment by zhankezhong** [comment]
如图 response里貌似是经过加密的  console里都是错误  所以没搞明白怎么取

**Comment by huanghyw** [comment]
> 如图 response里貌似是经过加密的 console里都是错误 所以没搞明白怎么取

随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台中输入变量_JdTdudfp，即可从输出的Json中获取eid和fp。

**Comment by zhankezhong** [comment]
明白了  谢了大佬  下个月账号限购解除  再来试试 抢到请你喝咖啡

**Comment by huanghyw** [comment]
好嘞，等你好消息

**Comment by stormspirit055** [comment]
我也碰到了类似问题 怎么解决呢
```python
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_spider_requests import JdSeckill
  File "/Users/wcq/Desktop/jd_seckill/jd_spider_requests.py", line 105
    def __init__(self, spider_session: SpiderSession):
                                     ^
SyntaxError: invalid syntax
```

**Comment by huanghyw** [comment]
> 我也碰到了类似问题 怎么解决呢
> 
> ```python
> Traceback (most recent call last):
>   File "main.py", line 3, in <module>
>     from jd_spider_requests import JdSeckill
>   File "/Users/wcq/Desktop/jd_seckill/jd_spider_requests.py", line 105
>     def __init__(self, spider_session: SpiderSession):
>                                      ^
> SyntaxError: invalid syntax
> ```

忽略就行，会自动重试

**Comment by stormspirit055** [comment]
> > 我也碰到了类似问题 怎么解决呢
> > ```python
> > Traceback (most recent call last):
> >   File "main.py", line 3, in <module>
> >     from jd_spider_requests import JdSeckill
> >   File "/Users/wcq/Desktop/jd_seckill/jd_spider_requests.py", line 105
> >     def __init__(self, spider_session: SpiderSession):
> >                                      ^
> > SyntaxError: invalid syntax
> > ```
> 
> 忽略就行，会自动重试

自动重试啥意思....不好意思 我没搞过python 我重新执行 还是一样

**Comment by huanghyw** [comment]
会自动重新请求服务器

**Comment by zhankezhong** [comment]
mac自带的是python2.7 再装个python3

**Comment by 181279934** [comment]
> > 如响应里里似似是经过加密的console里都是错误所以没搞明白怎么取
> 
> 随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台中输入变量_JdTdudfp，可以从输出的Json中获取eid和fp。

新手，这部可以更详细点么？谢谢

**Comment by thisleo** [comment]
应该是python运行环境的问题，Mac上默认是装的python2，如果直接运行应该是用的python2 运行的，你要指定python3运行，例如：python3 main.py

**Comment by forging2012** [comment]
python3 main.py
