### ISSUE TITLE
关于抢购时间设置

### ISSUE THREAD

**Issue by isomatical** [huanghyw/jd_seckill#52]
请问库主，是不是需要根据本地时间和京东服务器上的差值时间相应地修改config里的抢购时间。还是说抢购时间为默认的09:59:59.500即可？有没有什么好的建议呢？

**Comment by huanghyw** [comment]
正常设置时间就行，抢购开始时间是多少就设置多少，差值是自动计算的。
在设置的时候可以提前500毫秒。
