### ISSUE TITLE
OSError: [Errno 22] Invalid argument: './cookies/jd_661*****84322.cookies'

### ISSUE THREAD

**Issue by ZRT-1998** [huanghyw/jd_seckill#53]
我已经完全按照使用要求去做了,但是出现了这个问题
![图片](https://user-images.githubusercontent.com/34241963/103001495-14094800-4568-11eb-93ed-a5662c053682.png)

**Comment by huanghyw** [comment]
之前windows试过我的账号倒是没问题，这个问题会不会是因为用户名有星号导致的？

**Comment by huanghyw** [comment]
目前cookies缓存文件名称用的是京东用户昵称

**Comment by ZRT-1998** [comment]
确实是这个原因.我修改了昵称就好了

**Comment by huanghyw** [comment]
看来还不能用昵称当做用户名，回头调整下这块
