### ISSUE TITLE
pip install到lxml时报错

### ISSUE THREAD

**Issue by MingDemon411** [huanghyw/jd_seckill#54]
Running setup.py install for lxml ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ariesrol\appdata\local\programs\python\python39-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AriesRol\\AppData\\Local\\Temp\\pip-install-3doynbj7\\lxml_00fac900b9fb445c84d95364d2289dfe\\setup.py'"'"'; __file__='"'"'C:\\Users\\AriesRol\\AppData\\Local\\Temp\\pip-install-3doynbj7\\lxml_00fac900b9fb445c84d95364d2289dfe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\AriesRol\AppData\Local\Temp\pip-record-g3n62hjs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ariesrol\appdata\local\programs\python\python39-32\Include\lxml'
         cwd: C:\Users\AriesRol\AppData\Local\Temp\pip-install-3doynbj7\lxml_00fac900b9fb445c84d95364d2289dfe\
    Complete output (74 lines):
    Building lxml version 4.5.1.
    Building without Cython.
    Building against pre-built libxml2 andl libxslt libraries
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.9
    creating build\lib.win32-3.9\lxml
    copying src\lxml\builder.py -> build\lib.win32-3.9\lxml
    copying src\lxml\cssselect.py -> build\lib.win32-3.9\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win32-3.9\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win32-3.9\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win32-3.9\lxml
    copying src\lxml\sax.py -> build\lib.win32-3.9\lxml
    copying src\lxml\usedoctest.py -> build\lib.win32-3.9\lxml
    copying src\lxml\_elementpath.py -> build\lib.win32-3.9\lxml
    copying src\lxml\__init__.py -> build\lib.win32-3.9\lxml
    creating build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win32-3.9\lxml\includes
    creating build\lib.win32-3.9\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win32-3.9\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win32-3.9\lxml\html
    creating build\lib.win32-3.9\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win32-3.9\lxml\isoschematron
    copying src\lxml\etree.h -> build\lib.win32-3.9\lxml
    copying src\lxml\etree_api.h -> build\lib.win32-3.9\lxml
    copying src\lxml\lxml.etree.h -> build\lib.win32-3.9\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win32-3.9\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\__init__.pxd -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win32-3.9\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win32-3.9\lxml\includes
    creating build\lib.win32-3.9\lxml\isoschematron\resources
    creating build\lib.win32-3.9\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win32-3.9\lxml\isoschematron\resources\rng
    creating build\lib.win32-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl
    creating build\lib.win32-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win32-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
  Rolling back uninstall of lxml
  Moving to c:\users\ariesrol\appdata\local\programs\python\python39-32\lib\site-packages\lxml-4.6.2.dist-info\
   from C:\Users\AriesRol\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\~xml-4.6.2.dist-info
  Moving to c:\users\ariesrol\appdata\local\programs\python\python39-32\lib\site-packages\lxml\
   from C:\Users\AriesRol\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\~xml
ERROR: Command errored out with exit status 1: 'c:\users\ariesrol\appdata\local\programs\python\python39-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AriesRol\\AppData\\Local\\Temp\\pip-install-3doynbj7\\lxml_00fac900b9fb445c84d95364d2289dfe\\setup.py'"'"'; __file__='"'"'C:\\Users\\AriesRol\\AppData\\Local\\Temp\\pip-install-3doynbj7\\lxml_00fac900b9fb445c84d95364d2289dfe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\AriesRol\AppData\Local\Temp\pip-record-g3n62hjs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ariesrol\appdata\local\programs\python\python39-32\Include\lxml' Check the logs for full command output.

如上，我自己也在百度过并且从网上下载了lxml本地安装之后也报错，想问下大佬是什么情况

**Comment by ZRT-1998** [comment]
可以把lxml的版本换高一点,在request.txt中修改一下

**Comment by wzphood** [comment]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":
要装c++，就搜Microsoft C++ Build Tools就行

**Comment by huanghyw** [comment]
windows装个依赖还挺麻烦的

**Comment by MingDemon411** [comment]
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":
> 要装c++，就搜Microsoft C++ Build Tools就行

好的 不过我改了配置文件里lxml版本号之后也就能运行了，不知道这样对不对

**Comment by MingDemon411** [comment]
> windows装个依赖还挺麻烦的

是哦

**Comment by MingDemon411** [comment]
> windows装个依赖还挺麻烦的

有点哦

**Comment by Lstoryc** [comment]
> > error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":
> > 要装c++，就搜Microsoft C++ Build Tools就行
> 
> 好的 不过我改了配置文件里lxml版本号之后也就能运行了，不知道这样对不对

请问改了啥版本？我也遇到相同问题了
