### ISSUE TITLE
你好，土豆，问三个问题

### ISSUE THREAD

**Issue by lvtu1124** [huanghyw/jd_seckill#55]
1.获取抢购链接我要.8秒以后才会获取成功，请问你遇到没
2.获取秒杀初始化信息，返回null，请问知道什么原因吗
3.请问一下，可以同一个账号跑多个账号不

**Comment by huanghyw** [comment]
1. 我一般是1秒以上才能获取到，这次同步京东时间上线后看看这个问题有没有改善
1. 这个是京东接口返回数据异常，会自动重试，可以忽略
1. 同一个账号理论上可以多开，但是我没这么搞过

**Comment by lvtu1124** [comment]
就是请问同一个浏览器多个账号的eid，fp都一样，请问你解决了吗

**Comment by huanghyw** [comment]
> 就是请问同一个浏览器多个账号的eid，fp都一样，请问你解决了吗

我确实注意到有这个情况，以为这就是京东的生成逻辑，不清楚这两个值干什么用的。
您对这两个值有什么研究没？

**Comment by lvtu1124** [comment]
eid貌似可有可无，fp是浏览器特征值，我家里人的只敢多个浏览器，然后抓一次换一个ip

**Comment by lvtu1124** [comment]
代理ip太慢了，可是直接一个ip或者一个浏览器，多个账号一样，怕黑，

**Comment by huanghyw** [comment]
有办法在程序里面拿到fp的值吗？

**Comment by lvtu1124** [comment]
没办法，就是浏览器签名，我都怀疑可以随便生成给京东了

**Comment by huanghyw** [comment]
我还没找到这个值的生成逻辑，回头再研究研究

**Comment by lvtu1124** [comment]
问一下，秒杀初始化一直null，请问可以提前获取吗，78个null，货早没了

**Comment by lvtu1124** [comment]
方便加一下微信吗，traveller_fuding

**Comment by huanghyw** [comment]
有啥问题直接提issues吧，沟通可以通过邮箱 :)

从代码逻辑上来讲，提前获取信息是可以的，但是这个不符合用户正常使用流程，容易被风控识别出来。

**Comment by lvtu1124** [comment]
好的

**Comment by lvtu1124** [comment]
土豆，再问一个问题：pool.submit(self.seckill)这个多进程里面调用的方法里面使用loger.info都无效是为什么，print正常

**Comment by huanghyw** [comment]
有效吧，比如这两个日志都能正常打印

![image](https://user-images.githubusercontent.com/7189743/103045759-b9e8a100-45c0-11eb-8964-523c2379b514.png)

**Comment by huanghyw** [comment]
这两个不会是同一个问题吧？ #56
