### ISSUE TITLE
想请教个问题，不知道是不是bug

### ISSUE THREAD

**Issue by MingDemon411** [huanghyw/jd_seckill#56]
[如图，我想测试个商品看能不能提示抢购成功之类的信息，这里修改了sku和时间（已经存入cookie）。运行代码之后到了设置时间没有任何提示不知道是有没有出什么问题。在主页上看到说抢购非茅台商品会出现问题，但不知道这里的问题是不是符合作者说的。
![捕获](https://user-images.githubusercontent.com/48229057/103010451-4bf49900-4530-11eb-9376-57e5c53ab557.PNG)

**Comment by huanghyw** [comment]
输入2，按回车然后就没任何动静了吗？

**Comment by huanghyw** [comment]
配置文件贴出来看下

**Comment by MingDemon411** [comment]
> 输入2，按回车然后就没任何动静了吗？

嗯嗯

**Comment by MingDemon411** [comment]
> 配置文件贴出来看下

![Uploading QQ截图20201223232253.png…]()

**Comment by huanghyw** [comment]
> 配置文件贴出来看下

图片看不了，貌似传失败了

**Comment by MingDemon411** [comment]
> > 配置文件贴出来看下
> 
> 图片看不了，貌似传失败了

我再传一遍

**Comment by huanghyw** [comment]
还有，您用的是什么系统？

**Comment by MingDemon411** [comment]
> > 配置文件贴出来看下
> 
> 图片看不了，貌似传失败了

![QQ截图20201223232253](https://user-images.githubusercontent.com/48229057/103045831-ecbd7580-457d-11eb-8e92-317f2083a8c0.png)

**Comment by MingDemon411** [comment]
> 还有，您用的是什么系统？

Windows 10 20H2

**Comment by MingDemon411** [comment]
> 还有，您用的是什么系统？

我用python自带的IDLE运行之后就毫无反应，但我用cmd运行之后可以顺利显示信息.
![QQ截图20201224085253](https://user-images.githubusercontent.com/48229057/103047232-bf26fb00-4582-11eb-9bd3-d59726583cbd.png)
![QQ截图20201224085350](https://user-images.githubusercontent.com/48229057/103047247-c3ebaf00-4582-11eb-8cf8-95ba56ab49ee.png)

**Comment by huanghyw** [comment]
还有这问题呢，是说windows下不能再pycharm里面运行吗？
我回头找个环境试试。

**Comment by MingDemon411** [comment]
> 还有这问题呢，是说windows下不能再pycharm里面运行吗？
> 我回头找个环境试试。

嗯嗯 感谢
