### ISSUE TITLE
抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

### ISSUE THREAD

**Issue by qdkxh** [huanghyw/jd_seckill#57]
你好，土豆
一直是出现这个抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
请问是什么意思，什么原因导致的

**Comment by qdkxh** [comment]
**### 显示抢购失败后还有一直循环出现下面的信息**
抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
2020-12-24 10:00:01,644 - 5408-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:478] - INFO: 访问抢购订单结算页面...
2020-12-24 10:00:01,675 - 2824-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:521] - INFO: 生成提交抢购订单所需参数...
2020-12-24 10:00:01,675 - 2824-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:496] - INFO: 获取秒杀初始化信息...
2020-12-24 10:00:01,714 - 12680-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:577] - INFO: 抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】

**Comment by isomatical** [comment]
同样出现了这个问题，另外借楼问一句，为什么抢购没准点进行，大概10点08分才执行第一次抢购。

**Comment by qdkxh** [comment]
我出现了很多次
2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
resultCode：90016出现的频率比90008高一点点

**Comment by huanghyw** [comment]
【抢购失败，返回信息:null】
这个是京东接口没有返回信息，忽略就行，会自动重试

**Comment by huanghyw** [comment]
> 我出现了很多次
> 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> resultCode：90016出现的频率比90008高一点点

对于90016和90008在readme中有一些猜测

**Comment by sherry1900** [comment]
抢购时间需要更改么，比如提前一秒？

**Comment by huanghyw** [comment]
现在时间同步了，要不要提前无所谓了

**Comment by hnxzc** [comment]
> 我出现了很多次
> 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> resultCode：90016出现的频率比90008高一点点

我的90016占75%，90008占25%

**Comment by huanghyw** [comment]
> > 我出现了很多次
> > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > resultCode：90016出现的频率比90008高一点点
> 
> 我的90016占75%，90008占25%

那预估你的小白信用在90以上

**Comment by isomatical** [comment]
> > > 我出现了很多次
> > > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > resultCode：90016出现的频率比90008高一点点
> > 
> > 
> > 我的90016占75%，90008占25%
> 
> 那预估你的小白信用在90以上

小白信用就是京东plus综合分吗，我105分，但统计得到的结果是90016占68%。

**Comment by huanghyw** [comment]
> > > > 我出现了很多次
> > > > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > > resultCode：90016出现的频率比90008高一点点
> > > 
> > > 
> > > 我的90016占75%，90008占25%
> > 
> > 
> > 那预估你的小白信用在90以上
> 
> 小白信用就是京东plus综合分吗，我105分，但统计得到的结果是90016占68%。

不是的，这是两个分数

**Comment by hnxzc** [comment]
> > > 我出现了很多次
> > > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > resultCode：90016出现的频率比90008高一点点
> > 
> > 
> > 我的90016占75%，90008占25%
> 
> 那预估你的小白信用在90以上

京享值20000+，信誉星级5星，Plus综合分106，小白信用98.9，刚才发邮件给你了：）

**Comment by huanghyw** [comment]
> > > > 我出现了很多次
> > > > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > > resultCode：90016出现的频率比90008高一点点
> > > 
> > > 
> > > 我的90016占75%，90008占25%
> > 
> > 
> > 那预估你的小白信用在90以上
> 
> 京享值20000+，信誉星级5星，Plus综合分106，小白信用98.9，刚才发邮件给你了：）

要是小白信用能上100，90008的占比能低到个位数

**Comment by huanghyw** [comment]
90008占比越低，越有机会参与真正的抢购

**Comment by qdkxh** [comment]
> > > > > 我出现了很多次
> > > > > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > > > resultCode：90016出现的频率比90008高一点点
> > > > 
> > > > 
> > > > 我的90016占75%，90008占25%
> > > 
> > > 
> > > 那预估你的小白信用在90以上
> > 
> > 
> > 京享值20000+，信誉星级5星，Plus综合分106，小白信用98.9，刚才发邮件给你了：）
> 
> 要是小白信用能上100，90008的占比能低到个位数

怎么看90016和90008的出现的百分比，看控制台的输出再统计次数手动算吗？

**Comment by huanghyw** [comment]
对，手动统计的。目前这个百分比的含义也只是猜测。

**Comment by isomatical** [comment]
> > > > > > 我出现了很多次
> > > > > > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > > > > resultCode：90016出现的频率比90008高一点点
> > > > > 
> > > > > 
> > > > > 我的90016占75%，90008占25%
> > > > 
> > > > 
> > > > 那预估你的小白信用在90以上
> > > 
> > > 
> > > 京享值20000+，信誉星级5星，Plus综合分106，小白信用98.9，刚才发邮件给你了：）
> > 
> > 
> > 要是小白信用能上100，90008的占比能低到个位数
> 
> 怎么看90016和90008的出现的百分比，看控制台的输出再统计次数手动算吗？

用pychram或vscode打开那个log文件，然后ctrl+F 搜索90008和90016

**Comment by qdkxh** [comment]
> > > > > > > 我出现了很多次
> > > > > > > 2020-12-24 10:00:19,059 - 6136-MainThread - D:\pythonProject\jd_seckill-master\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
> > > > > > > resultCode：90016出现的频率比90008高一点点
> > > > > > 
> > > > > > 
> > > > > > 我的90016占75%，90008占25%
> > > > > 
> > > > > 
> > > > > 那预估你的小白信用在90以上
> > > > 
> > > > 
> > > > 京享值20000+，信誉星级5星，Plus综合分106，小白信用98.9，刚才发邮件给你了：）
> > > 
> > > 
> > > 要是小白信用能上100，90008的占比能低到个位数
> > 
> > 
> > 怎么看90016和90008的出现的百分比，看控制台的输出再统计次数手动算吗？
> 
> 用pychram或vscode打开那个log文件，然后ctrl+F 搜索90008和90016

谢谢，没看到有个日志文件。我90016有80%+的概率

**Comment by qdkxh** [comment]
> 90008占比越低，越有机会参与真正的抢购

大佬，请问buy_time时间设置在多少比较好啊？

**Comment by qdkxh** [comment]
> > 90008占比越低，越有机会参与真正的抢购
> 
> 大佬，请问buy_time时间设置在多少比较好啊？

我是设置在这个时间：09:59:59.500，有没有问题

**Comment by huanghyw** [comment]
可以，提前0.5秒就行

**Comment by BeyondRyan** [comment]
> 你好，土豆
> 一直是出现这个抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】
> 请问是什么意思，什么原因导致的

楼主问题解决了吗
