### ISSUE TITLE
今天抢购助手感觉有些问题

### ISSUE THREAD

**Issue by sea0302** [huanghyw/jd_seckill#58]
首先是抢购链接获取失败，稍后自动重试,需要获取很多次,而且出现了90016和90008同时出现了.昨天未修改前没出现这个问题,详见截图.
![QQ图片20201224100643](https://user-images.githubusercontent.com/32325218/103051200-38e5d580-45d1-11eb-8df6-836ded8b18ba.png)

**Comment by huanghyw** [comment]
抢购链接获取失败，稍后自动重试
说明京东抢购链接还没有放出来，所以获取失败

90016和90008同时出现是正常的，我对于这两个值分析详见readme

**Comment by hnxzc** [comment]
一直是这样的

**Comment by huanghyw** [comment]
> 一直是这样的

是抢购的茅台吗？

**Comment by hnxzc** [comment]
> > 一直是这样的
> 
> 是抢购的茅台吗？

是抢茅台，每天都要到01秒才能取到抢购链接，我觉得这个没问题

**Comment by huanghyw** [comment]
> > > 一直是这样的
> > 
> > 
> > 是抢购的茅台吗？
> 
> 是抢茅台，每天都要到01秒才能取到抢购链接，我觉得这个没问题

哦，那就是了，正常的，京东链接放的晚

**Comment by ZRT-1998** [comment]
而且没有抢购成功的提示

**Comment by huanghyw** [comment]
可以自己配置一下server酱，成功失败都会有消息推送。

我觉得最方便的还是手机登录查看有没有待付款订单，一分钟内没有基本上就是没有了。
