### ISSUE TITLE
初始化信息token

### ISSUE THREAD

**Issue by luojiaqi1** [huanghyw/jd_seckill#59]
hello大神，请问初始化信息中需要的token是用来干什么的？可以不取吗？谢谢。

**Comment by huanghyw** [comment]
说的是哪个地方？来个截图看看

**Comment by luojiaqi1** [comment]
<img width="622" alt="Screen Shot 2020-12-24 at 11 14 56 AM" src="https://user-images.githubusercontent.com/25439439/103056958-6c2c6280-45d9-11eb-93b3-4fb0bcab3a4e.png">


> 说的是哪个地方？来个截图看看

<img width="622" alt="Screen Shot 2020-12-24 at 11 14 56 AM" src="https://user-images.githubusercontent.com/25439439/103056981-79495180-45d9-11eb-809d-443ad7df8188.png">

token 取了放在data里面的～

**Comment by huanghyw** [comment]
这个不能不取，下单的时候需要提供给京东接口的
