### ISSUE TITLE
抢购链接获取失败，稍后自动重试

### ISSUE THREAD

**Issue by wzphood** [huanghyw/jd_seckill#6]
抢购的商品获取不了链接
发现cookies发生了改变，多了shshshfpa，是这个导致的吗

**Comment by huanghyw** [comment]
如果能日志输出能看见自己的用户名就不是cookie的问题。
获取链接失败一般是这两种情况：
1、可能是需要添加购物车才能秒杀的商品
2、秒杀未开始或者已经结束了。

**Comment by 354621693** [comment]
我感觉有这个问题是不是购物车中商品数量过多导致的，默认情况下5个线程各自+1进入购物车，最快的那个线程提交订单的时候，其他线程加购物车已经成功了（jd购物车是一个全局变量之类的设计），这时候提交订单，数量是5个，那么对于限购1个的商品，是不是就拿不到url了呢？

**Comment by wzphood** [comment]
> 我感觉有这个问题是不是购物车中商品数量过多导致的，默认情况下5个线程各自+1进入购物车，最快的那个线程提交订单的时候，其他线程加购物车已经成功了（jd购物车是一个全局变量之类的设计），这时候提交订单，数量是5个，那么对于限购1个的商品，是不是就拿不到url了呢？

我上午抢茅台是能得到链接的，下午显卡就不能了。不过显卡是在放购物车里了，下次我从购物车移除试试

**Comment by 354621693** [comment]
> > 我感觉有这个问题是不是购物车中商品数量过多导致的，默认情况下5个线程各自+1进入购物车，最快的那个线程提交订单的时候，其他线程加购物车已经成功了（jd购物车是一个全局变量之类的设计），这时候提交订单，数量是5个，那么对于限购1个的商品，是不是就拿不到url了呢？
> 
> 我上午抢茅台是能得到链接的，下午显卡就不能了。不过显卡是在放购物车里了，下次我从购物车移除试试

对我感觉也有这个问题，然后我觉得是不是他可能对手机端跟电脑端的抢购是有一个业务场景的区分？比如说用手机端抢购的时候，它是可以直接在商品页面跳转到下单页面，然而在用电脑网页抢购的时候，它是会会先加入一个购物车里面，再去结算，如果下单之前购物车里面已经有这些商品，我发现他有五个线程在工作的情况下，即使是抢购失败，拿不到抢购链接的情况下，这个商品的数量还是加了五个。或者是抢购的时候，购物车里面没有这件商品，会比较容易拿到链接

**Comment by huanghyw** [comment]
目前不支持需要加购物车方式的抢购

**Comment by wzphood** [comment]
> 目前不支持需要加购物车方式的抢购

是只要能添加进购物车的都不行吗？好多抢购都是能直接提交也能购物车提交

**Comment by matthkewk** [comment]
logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
我是这个提示。。一直循环

**Comment by huanghyw** [comment]
> > 目前不支持需要加购物车方式的抢购
> 
> 是只要能添加进购物车的都不行吗？好多抢购都是能直接提交也能购物车提交

对的，目前这个还不支持，后续可能会加入这个功能

**Comment by huanghyw** [comment]
> logger.info('抢购发生异常，稍后继续执行！', e)
> Message: '抢购发生异常，稍后继续执行！'
> 我是这个提示。。一直循环

首选确认配置文件正确配置。
还有问题就是接口返回数据异常，正常应该是json，但是返回了html。估计是并发过高，触发了接口的熔断机制。忽略就行，程序会自己重试。
