### ISSUE TITLE
你好 我这种不会Python的咋用这个程序呢？

### ISSUE THREAD

**Issue by Xzw111222** [huanghyw/jd_seckill#60]
已经拉了代码，安装好了`` requirements.txt``。
但在订单结算页面获取``eid``和``fp``时，打印不出来。
我控制台是这样输的 你看对不对：
https://cdn.jsdelivr.net/gh/Xzw111222/MyImages/imgs/jd.png

**Comment by ZRT-1998** [comment]
交点学费，手把手远程教你

**Comment by jingjxd** [comment]
多刷新几次结算页面再试试，输入的没问题

**Comment by Xzw111222** [comment]
``js_spider_requests.py``文件里面 ``logger``和``requests``函数报错，需要安装他们吗？

**Comment by huanghyw** [comment]
> `js_spider_requests.py`文件里面 `logger`和`requests`函数报错，需要安装他们吗？

requirements.txt 安装了依赖就都装好了

**Comment by Xzw111222** [comment]
好的。都配置的差不多了，可以運行。感謝大家的回復。最後想問一下這個程序是掃了二維碼之後就開始運行的是吧，那可以在10點之前就讓他運行起嗎？

**Comment by huanghyw** [comment]
我一般提前十分钟

**Comment by Xzw111222** [comment]
好的，谢谢！！！！

**Comment by a123478we** [comment]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_spider_requests import JdSeckill
  File "/Users/zhangxu/Desktop/jd_seckill-master/jd_spider_requests.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
