### ISSUE TITLE
关于限购

### ISSUE THREAD

**Issue by ZRT-1998** [huanghyw/jd_seckill#61]
一个月最多买2瓶吗？
能不能在同一台电脑上给我的家人购买？
京东有封号机制吗？

**Comment by huanghyw** [comment]
封号机制肯定有，不过具体什么逻辑不清楚。

我试过在同一台电脑两个账号下抢过两笔单，都成功了。
但是从第三单开始就不好抢了，可能是小白信用比较低，还有可能就是触发风控了。
不过目前还没有被封号。

**Comment by huanghyw** [comment]
还需要注意京东对于同一个账号的定义，见茅台商品详情页。
