### ISSUE TITLE
pip更新第三方库时报错

### ISSUE THREAD

**Issue by NewLi123** [huanghyw/jd_seckill#63]
Running setup.py install for lxml ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python39\jd_seckill-master\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Li\\AppData\\
Local\\Temp\\pip-install-9zopjqki\\lxml_dade571e863643c0aa9bab25eb3fb6f3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Li\\AppData\\Local\\Temp\\pip-install-9z
opjqki\\lxml_dade571e863643c0aa9bab25eb3fb6f3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'
"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Li\AppData\Local\Temp\pip-record-hrbbzmsx\install-record.tx
t' --single-version-externally-managed --compile --install-headers 'c:\python39\jd_seckill-master\venv\include\site\python3.9\lxml'
         cwd: C:\Users\Li\AppData\Local\Temp\pip-install-9zopjqki\lxml_dade571e863643c0aa9bab25eb3fb6f3\
    Complete output (74 lines):
    Building lxml version 4.5.1.
    Building without Cython.
    Building against pre-built libxml2 andl libxslt libraries
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\lxml
    copying src\lxml\builder.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\cssselect.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\sax.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\_elementpath.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\__init__.py -> build\lib.win-amd64-3.9\lxml
    creating build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win-amd64-3.9\lxml\html
    creating build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\etree.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\etree_api.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\__init__.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\
iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso
-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\x
sl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\
resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\i
so-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematro
n-xslt1
    running build_ext
    building 'lxml.etree' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-
tools/
    ----------------------------------------
  Rolling back uninstall of lxml
  Moving to c:\python39\jd_seckill-master\venv\lib\site-packages\lxml-4.6.2.dist-info\
   from C:\Python39\jd_seckill-master\venv\Lib\site-packages\~xml-4.6.2.dist-info
  Moving to c:\python39\jd_seckill-master\venv\lib\site-packages\lxml\
   from C:\Python39\jd_seckill-master\venv\Lib\site-packages\~xml
ERROR: Command errored out with exit status 1: 'c:\python39\jd_seckill-master\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0
] = '"'"'C:\\Users\\Li\\AppData\\Local\\Temp\\pip-install-9zopjqki\\lxml_dade571e863643c0aa9bab25eb3fb6f3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Li\\App
Data\\Local\\Temp\\pip-install-9zopjqki\\lxml_dade571e863643c0aa9bab25eb3fb6f3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.r
ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Li\AppData\Local\Temp\pip-
record-hrbbzmsx\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python39\jd_seckill-master\venv\include\site\pytho
n3.9\lxml' Check the logs for full command output.

已尝试默认设置安装https://visualstudio.microsoft.com/visual-cpp-build-tools/后依然上述报错

**Comment by huanghyw** [comment]
win下装这个库貌似有点坎坷，您参考下这个：#54，实在不行去wsl里面跑

**Comment by sea0302** [comment]
> Running setup.py install for lxml ... error
> ERROR: Command errored out with exit status 1:
> command: 'c:\python39\jd_seckill-master\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Li\AppData\
> Local\Temp\pip-install-9zopjqki\lxml_dade571e863643c0aa9bab25eb3fb6f3\setup.py'"'"'; **file**='"'"'C:\Users\Li\AppData\Local\Temp\pip-install-9z
> opjqki\lxml_dade571e863643c0aa9bab25eb3fb6f3\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'
> "'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Li\AppData\Local\Temp\pip-record-hrbbzmsx\install-record.tx
> t' --single-version-externally-managed --compile --install-headers 'c:\python39\jd_seckill-master\venv\include\site\python3.9\lxml'
> cwd: C:\Users\Li\AppData\Local\Temp\pip-install-9zopjqki\lxml_dade571e863643c0aa9bab25eb3fb6f3
> Complete output (74 lines):
> Building lxml version 4.5.1.
> Building without Cython.
> Building against pre-built libxml2 andl libxslt libraries
> running install
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-3.9
> creating build\lib.win-amd64-3.9\lxml
> copying src\lxml\builder.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\cssselect.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\sax.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml_elementpath.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml__init__.py -> build\lib.win-amd64-3.9\lxml
> creating build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes__init__.py -> build\lib.win-amd64-3.9\lxml\includes
> creating build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\builder.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\clean.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\defs.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\diff.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html_diffcommand.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html_html5builder.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html_setmixin.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html__init__.py -> build\lib.win-amd64-3.9\lxml\html
> creating build\lib.win-amd64-3.9\lxml\isoschematron
> copying src\lxml\isoschematron__init__.py -> build\lib.win-amd64-3.9\lxml\isoschematron
> copying src\lxml\etree.h -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\etree_api.h -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes__init__.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.9\lxml\includes
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
> copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
> copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
> copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
> iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso
> -schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\x
> sl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron
> resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\i
> so-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematro
> n-xslt1
> running build_ext
> building 'lxml.etree' extension
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-
> tools/
> ----------------------------------------
> Rolling back uninstall of lxml
> Moving to c:\python39\jd_seckill-master\venv\lib\site-packages\lxml-4.6.2.dist-info
> from C:\Python39\jd_seckill-master\venv\Lib\site-packages~xml-4.6.2.dist-info
> Moving to c:\python39\jd_seckill-master\venv\lib\site-packages\lxml
> from C:\Python39\jd_seckill-master\venv\Lib\site-packages~xml
> ERROR: Command errored out with exit status 1: 'c:\python39\jd_seckill-master\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0
> ] = '"'"'C:\Users\Li\AppData\Local\Temp\pip-install-9zopjqki\lxml_dade571e863643c0aa9bab25eb3fb6f3\setup.py'"'"'; **file**='"'"'C:\Users\Li\App
> Data\Local\Temp\pip-install-9zopjqki\lxml_dade571e863643c0aa9bab25eb3fb6f3\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.r
> ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Li\AppData\Local\Temp\pip-
> record-hrbbzmsx\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python39\jd_seckill-master\venv\include\site\pytho
> n3.9\lxml' Check the logs for full command output.
> 
> 已尝试默认设置安装[https://visualstudio.microsoft.com/visual-cpp-build-tools/后依然上述报错](https://visualstudio.microsoft.com/visual-cpp-build-tools/%E5%90%8E%E4%BE%9D%E7%84%B6%E4%B8%8A%E8%BF%B0%E6%8A%A5%E9%94%99)

我之前是在win10的企业版上安装和你一样的问题,折腾了很久,最好我是安装的4.6.2的版本.
你试试这个看是否能安装
pip install lxml==4.5.1 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

**Comment by sea0302** [comment]
还不行就网上找4.6.2版本安装,我安装的是4.6.2的

**Comment by DLwyp** [comment]
换清华源试试 pip install xxxx -i https://pypi.tuna.tsinghua.edu.cn/simple
