### ISSUE TITLE
大佬，我看他们群里说京东今天晚上8点更新了。大佬特别佩服你的技术，想跟你学技术。

### ISSUE THREAD

**Issue by wg512063479** [huanghyw/jd_seckill#67]

**Comment by wg512063479** [comment]
如果可以的话，联系我一下：512063479@qq.com

**Comment by huanghyw** [comment]
我也是在别人的代码基础上修改的，互相学习。
有问题在这沟通就行，这里的大佬更多。

**Comment by wg512063479** [comment]
大佬，如果不在抢购的时间，应该如何进行抓包来获取请求呢？？

**Comment by huanghyw** [comment]
只能在抢购的那么一会时间里面进行抓包，过了这段时间就不行了

**Comment by wg512063479** [comment]
好的，谢谢，大佬。

**Comment by huanghyw** [comment]
客气了

**Comment by zlf0308** [comment]
8点更新什么了？

**Comment by wg512063479** [comment]
> 8点更新什么了？

这个我也不知道，我有一个用软件抢购的群。昨天8点不接单，他说作者在进行更新呢，11点更新完的。。我就很懵，抢购还没开始怎么进行更新的。

**Comment by wg512063479** [comment]
> 客气了

大佬，你什么时候能建一个交流群。大家一起交流那种。。我是做大数据的，就因为抢茅台学的python，抓包，，自己也尝试写了，但是没有你的代码的这种思路有的地方抓包 抓的不明白

**Comment by huanghyw** [comment]
不建群了吧，有问题再Issues沟通挺好的，新来的人都能看见。
再说现在功能也少，就一个抢购茅台，等以后功能真的多了可以考虑建群的事情。

**Comment by wg512063479** [comment]
好的，持续关注。如果建群时候我第一个加入。

**Comment by huanghyw** [comment]
> 好的，持续关注。如果建群时候我第一个加入。

好嘞

**Comment by wg512063479** [comment]
![1608882474(1)](https://user-images.githubusercontent.com/58841370/103127268-0c62b400-46cc-11eb-8a5b-e113fd9be2b3.jpg)
1、这个图片中的 第一个红标是我点击抢购，抓包时候抓到请求url，这个url之前的请求是我没抓到么？？点击请求直接抓到了divide。下面进行了替换是什么意思呢。

![1608883832(1)](https://user-images.githubusercontent.com/58841370/103127359-606d9880-46cc-11eb-91d7-c5ef809547db.jpg)
2、这个提交的时候的sku_id，这个咱们不是在配置中写死的么？为什么要出初始化中来进行获取呢。
抢购和提交这两个方法看的有点懵

**Comment by zhuimingzhenbai202** [comment]
大佬，请问怎么获取eid和fp呢 不太会

**Comment by huanghyw** [comment]
> ![1608882474(1)](https://user-images.githubusercontent.com/58841370/103127268-0c62b400-46cc-11eb-8a5b-e113fd9be2b3.jpg)
> 1、这个图片中的 第一个红标是我点击抢购，抓包时候抓到请求url，这个url之前的请求是我没抓到么？？点击请求直接抓到了divide。下面进行了替换是什么意思呢。
> 
> ![1608883832(1)](https://user-images.githubusercontent.com/58841370/103127359-606d9880-46cc-11eb-91d7-c5ef809547db.jpg)
> 2、这个提交的时候的sku_id，这个咱们不是在配置中写死的么？为什么要出初始化中来进行获取呢。
> 抢购和提交这两个方法看的有点懵

1、减少一次302跳转，根据规律直接生成url
2、常用变量就在ini声明出来了，后面直接用，不用再get了

**Comment by huanghyw** [comment]
> 大佬，请问怎么获取eid和fp呢 不太会

readme里面有说明
