### ISSUE TITLE
请教一下问题

### ISSUE THREAD

**Issue by Lich3nbo** [huanghyw/jd_seckill#69]
我在开始抢购十分钟之前 打开了脚本输入了 2
然后提示正在等待
![image](https://user-images.githubusercontent.com/27914486/103114210-b7f21100-4698-11eb-9589-598c0cf1168f.png)
到了十点的时候 我发现脚本还是正在等待 
按了下回车 脚本开始跑了
![image](https://user-images.githubusercontent.com/27914486/103114278-e8d24600-4698-11eb-8259-624815bb5ab9.png)
之后就打印的是这些日志 

请问下大佬 怎么样才能到点自动抢购
不需要按回车

**Comment by huanghyw** [comment]
提前十分钟运行程序，输入2之后直接按回车，到达指定之间后会自动运行

**Comment by sea0302** [comment]
> 提前十分钟运行程序，输入2之后直接按回车，到达指定之间后会自动运行

生成提交抢购订单所需参数...这个是什么呢?

**Comment by huanghyw** [comment]
> > 提前十分钟运行程序，输入2之后直接按回车，到达指定之间后会自动运行
> 
> 生成提交抢购订单所需参数...这个是什么呢?

去京东接口拿地址、token等下单需要填写的信息

**Comment by Lich3nbo** [comment]
> 提前十分钟运行程序，输入2之后直接按回车，到达指定之间后会自动运行

感谢

**Comment by Lich3nbo** [comment]
> > > 提前十分钟运行程序，输入2之后直接按回车，到达指定之间后会自动运行
> > 
> > 
> > 生成提交抢购订单所需参数...这个是什么呢?
> 
> 去京东接口拿地址、token等下单需要填写的信息

大佬帮忙看一下我选了1之后报错  会不会影响 选项2 的 抢购

**Comment by Lich3nbo** [comment]
![image](https://user-images.githubusercontent.com/27914486/103122834-f1d50e80-46bc-11eb-931c-ca143b7440b0.png)


> > > 提前十分钟运行程序，输入2之后直接按回车，到达指定之间后会自动运行
> > 
> > 
> > 生成提交抢购订单所需参数...这个是什么呢?
> 
> 去京东接口拿地址、token等下单需要填写的信息

![image](https://user-images.githubusercontent.com/27914486/103122838-f699c280-46bc-11eb-88df-c06a1b31de61.png)

**Comment by huanghyw** [comment]
预约就报错吗？电脑上可以进行预约吗？

**Comment by Lich3nbo** [comment]
> 预约就报错吗？电脑上可以进行预约吗？

电脑上还没试过  ，手机上可以

**Comment by Lich3nbo** [comment]
> 预约就报错吗？电脑上可以进行预约吗？

刚试了下 可以预约

**Comment by Lich3nbo** [comment]
> 预约就报错吗？电脑上可以进行预约吗？

试了下 PC页面上可以预约 
昨天我是手机预约

**Comment by huanghyw** [comment]
从异常上来看是链接超时了，确认下网络环境是否稳定
