### ISSUE TITLE
咨询一个时间问题

### ISSUE THREAD

**Issue by rcfan1** [huanghyw/jd_seckill#74]
9:59:59:500定时启动，可是一直显示抢购链接获取失败，稍后自动重试，直到10:00:01,451才获取到抢购链接。
![QQ截图20201225111147](https://user-images.githubusercontent.com/69945315/103116806-b1689700-46a2-11eb-9fc3-3b44b1ce9751.png)

        咨询一下这个是因为京东开放链接晚的原因，还是我时间设置问题，还是我网络问题导致的啊，因为10:00:01才获取到链接的话，想要抢到的可能性几乎没有了。

**Comment by hnxzc** [comment]
京东放的晚

**Comment by rcfan1** [comment]
谢谢大佬回复，明白了，明天继续
