### ISSUE TITLE
Sever酱调用代码，用浏览器驱动会不会影响抢购速度？

### ISSUE THREAD

**Issue by ZRT-1998** [huanghyw/jd_seckill#76]
import time

# 引入selenium库中的 webdriver 模块
from selenium import webdriver

driver = webdriver.Chrome()
driver.implicitly_wait(5)
driver.get("https://sc.ftqq.com/XXX.send?text=抢购成功！~")

**Comment by huanghyw** [comment]
这种方式太慢了，直接python里面get请求就行

**Comment by ZRT-1998** [comment]
requests.get("https://sc.ftqq.com/XXX.send?text=抢购成功！~")

**Comment by huanghyw** [comment]
![image](https://user-images.githubusercontent.com/7189743/103124851-1385c400-46c4-11eb-84a2-b28f96f96074.png)

**Comment by ZRT-1998** [comment]
我在抢购时没有收到这个函数的返回

**Comment by huanghyw** [comment]
send_wechat这个函数？这个没有return

**Comment by ZRT-1998** [comment]
在配置里面填写了，微信没有推消息给我

**Comment by huanghyw** [comment]
抢购成功了没有收到消息？

**Comment by ZRT-1998** [comment]
是的

**Comment by huanghyw** [comment]
配置看下

**Comment by ZRT-1998** [comment]
![Uploading 图片.png…]()

**Comment by huanghyw** [comment]
知道什么问题了，上次调整代码的时候把这块给漏了，稍等，我一会修复一下

**Comment by huanghyw** [comment]
我刚才以为上次代码漏改了，本地试了下可以正常发微信。
还是把您的配置贴上来把，刚才上传的图片看不见，应该是传失败了。

**Comment by ZRT-1998** [comment]
[messenger]
# 使用了Server酱的推送服务
# 如果想开启下单成功后消息推送，则将 enable 设置为 true，默认为 false 不开启推送
# 开启消息推送必须填入 sckey，如何获取请参考 http://sc.ftqq.com/3.version。感谢Server酱～
enable = true
sckey ="SCU138307T7193b3c585fd20cea3fd227e7b1044dc5fe3057a17d88"

**Comment by ZRT-1998** [comment]
我拉的代码有问题？我收到了

**Comment by huanghyw** [comment]
配置文件里面把引号去掉

**Comment by huanghyw** [comment]
等号后面一个空格

**Comment by ZRT-1998** [comment]
额

**Comment by huanghyw** [comment]
sckey = SCU138307T7193b3c585fd20cea3fd227e7b1044dc5fe3057a17d88

**Comment by huanghyw** [comment]
还有一点需要注意下，server酱有个限制，同样标题同样内容在貌似在一分钟还是多少时间内是不能重复发送的

**Comment by huanghyw** [comment]
别忘把sckey重置一下

**Comment by ZRT-1998** [comment]
ok
