### ISSUE TITLE
登录二维码，使用jd App扫描识别不了

### ISSUE THREAD

**Issue by netcode001** [huanghyw/jd_seckill#78]
mac电脑使用pycharm运行代码，出现登录二维码后，使用京东APP扫描登录，但是一直扫描不成功。造成不能登录。
京东app把这个二维码识别程商品了。
我把图片保存到手机里面，在扫描也是不能登录，请问有遇到的吗？怎么解决？

**Comment by huanghyw** [comment]
图片查看软件的背景不能是深色的，会有干扰，白色最好

**Comment by netcode001** [comment]
> 图片查看软件的背景不能是深色的，会有干扰，白色最好

谢谢，已经调通了

**Comment by theRockLiu** [comment]
朋友 怎么解决的 我也有这个问题

**Comment by theRockLiu** [comment]
> > 图片查看软件的背景不能是深色的，会有干扰，白色最好
> 
> 谢谢，已经调通了

朋友 怎么解决的 我也有这个问题

**Comment by huanghyw** [comment]
注意下一下图片查看软件背景不能是黑色的

**Comment by netcode001** [comment]
> 朋友 怎么解决的 我也有这个问题

下载一个 IMGSee app，打开每次生成的二维码就可以了。是白色的底色。
