### ISSUE TITLE
你好，在到提交订单的时候就出现了错误，麻烦可以帮忙看一下吗

### ISSUE THREAD

**Issue by rost001** [huanghyw/jd_seckill#8]
详情如下
![image](https://user-images.githubusercontent.com/36664434/102159168-f9770500-3ebd-11eb-8e03-07a07c850170.png)
![image](https://user-images.githubusercontent.com/36664434/102159284-2fb48480-3ebe-11eb-93b4-a23d36f9e6a9.png)
然后如果抢不到了之后就会出现，像是正常的结果
![image](https://user-images.githubusercontent.com/36664434/102159309-3e9b3700-3ebe-11eb-97aa-f657063d5690.png)

**Comment by huanghyw** [comment]
京东接口返回异常，正常应该返回json，但是返回了一个页面。应该是接口并发太高，对部分请求进行了熔断，这个问题可以忽略，异常之后会有重试机制。

**Comment by rost001** [comment]
好的，那这个就是没有抢购没有抢到对吧

**Comment by huanghyw** [comment]
对，可以多关注着订单列表，抢到了就去待付款里面支付即可

**Comment by rost001** [comment]
好的，谢谢你了
