### ISSUE TITLE
不知道作者最近几天有没有遇到302的问题

### ISSUE THREAD

**Issue by Wwzb** [huanghyw/jd_seckill#80]
我是用Java写的程序，之前还可以正常抢购，最近几天都没有成功过，看了看日志除了失败的以外还返回了新的内容，不知道作者最近有没有遇到过，也不知道是不是JD的机制改了，返回结果如图：
![image](https://user-images.githubusercontent.com/39238599/103130289-0b834f80-46d7-11eb-800c-0818942e286a.png)

**Comment by huanghyw** [comment]
抢购的也是茅台吗？目前应该没问题，今天还有一个朋友用这个脚本抢到两瓶。

**Comment by Wwzb** [comment]
> 抢购的也是茅台吗？目前应该没问题，今天还有一个朋友用这个脚本抢到两瓶。

是的，之前也是没问题，就最近几天突然出现的302，有点奇怪，我再用python试试看

**Comment by huanghyw** [comment]
好的，可以走走断点，看看哪有不一样

**Comment by huanghyw** [comment]
还有，确保cookie没有失效

**Comment by Wwzb** [comment]
> 还有，确保cookie没有失效

cookie不可能失效的，我是提前几分钟登录的，我这边是多账号多线程下发，不太好断点。。每天就那么一分钟能复现。。只能多打点日志观察了。。
