### ISSUE TITLE
抢购失败，无法获取生成订单的基本信息，接口返回:【'addressList'】

### ISSUE THREAD

**Issue by Git-Wilson** [huanghyw/jd_seckill#81]
如题，请问这个是什么问题啊？
另外，我4个账号，抢了2周一个都没中，会使什么原因呢？麻烦指条明路，谢谢！
![image](https://user-images.githubusercontent.com/75881301/103136499-ed7c1600-46fb-11eb-99e7-2699a492cdd8.png)

**Comment by Shauming** [comment]
+1
我也遇到了一样的问题，看log一堆addressList的报错，还请帮忙定位问题在哪里，谢谢。

**Comment by hungter007** [comment]
_get_seckill_init_info 应该是这里获取地址，发票，token信息的时候出错了吧，确认一下扫码登陆之类状态

**Comment by 91chen1** [comment]
请问下抢购链接获取失败是怎么回事

**Comment by huanghyw** [comment]
> +1
> 我也遇到了一样的问题，看log一堆addressList的报错，还请帮忙定位问题在哪里，谢谢。



> 如题，请问这个是什么问题啊？
> 另外，我4个账号，抢了2周一个都没中，会使什么原因呢？麻烦指条明路，谢谢！
> ![image](https://user-images.githubusercontent.com/75881301/103136499-ed7c1600-46fb-11eb-99e7-2699a492cdd8.png)

这是京东返回的数据，偶尔会返回异常，如果一直出错从来没有成功过就需要检查一下自己的配置是否正确，扫码是否正常

**Comment by Git-Wilson** [comment]
> > +1
> > 我也遇到了一样的问题，看log一堆addressList的报错，还请帮忙定位问题在哪里，谢谢。
> 
> > 如题，请问这个是什么问题啊？
> > 另外，我4个账号，抢了2周一个都没中，会使什么原因呢？麻烦指条明路，谢谢！
> > ![image](https://user-images.githubusercontent.com/75881301/103136499-ed7c1600-46fb-11eb-99e7-2699a492cdd8.png)
> 
> 这是京东返回的数据，偶尔会返回异常，如果一直出错从来没有成功过就需要检查一下自己的配置是否正确，扫码是否正常

需要手动配置的只有eid和fp吧，都没有问题，扫码登陆也没问题。就是从来没抢中过。。。。。
比较奇怪的是，eid和fp对于不同账号好像也是一样的
