### ISSUE TITLE
不是plus会员可以抢购吗？

### ISSUE THREAD

**Issue by smartnikocj** [huanghyw/jd_seckill#82]
大佬好，
【前提】：不是京东plus会员。

运行脚本后：
1、选1提示预约成功（网页和APP都因不是【plus会员】无法预约），所以提示预约成功真的是成功吗（对非会员账户来说）？
2、选2后非会员可以抢购？
谢谢！

**Comment by XiaoHb233** [comment]
不能，京东plus才行

**Comment by smartnikocj** [comment]
> 不能，京东plus才行

明白了，谢谢！
