### ISSUE TITLE
开了二次验证扫码登录不成功

### ISSUE THREAD

**Issue by Lasx** [huanghyw/jd_seckill#84]
开了二次验证扫码登录不成功，会直接退出。

**Comment by XiaoHb233** [comment]
你可以试试cookie

**Comment by Lasx** [comment]
我关了二次验证。不搞那么麻烦了。另外有个问题，预约时间和抢购时间是同一个时间？万一时间差一点那不是就预约不上了，也就无法抢购了。

**Comment by Lasx** [comment]
lxml 只能用4.5.1的吗？最新是4.6.2
