### ISSUE TITLE
不会找eid,和fp，能否出个详细的小白教程啊

### ISSUE THREAD

**Issue by rcfan1** [huanghyw/jd_seckill#9]

**Comment by rost001** [comment]
在购物车里提交一个订单，然后抓包，有一个可以找到，或者在console输入var eid = $('#eid').val();
var fp = $('#fp').val();在打印出来就可以了

**Comment by rcfan1** [comment]
> 在购物车里提交一个订单，然后抓包，有一个可以找到，或者在console输入var eid = $('#eid').val();
> var fp = $('#fp').val();在打印出来就可以了

找到了，原来是找的位置不对导致的，谢谢了

**Comment by taylor618** [comment]
> > 在购物车里提交一个订单，然后抓包，有一个可以找到，或者在console输入var eid = $('#eid').val();
> > var fp = $('#fp').val();在打印出来就可以了
> 
> 找到了，原来是找的位置不对导致的，谢谢了
求教能不能发个教程呀，谢谢了

**Comment by rcfan1** [comment]
> > > 在购物车里提交一个订单，然后抓包，有一个可以找到，或者在console输入var eid = $('#eid').val();
> > > var fp = $('#fp').val();在打印出来就可以了
> > 
> > 
> > 找到了，原来是找的位置不对导致的，谢谢了
> > 求教能不能发个教程呀，谢谢了

打开京东PC端官网，并登陆，
随便加一个商品进入购物车，然后点击 去结算，
F12，sources,Watch,输入_JdTdudfp即可。

我第一次没点去结算，所以没获取到，以上就是小白教程
