### ISSUE TITLE
这个是怎么回事

### ISSUE THREAD

**Issue by yongyuanlin** [huanghyw/jd_seckill#90]
![QQ图片20201227135121](https://user-images.githubusercontent.com/76577177/103164805-b0726980-484a-11eb-8d56-574355ea8555.png)

**Comment by hungter007** [comment]
目录不对找不到文件呀兄弟

**Comment by yongyuanlin** [comment]
> 目录不对找不到文件呀兄弟

大佬 应该放那个文件夹里

**Comment by hungter007** [comment]
> > 目录不对找不到文件呀兄弟
> 
> 大佬 应该放那个文件夹里

你的requirements.txt放在哪个文件就在那个文件夹下执行这个命令

**Comment by yongyuanlin** [comment]
> > > 目录不对找不到文件呀兄弟
> > 
> > 
> > 大佬应该放那个文件夹里
> 
> 你的requirements.txt放在哪个文件就在那个文件夹下执行这个命令

![QQ图片20201227135121](https://user-images.githubusercontent.com/76577177/103166188-8cb71f80-485a-11eb-8122-55351244655f.png)
之后又这样

**Comment by alpha-hxb** [comment]
我也是报这个

**Comment by iNOmoNey** [comment]
> > > > 目录不对找不到文件呀兄弟
> > > 
> > > 
> > > 大佬应该放那个文件夹里
> > 
> > 
> > 你的requirements.txt放在哪个文件就在那个文件夹下执行这个命令
> 
> ![QQ图片20201227135121](https://user-images.githubusercontent.com/76577177/103166188-8cb71f80-485a-11eb-8122-55351244655f.png)
> 之后又这样

估计是版本不兼容的问题吧。在requirements.txt 中把 lxml版本换成4.6.2。
