### ISSUE TITLE
大神，“链接获取失败，请稍后再试。”哪里出问题了

### ISSUE THREAD

**Issue by sea1636** [huanghyw/jd_seckill#95]
大神，“链接获取失败，请稍后再试。”哪里出问题了

**Comment by wuchiawuchi** [comment]
我也是 我再猜想 是不是非抢购期间都提示这个

**Comment by 91chen1** [comment]
我也是这个情况

**Comment by jiangzuochen** [comment]
配置文件里，buy_time要设置一下哈。注意日期！日期！

**Comment by LuvTian** [comment]
> 配置文件里，buy_time要设置一下哈。注意日期！日期！

这个日期设置成多少啊?我设为buy_time = 2020-12-28 10:00:00.100000  也是 INFO: 抢购链接获取失败，稍后自动重试
