### ISSUE TITLE
INFO: 抢购链接获取失败，稍后自动重试

### ISSUE THREAD

**Issue by wuchiawuchi** [huanghyw/jd_seckill#96]
这个是正常现象 还是在非抢购期间都提示这个？

**Comment by jinooooooo** [comment]
调整config里的buy_time参数

**Comment by LuvTian** [comment]
> 调整config里的buy_time参数

by_time时间应该设置成多少，运行脚本时的时间吗？还是之前的任意时间

**Comment by huanghyw** [comment]
> 这个是正常现象 还是在非抢购期间都提示这个？

只有抢购期间才能获取到链接
