### ISSUE TITLE
启动后没有预约成功是怎么回事

### ISSUE THREAD

**Issue by 13338639858** [huanghyw/jd_seckill#98]
oooo oooooooooo.            .oooooo..o                     oooo         o8o  oooo  oooo
       `888 `888'   `Y8b          d8P'    `Y8                     `888         `"'  `888  `888
        888  888      888         Y88bo.       .ooooo.   .ooooo.   888  oooo  oooo   888   888
        888  888      888          `"Y8888o.  d88' `88b d88' `"Y8  888 .8P'   `888   888   888
        888  888      888 8888888      `"Y88b 888ooo888 888        888888.     888   888   888
        888  888     d88'         oo     .d8P 888    .o 888   .o8  888 `88b.   888   888   888
    .o. 88P o888bood8P'           8""88888P'  `Y8bod8P' `Y8bod8P' o888o o888o o888o o888o o888o
    `Y888P

功能列表：
 1.预约商品
 2.秒杀抢购商品

请选择:1
2020-12-27 22:30:37,484 - 7552-MainThread - C:\maotai\jd_spider_requests.py[line:364] - INFO: 商品名称:【茅台白酒】飞天 53%vol  500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
2020-12-27 22:30:37,570 - 7552-MainThread - C:\maotai\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-28 09:59:59.500000，检测本地时间与京东服务器时间误差为【-1048】毫秒

我在网页端看没有预约 是哪里错了吗 EID FP都填上了

**Comment by 514892637** [comment]
你是不是设置的预约？2020-12-27 22:30:37,570 - 7552-MainThread - C:\maotai\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-28 09:59:59.500000， 你看如果选的预约，那么程序就会等到你设置的预约时间才启动

**Comment by 514892637** [comment]
> ```
>    oooo oooooooooo.            .oooooo..o                     oooo         o8o  oooo  oooo
>    `888 `888'   `Y8b          d8P'    `Y8                     `888         `"'  `888  `888
>     888  888      888         Y88bo.       .ooooo.   .ooooo.   888  oooo  oooo   888   888
>     888  888      888          `"Y8888o.  d88' `88b d88' `"Y8  888 .8P'   `888   888   888
>     888  888      888 8888888      `"Y88b 888ooo888 888        888888.     888   888   888
>     888  888     d88'         oo     .d8P 888    .o 888   .o8  888 `88b.   888   888   888
> .o. 88P o888bood8P'           8""88888P'  `Y8bod8P' `Y8bod8P' o888o o888o o888o o888o o888o
> `Y888P
> ```
> 
> 功能列表：
> 1.预约商品
> 2.秒杀抢购商品
> 
> 请选择:1
> 2020-12-27 22:30:37,484 - 7552-MainThread - C:\maotai\jd_spider_requests.py[line:364] - INFO: 商品名称:【茅台白酒】飞天 53%vol 500ml 贵州茅台酒（带杯）【行情 报价 价格 评测】-京东
> 2020-12-27 22:30:37,570 - 7552-MainThread - C:\maotai\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-28 09:59:59.500000，检测本地时间与京东服务器时间误差为【-1048】毫秒
> 
> 我在网页端看没有预约 是哪里错了吗 EID FP都填上了

你是不是设置的预约？2020-12-27 22:30:37,570 - 7552-MainThread - C:\maotai\timer.py[line:45] - INFO: 正在等待到达设定时间:2020-12-28 09:59:59.500000， 你看如果选的预约，那么程序就会等到你设置的预约时间才启动
