### ISSUE TITLE
抢到之后，是不是得手动去手机端支付？

### ISSUE THREAD

**Issue by kojayhuang** [huanghyw/jd_seckill#99]
![image](https://user-images.githubusercontent.com/65299127/103177362-b13fe580-48b4-11eb-8a35-e1f5ed8a270f.png)
如果没有上述情况的话，密码就不用填了吧？

**Comment by huanghyw** [comment]
如果有支付密码并且上次支付使用过京卡或者茅豆就需要填写，不然可能下单失败。

抢购成功后去手机端或PC端支付。
